### ISSUE TITLE
handling mailto: with the command line

### ISSUE THREAD

**Issue by apm256** [astroidmail/astroid#11]
Hi gauteh,
I tryto not bother you with tons of feature requests :-), but have you planned to allow triggering "Compose new mail" thanks to the command line?
Something like:
`astroid "mailto:?subject=$1&body=$2"`
It would be useful to handle "mailto:" link from a browser, for instance.
Best regards,

**Comment by gauteh** [comment]
Hi, I've finally gotten this to work so that mailto works with `astroid -m address` even if astroid is already running. All the fields are not implemented yet, but I'll close this for now as the main functionality is working.
