### ISSUE TITLE
Print css : font size

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#128]
Try to print an email. See the font size is too big.

**Comment by gauteh** [comment]
Hugo Roy writes on mai 10, 2016 19:57:
> Try to print an email. See the font size is too big.

This hit me too a few times.. can probably be fixed in the css (as you
suggest).

**Comment by hugoroy** [comment]
↪ mai 10, 2016 11:28 — Gaute Hope:
> Hugo Roy writes on mai 10, 2016 19:57:
>> Try to print an email. See the font size is too big.
> 
> This hit me too a few times.. can probably be fixed in the css (as you
> suggest). 

I tried adding a font-size but it did not affect it. I have to look
deeper :)

**Comment by gauteh** [comment]
Fixed in #178.
