### ISSUE TITLE
Encryption on a per-email basis

### ISSUE THREAD

**Issue by mardukbp** [astroidmail/astroid#133]
Unfortunately, very few people send encrypted emails. However, when they do, I would like to reply with an encrypted email. It would be nice to have a switch to turn encryption on as we do for the signature.

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 13, 2016 22:22:
> Unfortunately, very few people send encrypted emails. However, when they do, I would like to reply with an encrypted email. It would be nice to have a switch to turn encryption on as we do for the signature.

Yes. Decryption works to some extent. Needs to be implemented, then the
UI would look something like the signatures.

**Comment by gauteh** [comment]
#168: WIP.

**Comment by gauteh** [comment]
Fixed.
