### ISSUE TITLE
Cannot quit first instance after opening two instances of astroid

### ISSUE THREAD

**Issue by mardukbp** [astroidmail/astroid#136]
I performed the following experiment in Ubuntu 15.10 with both Gnome and i3:

1. Launch astroid
2. Launch another instance of astroid
3. Press `q` to quit the second instance
4. Press `q` to quit the first instance. The yes/no prompt comes up, but it does not accept any answer. I have to focus another window and then focus astroid again in order to be able to select `y` or `n`.

**Comment by gauteh** [comment]
Yeah, this happens sometimes. Not sure what the problem is..

**Comment by mardukbp** [comment]
I tried to debug it using `xprop`, `xev` and the log of i3 but could not figure it out. Any suggestions?

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 23, 2016 9:32:
> I tried to debug it using `xprop`, `xev` and the log of i3 but could not figure it out. Any suggestions?

There is something wrong with the way focus is grabbed, you could have
a look at the code. I believe it is in main_window.cc focus_in /
focus_out events. Perhaps it is not properly done when a window is quit.

Also, it seems focus is not properly given to the editor instance when
starting a new mail in the first instance after quitting the second
instance.

**Comment by gauteh** [comment]
Gaute Hope writes on mai 23, 2016 10:35:
> Marduk Bolaños writes on mai 23, 2016 9:32:
>> I tried to debug it using `xprop`, `xev` and the log of i3 but could not figure it out. Any suggestions?
> 
> There is something wrong with the way focus is grabbed, you could have
> a look at the code. I believe it is in main_window.cc focus_in /
> focus_out events. Perhaps it is not properly done when a window is quit.
> 
> Also, it seems focus is not properly given to the editor instance when
> starting a new mail in the first instance after quitting the second
> instance.
> 

Put some more debug messages in there and into the grab_focus of the
modes (mode.cc) then you should be able to follow where the focus is going.

**Comment by gauteh** [comment]
Could you test latest 'master' or 'plugins' and see if this problem
still persists? I re-organized the way key events are handled and both
quitting the main window and keyhandling should be better now.

-gaute

**Comment by apm256** [comment]
FWI, the problem seems have disappeared in my case.

**Comment by mardukbp** [comment]
Works great!

Thank you very much!

**Comment by gauteh** [comment]
Great!
