### ISSUE TITLE
Colored tags

### ISSUE THREAD

**Issue by aureooms** [astroidmail/astroid#139]
Would there be an easy way to specify different colors for different tags? Possibly background color with matching text color like in gmail, random would be ok, better if it can be matched with gmail color (I don't know if there is any way to retrieve this). I would find this very useful. Tags displayed in the thread index in monochrome color do not seem to help me to sort through mail in any way.

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 18, 2016 22:05:
> Would there be an easy way to specify different colors for different tags? Possibly background color with matching text color like in gmail, random would be ok, better if it can be matched with gmail color (I don't know if there is any way to retrieve this). I would find this very useful. Tags displayed in the thread index in monochrome color do not seem to help me to sort through mail in any way.
> 

I think most ways (not involving synchronization) could be implemented
fairly easily - what would the algorithm be? It would be nice with:

- the same tag gets the same color always
- tags next to each other (alphabetically sorted) dont have the same
  color

**Comment by aureooms** [comment]
Via hashing you get the first but not necessarily the second, although getting the same color for two different tags alphabetically close would be rather rare. The background color of the headers in [this example](https://aureooms-research.github.io/pats-game/) are generated exactly with this technique (last 6 hex digit of the hash). You can restrict to nice pastel colors by mixing a random color with white.

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 18, 2016 22:44:
> Via hashing you get the first but not necessarily the second, although getting the same color for two different tags alphabetically close would be rather rare. The background color of the headers in [this example](https://aureooms-research.github.io/pats-game/) are generated exactly with this technique (last 6 hex digit of the hash). You can restrict to nice pastel colors by mixing a random color with white.
> 

That could work, what exactly is the algorithm that you use there? I
think it would be best to mix it with light gray or something (if that
works).

**Comment by aureooms** [comment]
SHA1

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 19, 2016 10:02:
> SHA1

I am using MD5, since I had it readily available without extra
dependencies.

Please test #140. 
- Do you think that the base color should be configurable? 
- What should the default be? 
- Should it be weighted? Like I do now
- Should the color mixing be configurable?

**Comment by aureooms** [comment]
I will give it a shot tonight

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 19, 2016 10:57:
> I will give it a shot tonight
> 

Ok great! I bet @hugoroyd (pinged) has an opinion as well ;)!

**Comment by hugoroy** [comment]
I'd like to ping my favourite designer @jancborchardt on this :-)

**Comment by hugoroy** [comment]
The way it is now, the colours are hardly distinctive... it's very subtle. I don't know if it's that useful (but it doesn't seem to hurt).

![capture d ecran de 2016-05-19 21-43-41](https://cloud.githubusercontent.com/assets/1629771/15407373/cb0dfa12-1e0a-11e6-96d0-f3c93f351b1e.png)

**Comment by gauteh** [comment]
Hugo Roy writes on mai 19, 2016 21:48:
> The way it is now, the colours are hardly distinctive... it's very subtle. I don't know if it's that useful (but it doesn't seem to hurt).

Agreed, need better defaults: you can tune it with the config options:
tags_blend_color and tags_blend_weight.

**Comment by aureooms** [comment]
Like @hugoroy said: hardly distinctive, but still better than a uniform color on all tags in my opinion.

Two potential issues:
  - The fact that the background of the UI is white restricts the range of colors you can use to dark ones.
  - Also some of the tags of the "selected thread" (highlighted in blue) are more difficult to read.

Somehow, the way gmail handles this looks more flexible: having a colored background and a complementary text color for each tag avoids the two issues.

![2016-05-19-223937_1222x43](https://cloud.githubusercontent.com/assets/5165674/15408913/b7825ca6-1e12-11e6-83ff-50b15502d433.png)

![2016-05-19-224452_1224x41](https://cloud.githubusercontent.com/assets/5165674/15409070/7ec32228-1e13-11e6-9d45-3d5407d6258c.png)

To compute a complementary color you have several options:
  - http://stackoverflow.com/a/21924155/1582182
  - http://stackoverflow.com/a/1664186/1582182

Or just choose between dark or light complementary color (gmail uses 'rgb(102, 102, 102)' on light background and 'rgb(243, 243, 243)' on dark background)
  - http://stackoverflow.com/a/24261119/1582182

**Comment by aureooms** [comment]
Also it looks like the option `tags_blend_weight` parameter does the opposite of what it should do: it gives the % of random color that is added to the `tags_blend_color`. Shouldn't it be the other way around?

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 19, 2016 23:20:
> Also it looks like the option `tags_blend_weight` parameter does the opposite of what it should do: it gives the % of random color that is added to the `tags_blend_color`. Shouldn't it be the other way around?
> 

Maybe we should have a background color for: unselected and selected
rows. I think I prefer two fixed colors like gmail, but they should be
configurable.

If you use a whiter blend-color they will be more discernible, if you
turn up the blend_weight it will also be more discernible.

I agree that the name perhaps means the opposite now, but I thought it
would be more useful to be able to adjust the weight of the tag-color
because then you can turn it completely off.

It would be great if you could suggest some sane values for this. I'll
see if I can add some background..

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 19, 2016 23:20:
> Also it looks like the option `tags_blend_weight` parameter does the opposite of what it should do: it gives the % of random color that is added to the `tags_blend_color`. Shouldn't it be the other way around?

Please try the latest version:

- Change default blend color to white (please update your config)
- Change default weight to 1.0 (please update your config)
- Added background color for unselected
- Added background color for selected

both background colors are by default the same, but they can be
configured.

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 19, 2016 23:13:
> Somehow, the way gmail handles this looks more flexible: having a colored background and a complementary text color for each tag avoids the two issues.

I just realized that you meant that the background color should be
changed, not necessarily the text. Please let me know if you still think
this is the best solution after having tested the newest changes.

**Comment by aureooms** [comment]
I'll let you know next week. No access to computer this weekend.

**Comment by hugoroy** [comment]
I think that having a uniform-color background isn't making it better.

I like the notmuch and low-hanging-fruit backgrounds and text color combinations here:
![capture d ecran de 2016-05-20 21-56-32](https://cloud.githubusercontent.com/assets/1629771/15440472/e5232834-1ed5-11e6-9feb-f0a8f81d6eb1.png)

Why not have the background and text color both derive from the same thing but with a different transformation so we can have this kind of nice effects?

**Comment by aureooms** [comment]
> I just realized that you meant that the background color should be changed, not necessarily the text. Please let me know if you still think this is the best solution after having tested the newest changes.

I just tested and I still think you should try with a random background color instead of a random text color. Like @hugoroy noted, github uses a similar system for issues labels colors with the text color being way darker or lighter than the background color (but not fixed).

**Comment by gauteh** [comment]
Aurélien Ooms writes on mai 24, 2016 22:51:
>> I just realized that you meant that the background color should be changed, not necessarily the text. Please let me know if you still think this is the best solution after having tested the newest changes.
> 
> I just tested and I still think you should try with a random background color instead of a random text color. Like @hugoroy noted, github uses a similar system for issues labels colors with the text color being way darker or lighter than the background color (but not fixed).
> 

Yeah - I agree. It should give more stable results. Will see if I can
come up with something.. The text will then be either white or black
depending on the background color, the background color will then be
random (based on md5 sum) within some dark range or withing some light
range.

**Comment by gauteh** [comment]
Gaute Hope writes on mai 25, 2016 9:07:
> Aurélien Ooms writes on mai 24, 2016 22:51:
>>> I just realized that you meant that the background color should be changed, not necessarily the text. Please let me know if you still think this is the best solution after having tested the newest changes.
>> 
>> I just tested and I still think you should try with a random background color instead of a random text color. Like @hugoroy noted, github uses a similar system for issues labels colors with the text color being way darker or lighter than the background color (but not fixed).
>> 
> 
> Yeah - I agree. It should give more stable results. Will see if I can
> come up with something.. The text will then be either white or black
> depending on the background color, the background color will then be
> random (based on md5 sum) within some dark range or withing some light
> range.
> 

I am now varying the background color and setting the font color based
on whether the background is above or below #888888. I am not sure if I
like the default color for 'inbox', but this is a start. 

The random color is normalized to be between #f2f2f2 and #333333, to
make sure that the background color is not too light or dark. Things
might look better with a blend color as well (before deciding font
color). You can experiment by varying the colors in
thread_index_list_cell_renderer.cc:338.

**Comment by gauteh** [comment]
Gaute Hope writes on mai 31, 2016 12:07:
> I am now varying the background color and setting the font color based
> on whether the background is above or below #888888. I am not sure if I
> like the default color for 'inbox', but this is a start. 

Now using luminosity to determine foreground color.

**Comment by gauteh** [comment]
Gaute Hope writes on mai 31, 2016 13:35:
> Gaute Hope writes on mai 31, 2016 12:07:
>> I am now varying the background color and setting the font color based
>> on whether the background is above or below #888888. I am not sure if I
>> like the default color for 'inbox', but this is a start. 
> 
> Now using luminosity to determine foreground color.
 
Added colors to tags in thread-view.

**Comment by aureooms** [comment]
Looks good to me. What about removing commas and slightly smaller font for tags?
Also, it looks better to me when I add more spacing between lines. However the blue selected background looks a bit off when I do this (see screenshot).
![2016-06-02-102509_1439x218](https://cloud.githubusercontent.com/assets/5165674/15738628/749e6052-28ac-11e6-8b8e-5d056b84d3c0.png)

**Comment by aureooms** [comment]
Looks amazing!

**Comment by gauteh** [comment]
I think it is great. I have been missing this for a long time! You will
also see colored tags in the thread-view now.

I think the colors generated now are sensible, it feels less random when
the font is more stable.

The previous configuration options regarding tag colors are all gone,
you now only configure upper and lower color boundaries - and I think
the defaults are sensible now.

Anyone else have any comments before merging?

**Comment by gauteh** [comment]
Merged.

**Comment by aureooms** [comment]
Little glitch: when there are many tags so that the last one ends with an ellipsis, the MD5 hash is wrongly computed.

![2016-06-05-143817_1439x33](https://cloud.githubusercontent.com/assets/5165674/15805483/8814a394-2b2c-11e6-9cbf-21e73a2c8eeb.png)
![2016-06-05-143731_1439x34](https://cloud.githubusercontent.com/assets/5165674/15805482/861d386c-2b2c-11e6-86c9-b0d5cf3128db.png)

**Comment by hugoroy** [comment]
The tags are really too flashy to my taste. It seems that it's all I can see right now as if they're the most important information. Are they?

My first suggestion is not to colour the tag and revert the previous look for the thread view.

**Comment by aureooms** [comment]
What if you adjust the config files to get less flashy colors. I don't know what should be the default.

**Comment by gauteh** [comment]
Aurélien Ooms writes on juni 5, 2016 14:49:
> Little glitch: when there are many tags so that the last one ends with an ellipsis, the MD5 hash is wrongly computed.

Should be fixed.

**Comment by gauteh** [comment]
Hugo Roy writes on juni 5, 2016 15:32:
> The tags are really too flashy to my taste. It seems that it's all I can see right now as if they're the most important information. Are they?
> 
> My first suggestion is not to colour the tag and revert the previous look for the thread view.
> 

You could set for instance the upper and lower bounds to be very close,
that should result in less flashy colors.

The default is now a quite wide range, this results in very different
colors for the different tags.

**Comment by hugoroy** [comment]
Is it possible to set the colours by rgba() instead of html hex code?

**Comment by gauteh** [comment]
Hugo Roy writes on juni 5, 2016 19:18:
> Is it possible to set the colours by rgba() instead of html hex code?
> 

Both pango and webkit should support alpha, so the hex color spec could
be extended to that. How should the alpha value work on colors?

> tag font size?

In thread-view?

In the thread-index there is one font for the whole line.

> horizontal space vs vertical-space

This is currently one white-space char (in both thread-index and
thread-view). The white-space could maybe be reduced with using a <span>
tag with a reduced font-size.

In the thread-index you can change the vertical spacing with the
line-spacing option.

**Comment by hugoroy** [comment]
↪ juin 5, 2016 8:27 — Gaute Hope:
>> horizontal space vs vertical-space
> 
> This is currently one white-space char (in both thread-index and
> thread-view). The white-space could maybe be reduced with using a <span>
> tag with a reduced font-size.
> 

In the thread index, this should be smaller than a white space then. But
this is GTK, so I have no idea how to affect that.

**Comment by apm256** [comment]
Thank you for this new feature!

Related to:

>  The tags are really too flashy to my taste. It seems that it's all I can see right now as if they're the most important information. Are they?

Perhaps an option `uncolored_tags`, similar to `hidden_tags`, would be sensible?

**Comment by gauteh** [comment]
Gaute Hope writes on juni 5, 2016 20:27:
> Hugo Roy writes on juni 5, 2016 19:18:
>> Is it possible to set the colours by rgba() instead of html hex code?
>> 
> 
> Both pango and webkit should support alpha, so the hex color spec could
> be extended to that. How should the alpha value work on colors?

I imagine the alpha value should not be sliding from the upper to the
lower bound, and also it should not be random based on tag. 

So we should probably have an extra config option: tags_alpha_color: [0,
1]. If you set it to 0, background color will be disabled.

If you try for instance to have a upper and lower bounds close to
#ffffff, and a alpha of 0.5 the tag color should be a lot less
pronounced.

**Comment by gauteh** [comment]
Check out multi-tag-colors branch:

* You can now specify an alpha value (default is 0.5)
* Horizontal space in thread-index decreased.

**Comment by jancborchardt** [comment]
I recommend using hsl (hue, saturation, lightness) for computing the colors. You can set a defined percentage for saturation and lightness, and then only adjust the hue (color on the spectrum). That leads to getting a lot of different colors which seem from a similar family.

To not make the tags so extremely prominent there are some things:
- make the tags more pastel colored
- only color the text
- only have a dot/circle in front of each tag name which is colored. Like `⏺ tagname` (using [black circle for record](http://www.fileformat.info/info/unicode/char/23fa/index.htm)), maybe even without a space between the circle if it’s too much whitespace

**Comment by hugoroy** [comment]
Using that unicode character might not be a good idea. It would be too easy to have a font where it does not work. 

FTR this is how it appears to me here: 
![capture d ecran de 2016-06-08 23-31-30](https://cloud.githubusercontent.com/assets/1629771/15911668/2622e892-2dd1-11e6-96aa-8a5186655b01.png)

Otherwise I think it's a good idea worth looking at. I feel the coloured boxes are too much.

**Comment by aureooms** [comment]
Its seems like people differ in opinions about those tags. It's C++,
right?! Could we have a polymorphic approach to allow any kind of handling
for those tags with a finite set of predefined handlers --- textonly with
commas, boxes, little circle, even "do not display" --- ?

**Comment by gauteh** [comment]
Did you test the latest version on multi-tag-colors: now on #155 ? 

It uses alpha values, making the colors much less pronounced. You could
experiment with different alphas and color boundaries.

Will see if I can test out HSV soon.

I think coloring the background gives the most readable and stable
result (first experiments used colored text, and it looked more random).

**Comment by gauteh** [comment]
Aurélien Ooms writes on juni 8, 2016 23:44:
> Its seems like people differ in opinions about those tags. It's C++,
> right?! Could we have a polymorphic approach to allow any kind of handling
> for those tags with a finite set of predefined handlers --- textonly with
> commas, boxes, little circle, even "do not display" --- ?

Could definetely have a one or two options - it is a pretty significant
part of the user interface. One of the options should be just plain text.

Would be great to agree on one sensible option first though :)

**Comment by gauteh** [comment]
I wrote a small HSV tag format plugin at: https://github.com/astroidmail/astroid-plugin-hsv-tagcolor

if you use the `plugins` branch of astroid and install the plugin per
the instructions in its [README](https://github.com/astroidmail/astroid-plugin-hsv-tagcolor#readme), you will get HSV tag colors (saturation
and value parameters are configurable in the normal config).

Regards, Gaute

**Comment by hugoroy** [comment]
Should we move the whole colored tag feature to a plugin? 

Anyway, I also think that Jan's approach would be good to try. The pastel colours are better for the background, but it still looks a bit intimidating.

**Comment by gauteh** [comment]
Hugo Roy writes on juni 19, 2016 10:30:
> Should we move the whole colored tag feature to a plugin? 

I think it would be best to have one default method included. 
 
> Anyway, I also think that Jan's approach would be good to try. The pastel colours are better for the background, but it still looks a bit intimidating.

I just realized Jan's approach used HSL, I'll change it.

Did you try to out changing the `saturation` and `value` parameters? It
might also be worth putting a range on `hue` and adding an `alpha`
paramter.

Regards, Gaute

**Comment by gauteh** [comment]
Gaute Hope writes on juni 19, 2016 10:37:
> Hugo Roy writes on juni 19, 2016 10:30:
>> Anyway, I also think that Jan's approach would be good to try. The pastel colours are better for the background, but it still looks a bit intimidating.
> 
> I just realized Jan's approach used HSL, I'll change it.
> 

HLS is now default, you can use HSV as well. Added 'alpha' value (also
configurable).
