### ISSUE TITLE
Prompt before performing any destructive operation

### ISSUE THREAD

**Issue by mardukbp** [astroidmail/astroid#150]
notmuch as a matter of principle does not allow deleting emails. However, in astroid it is possible to delete things. Namely, entries in the search history and saved queries. Since, in my experience, this operations cannot be reverted using undo, it would be better to prompt the user before executing them.

**Comment by gauteh** [comment]
I think the best is to make the actions undoable, except the
clear-searches which should prompt before clearing. Also probably not
too hard, you could try ;)

**Comment by hugoroy** [comment]
Yes, allowing to undo things is definitely better than prompting before any action.

I really like how Gnome's Nautilus handles file deletion. Deleting any file prompts something like this:

![capture d ecran de 2016-05-28 14-15-30](https://cloud.githubusercontent.com/assets/1629771/15627258/b583e366-24de-11e6-8b5f-eeb099921b87.png)

Having this in Astroid would be ideal :-)

**Comment by gauteh** [comment]
Hugo Roy writes on mai 28, 2016 14:17:
> Yes, allowing to undo things is definitely better than prompting before any action.
> 
> I really like how Gnome's Nautilus handles file deletion. Deleting any file prompts something like this:
> 
> ![capture d ecran de 2016-05-28 14-15-30](https://cloud.githubusercontent.com/assets/1629771/15627258/b583e366-24de-11e6-8b5f-eeb099921b87.png)
> 
> Having this in Astroid would be ideal :-)

Sounds good, would be better if it was consistent with the current
revealer-prompt at the bottom. But this could potentially be moved up to
the prettier drop-down nautilus-style box.

**Comment by hugoroy** [comment]
↪ mai 30, 2016 10:15 — Gaute Hope:
> Sounds good, would be better if it was consistent with the current
> revealer-prompt at the bottom. But this could potentially be moved up to
> the prettier drop-down nautilus-style box.

Consistency is important, yes. But I don't think the two are the same
here. Cancelling an action is the exact opposite of Asking for
confirmation of an action after all :-)

Maybe moving the revealer-prompt to the top is a good idea.

**Comment by gauteh** [comment]
Now asking for confirmation.
