### ISSUE TITLE
Default keybindings

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#151]
Sorry for opening this can of worms :-) I guess everyone likes their own keybindings, and the fact that we can set our own keybindings is very important. But I'd like to discuss some of the current default keybindings in order to propose some changes. The aim is to make sure that a new astroid user is not surprised by the keybinidngs.

I think that default keybindings should be as common as possible with popular apps.

# Closing tabs (a "page" or "pane")

Right now, the default keybinding for closing a tab is `x` or `X`. 

I would like to propose changing this to `CTRL` + `w` or `CTRL` + `W`.   Because that's how to close tabs in most graphic clients which have tabs (web browser, file browser, graphical text editors, etc.)

# Opening a new search query

In astroid, opening a new tab is essentially the same thing as making a completely new notmuch query (as opposed to "refining" the query of the existing thread view pane). So in terms of keybinding, we can either make something usually associated with searches, or something associated with opening a new tab like `CTRL` + `t`.

The problem that I see with the current keybinding `F` is that it's too close to forwarding.

I have personally set `main_window.search` to `/` but I think we can discuss something else if slash isn't associated with searches enough. `CTRL` + `F` may be more associated with searches but (1) I feel the keybinding is a bit annoying for something as common as making a new notmuch query and (2) it's already taken to get the Saved Searches view (and I think it makes sense)

# Navigating between tabs ("pages")

In order to navigate between "pages" the current keybindings are `b` and `B`. This is the kind of keybinding that the user would never be able to guess (unless it's a keybinding taken from another program but I donk't know which).

I understand that `CTRL` + `Tab` and `CTRL` + `TAB` should be the obvious choices (in addition to the awful Gtk `CTRL` + `PgDwn` and `CTRL` + `PgUp` which on most laptops require 3 keys to be pressed as PgUp and PgDwn is often a Fn). But that they may be rather difficult to implement at the moment.

I personally replaced `B` with `h` and `b` with `l` so that I get "vim like" navigation which are a nice combination with `j` and `k`. I think that h and l are more nerdy and other uses would just expect the Ctrl + Tab.

Of course, we can discuss other keybindings :-)

**Comment by gauteh** [comment]
Hugo Roy writes on mai 28, 2016 15:44:
> Sorry for opening this can of worms :-) I guess everyone likes their own keybindings, and the fact that we can set our own keybindings is very important. But I'd like to discuss some of the current default keybindings in order to propose some changes. The aim is to make sure that a new astroid user is not surprised by the keybinidngs.
 

Totally fine :) I welcome it. See below..

> I think that default keybindings should be as common as possible with popular apps.
> 
> # Closing tabs (a "page" or "pane")
> 
> Right now, the default keybinding for closing a tab is `x` or `X`. 
> 
> I would like to propose changing this to `CTRL` + `w` or `CTRL` + `W`.   Because that's how to close tabs in most graphic clients which have tabs (web browser, file browser, graphical text editors, etc.)

Agreed, I like the few-keystrokes way. But I could always change it
back, maybe add them as alternates.

> 
> # Opening a new search query
> 
> In astroid, opening a new tab is essentially the same thing as making a completely new notmuch query (as opposed to "refining" the query of the existing thread view pane). So in terms of keybinding, we can either make something usually associated with searches, or something associated with opening a new tab like `CTRL` + `t`.
> 
> The problem that I see with the current keybinding `F` is that it's too close to forwarding.

True..
> 
> I have personally set `main_window.search` to `/` but I think we can discuss something else if slash isn't associated with searches enough. `CTRL` + `F` may be more associated with searches but I feel the keybinding is a bit annoying for something as common as making a new notmuch query.

Currently '/' is set to search in the Thread View, and I think this
makes sense. Perhaps it would work to shadow it while in thread-view. I
like that there is only one key-stroke for this, and I think that new
users very quickly gets used to it. Otherwise Ctrl-F is the most
logical. 

I am up for changing it to something else, but I think it
should be one-key, maybe '/'.

> 
> # Navigating between tabs ("pages")
> 
> In order to navigate between "pages" the current keybindings are `b` and `B`. This is the kind of keybinding that the user would never be able to guess (unless it's a keybinding taken from another program but I donk't know which).
> 
> I understand that `CTRL` + `Tab` and `CTRL` + `TAB` should be the obvious choices (in addition to the awful Gtk `CTRL` + `PgDwn` and `CTRL` + `PgUp` which on most laptops require 3 keys to be pressed as PgUp and PgDwn is often a Fn). But that they may be rather difficult to implement at the moment.
> 
> I personally replaced `B` with `h` and `b` with `l` so that I get "vim like" navigation which are a nice combination with `j` and `k`. I think that h and l are more nerdy and other uses would just expect the Ctrl + Tab.

'h' and 'l' are good, what do you have for changing tags then?

**Comment by hugoroy** [comment]
# Opening a new search query

>> I have personally set `main_window.search` to `/` but I think we can
>> discuss something else if slash isn't associated with searches
>> enough. `CTRL` + `F` may be more associated with searches but I feel
>> the keybinding is a bit annoying for something as common as making a
>> new notmuch query.
> 
> Currently '/' is set to search in the Thread View, and I think this
> makes sense.

Hm. Maybe I'm missing something, but it seems to me that, by default,
search in the Thread view is the same as in the Thread index: F.

> Perhaps it would work to shadow it while in thread-view. I
> like that there is only one key-stroke for this, and I think that new
> users very quickly gets used to it. Otherwise Ctrl-F is the most
> logical. 

Ctrl-F in the Thred view right now toggles the folded alignment. I could
totally get rid of that keybinding and reassign it to something like
searching within the content of the email (like searching within the
content of a web page). But this hasn't been implemented yet as far as I
can see.

> I am up for changing it to something else, but I think it
> should be one-key, maybe '/'.


I am also in favour of 

    main_window.search=/ 


# Navigating between tabs ("pages")

> 'h' and 'l' are good, what do you have for changing tags then?

I use `+` because I usually add tags (and I also used minus in the past
but it stopped working, now I see it should work again soon).

**Comment by gauteh** [comment]
Hugo Roy writes on mai 30, 2016 17:54:
> 
> # Opening a new search query
> 
>>> I have personally set `main_window.search` to `/` but I think we can
>>> discuss something else if slash isn't associated with searches
>>> enough. `CTRL` + `F` may be more associated with searches but I feel
>>> the keybinding is a bit annoying for something as common as making a
>>> new notmuch query.
>> 
>> Currently '/' is set to search in the Thread View, and I think this
>> makes sense.
> 
> Hm. Maybe I'm missing something, but it seems to me that, by default,
> search in the Thread view is the same as in the Thread index: F.

#142: It searches the text of the email.

> 
>> Perhaps it would work to shadow it while in thread-view. I
>> like that there is only one key-stroke for this, and I think that new
>> users very quickly gets used to it. Otherwise Ctrl-F is the most
>> logical. 
> 
> Ctrl-F in the Thred view right now toggles the folded alignment. I could
> totally get rid of that keybinding and reassign it to something like
> searching within the content of the email (like searching within the
> content of a web page). But this hasn't been implemented yet as far as I
> can see.

#142: see above :)

> 
>> I am up for changing it to something else, but I think it
>> should be one-key, maybe '/'.
> 
> 
> I am also in favour of 
> 
>     main_window.search=/ 
> 
> 
> # Navigating between tabs ("pages")
> 
>> 'h' and 'l' are good, what do you have for changing tags then?
> 
> I use `+` because I usually add tags (and I also used minus in the past
> but it stopped working, now I see it should work again soon).

You should spell it out 'Minus' (#148).

**Comment by hugoroy** [comment]
OK. #142 looks awesome and I would definitely use CTRL+F for this, again to be as close as possible to common apps.

**Comment by gauteh** [comment]
Hugo Roy writes on mai 30, 2016 18:09:
> OK. #142 looks awesome and I would definitely use CTRL+F for this, again to be as close as possible to common apps.
> 

Yeah - makes sense:

main_window.search=/
thread_view.search.search=C-f
thread_view.flat= # ???

main_window.next_page=l
main_window.next_page=b
main_window.previous_page=h
main_window.previous_page=B

thread_index.label= ??? (should be thread_index.tag..) 
# not sure if +/- makes a lot of sense

also all the other tag actions needs to be changed to the same key, i
think changing 'l' will break behaviour for several users.


-gaute

**Comment by hugoroy** [comment]
↪ mai 30, 2016 6:21 — Gaute Hope:
> Yeah - makes sense:
> 
> main_window.search=/
> thread_view.search.search=C-f

Search twice? :-)

> thread_view.flat= # ???

C-F ?

I never use that feature anyway. I just use the default option.

> main_window.next_page=l
> main_window.next_page=b
> main_window.previous_page=h
> main_window.previous_page=B
> 
> thread_index.label= ??? (should be thread_index.tag..) 
> # not sure if +/- makes a lot of sense
> 
> also all the other tag actions needs to be changed to the same key, i
> think changing 'l' will break behaviour for several users.

I agree that it's a pretty major change. But it's also easy to revert to
the previous behaviour in the keybindings file :)

Regarding other tag actions: there is `thread_index.label` and
`thread_view.tag_message`. Anything else?

I like + and - but I'm sure we can find something else.

t is taken. Ctrl+t is available but I don't like having to use Ctrl in
that scenario.

L is available.

**Comment by ff2000** [comment]
> > I have personally set `main_window.search` to `/` but I think we can discuss something else if slash isn't associated with searches enough. `CTRL` + `F` may be more associated with searches but I feel the keybinding is a bit annoying for something as common as making a new notmuch query.
> 
> Currently '/' is set to search in the Thread View, and I think this
> makes sense. Perhaps it would work to shadow it while in thread-view. I
> like that there is only one key-stroke for this, and I think that new
> users very quickly gets used to it. Otherwise Ctrl-F is the most
> logical. 
> 
> I am up for changing it to something else, but I think it
> should be one-key, maybe '/'.

If you don't insist on *s*earching threads or *f*inding them you can call
it simply "open a query". So I would say `o` for open a new query,
`O` for refine current query, `t` for open query in a new tab might
be OK, too.

**Comment by hugoroy** [comment]
> If you don't insist on *s*earching threads or *f*inding them you can call it simply "open a query". So I would say `o` for open a new query, `O` for refine current query, `t` for open query in a new tab might be OK, too.

o and O look like good candidates to replace F and v, I agree.

**Comment by gauteh** [comment]
Hugo Roy writes on mai 30, 2016 18:32:
> ↪ mai 30, 2016 6:21 — Gaute Hope:
>> Yeah - makes sense:
>> 
>> main_window.search=/
>> thread_view.search.search=C-f
> 
> Search twice? :-)

Yes, there are a few other search related options :)

# thread_view.search.search=/ # Search for text, default: /
# thread_view.search.cancel=GDK_KEY_Escape # Cancel current search, default: GDK_KEY_Escape
# thread_view.search.next=N # Go to next match, default: N
# thread_view.search.previous=P # Go to previous match, default: P

 
>> thread_view.flat= # ???
> 
> C-F ?
> 
> I never use that feature anyway. I just use the default option.

Hm, ok. C-F could work. I use it, but infrequently. But then I think it
is very useful. It is the only way to distinguish which email the reply
is to sometimes.
 
[...]
> 
> L is available.

Not quite, it is the shortcut for searching with 'tag:' already entered.

**Comment by gauteh** [comment]
Did we find a conclusion here?  `L` is not available now.

**Comment by hugoroy** [comment]
What about +/- (adding/removing tag)?

**Comment by gauteh** [comment]
Hugo Roy writes on juli 2, 2016 0:39:
> What about +/- (adding/removing tag)?

This is used for actions to multiple threads now.

**Comment by taziden** [comment]
I think +/- is kinda straightforward for adding/removing tags.
To apply actions to multiple threads, I'd prefer something like ";" which is the default in mutt for this.

**Comment by gauteh** [comment]
taziden writes on juli 8, 2016 18:58:
> I think +/- is kinda straightforward for adding/removing tags.

We only need one key though, since it is really editing tags, just '+'?
Or should both go to the same.

> To apply actions to multiple threads, I'd prefer something like ";" which is the default in mutt for this.

; sounds good.

**Comment by hugoroy** [comment]
Yes one is enough but it's a bit counterintuitive to press + to remove a tag. So having both keys used to add or remove tags makes sense. 

In any case + and - should have a related meaning.
-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by gauteh** [comment]
Please have a look at #171 to check if I remmebered it all and if it
makes sense.

Notably switching tabs are not super-logical, but I like 'h' and 'l'.

**Comment by hugoroy** [comment]
This looks great :-)
