### ISSUE TITLE
Shortcuts for startup queries

### ISSUE THREAD

**Issue by aureooms** [astroidmail/astroid#154]
It would be nice if there was a way to add/remove a query to the list of startup queries directly from the UI.
- add: a shortcut in thread index view + input field for the name
- remove: a shortcut in thread index view + yes/no confirmation

Maybe also shortcuts for reordering them (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>/<kbd>K</kbd>) and some visual hint to tell the difference between a startup query name and a regular one.

**Comment by gauteh** [comment]
Aurélien Ooms writes on juni 4, 2016 14:34:
> It would be nice if there was a way to add/remove a query to the list of startup queries directly from the UI.
> 
>   - add: a shortcut in thread index view + input field for the name
>   - remove: a shortcut in thread index view + yes/no confirmation
> 
> Maybe also shortcuts for reordering them (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>/<kbd>K</kbd>) and some visual hint to tell the difference between a startup query name and a regular query one.

Perhaps we should just remove startup-queries and only have saved
queries, then they can be marked as 'show-on-startup' with a keybinding
like you suggest.

**Comment by aureooms** [comment]
Yes! We might also keep both startup and saved queries if there is any use? Although I doubt there is one..

**Comment by aureooms** [comment]
Oh I see. Saved queries already exist!

**Comment by hugoroy** [comment]
I'm not sure keybindings are a good idea to manipulate that.

Maybe this could be done with a graphic interface with buttons or something like this.

**Comment by gauteh** [comment]
Hugo Roy writes on juli 23, 2016 18:21:
> Maybe this could be done with a graphic interface with buttons or something like this.

Maybe a toggle-button next to the saved query (with a header Show on
startup), I feel it would be logical from that view, but maybe not to
find in the first place.

**Comment by gauteh** [comment]
notmuch master now has support for saved queries, we should probably
implement our saved searches in that way.

**Comment by hugoroy** [comment]
I think this is implemented now, so we can close this :-)

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 0:29:
> I think this is implemented now, so we can close this :-)

I guess not exaclyt like intended, but with the saved searches it should
be possible :)
