### ISSUE TITLE
Composing and sending emails while offline

### ISSUE THREAD

**Issue by aureooms** [astroidmail/astroid#163]
While composing emails offline, how difficult would it be to be able to tell astroid to send composed emails as soon as a connection to the SMTP server is established. Or should it be implemented as a wrapper around msmtp and not appear in astroid (see [msmtpqueue](https://wiki.archlinux.org/index.php/msmtp#Using_msmtp_offline))?

**Comment by gauteh** [comment]
Aurélien Ooms writes on juni 25, 2016 17:13:
> While composing emails offline, how difficult would it be to be able to tell astroid to send composed emails as soon as a connection to the SMTP server is established. Or should it be implemented as a wrapper around msmtp and not appear in astroid (see [msmtpqueue](https://wiki.archlinux.org/index.php/msmtp#Using_msmtp_offline))?

It is definetely a useful feature, msmtpqueue should work as a drop-in
replacement, but you won't get the status in astroid or know that the
message is sent.

I think that for now the best would be to go for mstmpqueue, we can
rather pick up this issue again later if it becomes relevant.

You might want to call msmtp-runqueue from the beginning of the poll
script.

**Comment by emdete** [comment]
if queing is needed that shouldn't be done in astroid. i have a local exim installation which does exactly that job. following the unix philosophy: let one program do one job.

**Comment by gauteh** [comment]
This is useful information for the wiki.
