### ISSUE TITLE
display of quoting is wrong

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#164]
if quoting is done with a '>' only astroids quoting-display works fine, a line per level is displayed. if the quoting is done with '> ' (notice the space) the lines are still displayed fine but the '>' are partly displayed as well.

**Comment by gauteh** [comment]
M. Dietrich writes on juni 27, 2016 9:06:
> if quoting is done with a '>' only astroids quoting-display works fine, a line per level is displayed. if the quoting is done with '> ' (notice the space) the lines are still displayed fine but the '>' are partly displayed as well.

Ah, these are always hard to get right, could you give two explicit
examples: one working and one that demos how it breaks?

This is handled by the custom gmime filter: https://github.com/astroidmail/astroid/tree/master/src/utils/gmime

Regards, Gaute

**Comment by emdete** [comment]
a rough look into src/utils/gmime/gmime-filter-html-bq.c shows that citation depth and number of cut characters from the line is handled the same (as far as i understand the code). so a '> ' is one depth and two chars to cut. that's why '>>>' works fine while '> > > ' does not.

**Comment by gauteh** [comment]
#167.
