### ISSUE TITLE
astroid cores on 'qq' 

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#165]
whe setting `main_window.close_page=q` astroid cores when pressing two 'q'.

**Comment by gauteh** [comment]
M. Dietrich writes on juni 27, 2016 9:07:
> whe setting `main_window.close_page=q` astroid cores when pressing two 'q'.

this should be fixed now (only an issue on the plugins branch). caused
by modes destructing when they are invincible, so that when they are
actually destroyed they will be destructed twice.
