### ISSUE TITLE
Edit e-mail before sending without saving it to drafts

### ISSUE THREAD

**Issue by taziden** [astroidmail/astroid#174]
Hello,

After writing an e-mail and right before sending it, I'd like to be able to edit it again or delete it, without having to save it to drafts.

Regards,
taziden

**Comment by gauteh** [comment]
taziden writes on juli 13, 2016 15:00:
> Hello,
> 
> After writing an e-mail and right before sending it, I'd like to be able to edit it again or delete it, without having to save it to drafts.

Press Enter.

**Comment by taziden** [comment]
Oops. Thanks, it works like a charm. Sorry about that.

**Comment by gauteh** [comment]
Maybe we should have a hints bar, which can be disabled. It is not very
obvious currently. I am impressed that you kept using astroid without
knowing about this.
