### ISSUE TITLE
Scons failure: package gobject introspection not found

### ISSUE THREAD

**Issue by hughwilliams94** [astroidmail/astroid#176]
Using Kubuntu 16.04, when I try to compile I get an error stating that the gobject introspection package can't be found and then the build stops. I have seen elsewhere that this package may have a different name under debian/ubuntu: [http://stackoverflow.com/questions/18025730/pygobject-2-28-6-wont-configure-no-package-gobject-introspection-1-0-found](See here). Any suggestions

**Comment by gauteh** [comment]
Did you try installing libgirepository1.0-dev ? If you do figure it out,
please update the wiki!

(as a last resort, though I don't recommend it, you can use
--disable-plugins).

**Comment by gauteh** [comment]
Closing, need-info.

**Comment by hughwilliams94** [comment]
Yes this worked but then got another failure with missing Gmime-2.6.gir, I have looked around and this seems to be a known bug that has been fixed upstream just waiting for an update in the repos.

**Comment by gauteh** [comment]
You can copy the gir and typelib from the Arch  package for the time being, 
i think the bug was reported by another astroid user (@emdete: ?).

Hopefully it gets fixed soon. Did you get it to work with
--disable-plugins now?

Den mandag 18. juli 2016 skrev Hugh Williams <notifications@github.com> 
følgende:
> Yes this worked but then got another failure with missing Gmime-2.6.gir, I 
> have looked around and this seems to be a known bug that has been fixed 
> upstream just waiting for an update in the repos.

**Comment by gauteh** [comment]
Do you have a link for the upstream bug?

**Comment by hughwilliams94** [comment]
Got it working using the copied files but  iahvent been able to find the bug i was reading.

**Comment by gauteh** [comment]
Ok, good - hopefully the files are included in debian soon.

**Comment by gauteh** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829555

**Comment by airways** [comment]
In case someone else lands on this page, here is how I got the file since I did not see this explicitly described anywhere:

```
wget https://www.archlinux.org/packages/extra/i686/gmime/download/ -Ogmime.tgz
tar -xvf ./gmime.tgz
sudo cp usr/share/gir-1.0/GMime-2.6.gir /usr/share/gir-1.0/
rm -rf usr/ gmime.tgz
```
