### ISSUE TITLE
reply_all sometimes doesn't include From: address

### ISSUE THREAD

**Issue by taziden** [astroidmail/astroid#177]
Hello,

Seems like reply_all doesn't include the sender address if From: header is different from Reply-To:.
Maybe something else is triggering this but neither "reply" nor "reply all" include the initial sender as recipient in this case.

Regards,
taziden

**Comment by gauteh** [comment]
Should it? If the sender has set a Reply-To address then he doesn't want a reply sent to the From address.

**Comment by taziden** [comment]
For a simple Reply, I would expect the answer to follow what's indicated by Reply-To, but not with Reply All.

**Comment by gauteh** [comment]
I think I prefer the current behaviour, only include either From or Reply-To.
