### ISSUE TITLE
.cache/astroid not automatically created?

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#183]
Hi, I just installed astroid on a new machine. I could not open any attachment, as `~/.cache/astroid` did not exist.

**Comment by gauteh** [comment]
Hugo Roy writes on august 6, 2016 12:52:
> Hi, I just installed astroid on a new machine. I could not open any attachment, as `~/.cache/astroid` did not exist.

I moved the create_directories to config.cc and it should now be done on
startup.

-gaute
