### ISSUE TITLE
[Feature] Cancel sending message...

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#184]
Sometimes, when you press send, you realise while "sending message..." that you made a mistake somewhere, and that you would like to cancel sending the email. This is probably the only feature I remember from the days of using Gmail and that I miss in most email clients (which is a shame because it's really useful).

Do you think that's a good idea?

**Comment by gauteh** [comment]
Hugo Roy writes on august 6, 2016 13:14:
> Sometimes, when you press send, you realise while "sending message..." that you made a mistake somewhere, and that you would like to cancel sending the email. This is probably the only feature I remember from the days of using Gmail and that I miss in most email clients (which is a shame because it's really useful).
> 
> Do you think that's a good idea?
> 

I would like it with something like Ctrl+C. It is hard to guarantee that
it wasn't sent, depending on the sendmail program.

-gaute

**Comment by hugoroy** [comment]
Consider this use case: I changed to a new machine and forgot to set up msmtp. I tried to send an email. It obviously couldn't work, but still astroid was "sending message..." without me having any way in the UI to say: "Cancel" :-)

**Comment by gauteh** [comment]
Hugo Roy writes on august 7, 2016 0:21:
> Consider this use case: I changed to a new machine and forgot to set up msmtp. I tried to send an email. It obviously couldn't work, but still astroid was "sending message..." without me having any way in the UI to say: "Cancel" :-)

Yeah. it would be nice :) But in that case, msmtp should just fail and
you'd get an error message in astroid?

**Comment by hugoroy** [comment]
If we get deeper into this issue, I see 3 things:

0. set a delay in astroid of 5 (more?) seconds during which the user can "Cancel" the sending
1. have a way to show if the sending program fails
2. set a timeout for sending the message if it takes too much time (for instance if the mail has a large attachment and the connection is too slow): then give the user a choice between cancelling or ignore the timeout

**Comment by gauteh** [comment]
Hugo Roy writes on august 7, 2016 0:42:
> If we get deeper into this issue, I see 3 things:
> 
> 0. set a delay in astroid of 5 (more?) seconds during which the user can "Cancel" the sending

Why 5? What we need to know is whether the message has been sent or not.

> 1. have a way to show if the sending program fails

That is how it works now. Try disconnecting your network and sending a
message. This would be a similar response if you just killed the msmtp
program during sending.

> 2. set a timeout for sending the message if it takes too much time (for instance if the mail has a large attachment and the connection is too slow): then give the user a choice between cancelling or ignore the timeout

Why? The message should be sent anyway, if large attachment or
slow network the user should be able to decide.

In any case the user should either be able to cancel all the time, we
don't know if the sending program or server got the message already, but
probably not untill the program is completely finished. So we should
just allow the user to cancel all the time, but we cannot guarantee that
the message has not been sent. Maybe there are some notes on this in
MSMTP or SMTP docs, but it might differ between sendmail and servers.

**Comment by hugoroy** [comment]
> >  0. set a delay in astroid of 5 (more?) seconds during which the user can "Cancel" the sending
> 
> Why 5? What we need to know is whether the message has been sent or not.

I mean: some delay before actually launching the send command. This could be another way of approaching the problem instead of asking the user to confirm "Really send the message? [y/n]". (BTW, my brain has just wired that I just press y twice in order to send an email)

**Comment by gauteh** [comment]
Hugo Roy writes on august 7, 2016 1:54:
>> >  0. set a delay in astroid of 5 (more?) seconds during which the user can "Cancel" the sending
>> 
>> Why 5? What we need to know is whether the message has been sent or not.
> 
> I mean: some delay before actually launching the send command. This could be another way of approaching the problem instead of asking the user to confirm "Really send the message? [y/n]". (BTW, my brain has just wired that I just press y twice in order to send an email)
> 

Ah I see, yes - that is one option, I'm not sure I would like that
behavior though. Seems clumsy for most emails (especially short ones)
where you don't need to cancel the operation. 

Indeed, when I am sure I want to send the email I just double press 'y',
it is more there for the case when you accidentally press 'y' when
editing the email or something, then you are unlikely to press 'y'
twice.

Have a look at #185: this implements cancelling the sendmail program
with Ctrl+C, generally it seems that if 'msmtp' is killed before it is
allowed to finish the message has not been sent. There is not a way for
us to guarantee this though.

**Comment by gauteh** [comment]
#185 has been merged.
