### ISSUE TITLE
raw: could not convert

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#188]
the error

[ERROR] (15:54:07): raw: could not convert: ....

is not a mail conversion problem but a buffer length problem. the logged mail content contains garbage chars at the end (in this case "ÂÁ" which varies per invocation). i have a mail which is 16937 bytes (file size). if i log the len field in src/modes/raw_message.cc it gives me 16940 bytes length (i removed the filename line before that test). 

in another case i got 8779 / 8539 bytes mismatch in length of the mail. 

furthermore i found out that some mails open in one case and don't if you do the same operation again later.

**Comment by gauteh** [comment]
Please try the fix-raw branch.

**Comment by emdete** [comment]
it fixes the bad behaviour for me.

i would put the line s.write (out, written); inside the if (out != NULL) {...
