### ISSUE TITLE
seg fault on first start up

### ISSUE THREAD

**Issue by stdbull** [astroidmail/astroid#189]
Hi. I've just cloned and installed astroid on my gentoo machine. scons test runs ok. I get a seg fault immediately at start up. Back trace looks like this:
`
Starting program: /usr/local/bin/astroid 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[info ] (15:12:29): welcome to astroid! - v0.6-20-gda04fd01
[debug] (15:12:29): utf8: 1, UTF-8
[debug] (15:12:29): loading gtk..
[New Thread 0x7fffe2d70700 (LWP 6751)]
[New Thread 0x7fffe256f700 (LWP 6752)]
[debug] (15:12:29): HOME: /home/me
[info ] (15:12:29): cf: loading: "/home/me/.config/astroid/config"
[warn ] (15:12:29): cf: making runtime dir..

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff03d2775 in boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*) () from /usr/lib64/libboost_filesystem.so.1.56.0
(gdb) bt
#0  0x00007ffff03d2775 in boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*) () from /usr/lib64/libboost_filesystem.so.1.56.0
#1  0x00007ffff03d2c64 in boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*) () from /usr/lib64/libboost_filesystem.so.1.56.0
#2  0x0000000000698ec8 in boost::filesystem::create_directories (p=...) at /usr/include/boost/filesystem/operations.hpp:510
#3  0x000000000069666c in Astroid::Config::load_config (this=0xc4fbb0, initial=false) at src/config.cc:276
#4  0x0000000000693b85 in Astroid::Config::Config (this=0xc4fbb0, _test=false, no_load=false) at src/config.cc:32
#5  0x0000000000668035 in Astroid::Astroid::main (this=0xad48e0, argc=1, argv=0x7fffffffdb28) at src/astroid.cc:241
#6  0x00000000006593ec in main (argc=1, argv=0x7fffffffdb28) at src/main.cc:5
(gdb)
`
I have boost 1.56.0-r1. I've tried playing around with astroid options to create a  new config, and also a config in a different location, but the end result is always the same. Directory $HOME/.config/astroid/ always gets created but it's empty. Permissions look find (same as other dirs in $HOME/.config/).

Any thoughts as to what could be going wrong?
Thanks.

**Comment by gauteh** [comment]
Do you have a ~/.cache dir?

Den onsdag 10. august 2016 skrev Matthew Lear <notifications@github.com>
følgende:

**Comment by stdbull** [comment]
Yes I do.

**Comment by gauteh** [comment]
Could you try making the astroid dir in there manually?

Den onsdag 10. august 2016 skrev Matthew Lear <notifications@github.com>
følgende:

**Comment by stdbull** [comment]
Wonderful. That works :-) How come?

**Comment by stdbull** [comment]
Closing anyway. Thanks for the quick response.

**Comment by gauteh** [comment]
Matthew Lear writes on august 10, 2016 17:02:
> Wonderful. That works :-) How come?

A bug in what variable was used for creating the directory, should be
fixed now. Thanks for reporting.
