### ISSUE TITLE
Reply-To not shown in ThreadView

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#191]
Normally when replying to a mail, I hit reply-to-all in astroid. However this is not wanted if a sender has defined a reply-to. Unfortunately astroid doesn't show if a sender has a Reply-To defined (but reacts correctly if a simple reply is hit).

Can we somehow show an extra line with the Reply-To address **if** the sender has set one? This would help spotting those.

**Comment by gauteh** [comment]
mxmehl writes on august 12, 2016 12:36:
> Can we somehow show an extra line with the Reply-To address **if** the sender has set one? This would help spotting those.

Yep, use the same logic as for Bcc.

**Comment by gauteh** [comment]
Merged.
