### ISSUE TITLE
Focus on text/html alternative part or attachment when focus on previous message

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#204]
In the thread view, when you want to focus on the previous message, astroid will focus on that previous message's alternative parts or last attachment if it has some, instead of just focusing on the message.

For me, this results in often opening attachments or the html part of an email unintentionally.

**Comment by gauteh** [comment]
That it is intentional, you should be able to jump between messages with n
and p. I think 😊

Den søndag 28. august 2016 skrev Hugo Roy <notifications@github.com>
følgende:

**Comment by gauteh** [comment]
Gaute Hope writes on august 28, 2016 19:37:
> That it is intentional, you should be able to jump between messages with n
> and p. I think 😊

Disregard that, 'p' focuses the last element. I personally prefer the
behavior, and I don't know if one is more logical than the other.
Anyway, I can make an unbound target for switching focus ('p' style)
setting the focus to the message.

**Comment by hugoroy** [comment]
↪ Gaute Hope, août 28, 2016 7:48 :
> Gaute Hope writes on august 28, 2016 19:37:
>> That it is intentional, you should be able to jump between messages with n
>> and p. I think 😊
> 
> Disregard that, 'p' focuses the last element. I personally prefer the
> behavior, and I don't know if one is more logical than the other.
> Anyway, I can make an unbound target for switching focus ('p' style)
> setting the focus to the message. 


As far as I can tell, there are 3 kinds of prev/next movements in the
thread view:

 1. move focus between messages
 2. move focus between elemnets
 3. scroll and move focus between elements

I think that moving between messages (move 1) should only select the
message and not an elment inside of it. It works correctly this way for
going to the next message, but not when going to the previous message
where the focus gets on the last elments (which means that hitting Enter
to "hide" the email will instead open the attachment or the html part).

Does that make sense to you as well?

**Comment by gauteh** [comment]
Hugo Roy writes on august 28, 2016 20:45:
> ↪ Gaute Hope, août 28, 2016 7:48 :
>> Gaute Hope writes on august 28, 2016 19:37:
>>> That it is intentional, you should be able to jump between messages with n
>>> and p. I think 😊
>> 
>> Disregard that, 'p' focuses the last element. I personally prefer the
>> behavior, and I don't know if one is more logical than the other.
>> Anyway, I can make an unbound target for switching focus ('p' style)
>> setting the focus to the message. 
> 
> 
> As far as I can tell, there are 3 kinds of prev/next movements in the
> thread view:
> 
>  1. move focus between messages
>  2. move focus between elemnets
>  3. scroll and move focus between elements
> 
> I think that moving between messages (move 1) should only select the
> message and not an elment inside of it. It works correctly this way for
> going to the next message, but not when going to the previous message
> where the focus gets on the last elments (which means that hitting Enter
> to "hide" the email will instead open the attachment or the html part).
> 
> Does that make sense to you as well?

Yes, I'm sold. So to get to the last element one could do:

1. n
2. C-k

**Comment by hugoroy** [comment]
↪ Gaute Hope, août 28, 2016 10:22 :
> Yes, I'm sold. So to get to the last element one could do:
> 
> 1. n
> 2. C-k


It looks to me that C-k does not work as before (i.e. it does not go to
the previous element). Is it indended? I would think that only n/p
needed to be modified, but j/k and C-j/C-k worked correctly and consistently.

**Comment by gauteh** [comment]
Hugo Roy writes on august 28, 2016 23:40:
> ↪ Gaute Hope, août 28, 2016 10:22 :
>> Yes, I'm sold. So to get to the last element one could do:
>> 
>> 1. n
>> 2. C-k
> 
> 
> It looks to me that C-k does not work as before (i.e. it does not go to
> the previous element). Is it indended? I would think that only n/p
> needed to be modified, but j/k and C-j/C-k worked correctly and consistently.
> 

Right, should be fixed now.
