### ISSUE TITLE
Missing Gmime GIR on Ubuntu and Debian

### ISSUE THREAD

**Issue by starkers** [astroidmail/astroid#211]
Heya

Still trying to compile this up on Xenial (thanks for the quick fix earlier)

Currently its unable to find GMime gir file:

```
...
compiling ==> src/plugin/thread_view_activatable.c
compiling ==> src/plugin/gir_main.c
linking Program ==> girmain
LD_LIBRARY_PATH=./ g-ir-scanner -o Astroid-0.1.gir --warn-all --namespace=Astroid --include=GObject-2.0 --include=GMime-2.6 --nsversion=0.1 --pkg=gobject-introspection-1.0 --pkg=gmime-2.6 -Isrc/ --program=./girmain src/plugin/astroid_activatable.c src/plugin/gir_main.c src/plugin/thread_index_activatable.c src/plugin/thread_view_activatable.c src/plugin/astroid_activatable.h src/plugin/thread_index_activatable.h src/plugin/thread_view_activatable.h
Couldn't find include 'GMime-2.6.gir' (search path: '['gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0']')
```

There are several .gir files installed but certainly no GMime ones.

A quick update and search and even with *universe* there are absolutely no .gir files matching a search for "mime" available.

```
# apt-file update
...blabla...
# apt-file find .gir | grep -i mime
#
```

...any advice welcome :-)

**Comment by gauteh** [comment]
This is due to a bug in the debian / ubuntu gmime package. It doesn't
build the GIR and Typelib packages. You can copy them from another
distribution, --disable-plugins, or bug ubuntu / debian:

Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829555

Copy from arch: #176.

**Comment by starkers** [comment]
Thanks for the link, will go badger them now!

**Comment by gauteh** [comment]
David Stark writes on september 6, 2016 13:43:
> Thanks for the link, will go badger them now!

That's the spirit!

**Comment by starkers** [comment]
I have no words for how much I hate the whole GI stuff.. I dabled with some gtk3 in python and it made me so depressed but being able to auto-complete in vim... *sigh*

**Comment by gauteh** [comment]
David Stark writes on september 6, 2016 13:48:
> I have no words for how much I hate the whole GI stuff.. I dabled with some gtk3 in python and it made me so depressed but being able to auto-complete in vim... *sigh*
> 

Yes - autocomplete in vim is surprisingly hard. I use youcompleteme now,
but will try the stuff from: https://www.vi-improved.org/recommendations/ when I get the chance.

**Comment by starkers** [comment]
hmm interesting, reluctantly moved to YCM also, noted for now :+1:

**Comment by mardukbp** [comment]
Ubuntu 16.10 includes the missing file. Installing [libgmime](http://packages.ubuntu.com/yakkety/libgmime-2.6-0) and [libgmime-dev](http://packages.ubuntu.com/yakkety/libgmime-2.6-dev) in Ubuntu 16.04 solves this issue.

**Comment by gauteh** [comment]
Ok, good. Thanks for letting me know! I'll close this issue then.

**Comment by aweiher** [comment]
Sorry, but issue is not resolved on ubuntu 16.04 by installing this libs: 

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
$ dpkg -L libgmime-2.6-dev|grep gir
$ dpkg -L libgmime-2.6-0 |grep gir
$ 
```

I use `scons  --disable-plugins` for now.

**Comment by mardukbp** [comment]
Did you install the Ubuntu 16.10 packages linked to in my comment? What is the compile error you get? Please explain what did you do and what happened.

**Comment by airways** [comment]
This was blocking me as well after fighting through many other Ubuntu 14.04 related issues. Kind of a bummer, feels so close.

Here is how to get the file from arch's package, I did not see this explicitly described anywhere:

```
wget https://www.archlinux.org/packages/extra/i686/gmime/download/ -Ogmime.tgz
tar -xvf ./gmime.tgz
sudo cp usr/share/gir-1.0/GMime-2.6.gir /usr/share/gir-1.0/
rm -rf usr/ gmime.tgz
```
