### ISSUE TITLE
Unable to add "BackSpace" as a keybinding

### ISSUE THREAD

**Issue by Radvendii** [astroidmail/astroid#212]
There seems to be a hardcoded list of special keys (return, arrow keys, question mark, etc) that are allowed in keybindings, and have other keywords that are mapped to the GDK_KEY_whatever. First of all, is there a way to allow arbitrary GDK_KEY_whatever variables in the keybindings file? Alternatively, should someone (I can do this) add a comprehensive list? Also, this is documented nowhere. The wiki says to use devel/get_keys.py to get the list of default keybindings, but this generates a list with, for example,

`# searches.open=Key (GDK_KEY_Return) # Open query, default: Key (GDK_KEY_Return), Key (GDK_KEY_KP_Enter)`

which, if uncommented, doesn't run (since the proper command would be searches.open=Return
Another issue with the documentation is that it is totally unclear how to set multiple keys to the same action. The commented out lines don't even show this being done, but just say that it has been done.

I am happy to make some of these changes, I am just new to the community and wanted to know what peoples' feelings are about this and what this should be changed to.

**Comment by gauteh** [comment]
Radvendii writes on september 7, 2016 2:47:
> There seems to be a hardcoded list of special keys (return, arrow keys, question mark, etc) that are allowed in keybindings, and have other keywords that are mapped to the GDK_KEY_whatever. First of all, is there a way to allow arbitrary GDK_KEY_whatever variables in the keybindings file? Alternatively, should someone (I can do this) add a comprehensive list? Also, this is documented nowhere. The wiki says to use devel/get_keys.py to get the list of default keybindings, but this generates a list with, for example,
> 
> `# searches.open=Key (GDK_KEY_Return) # Open query, default: Key (GDK_KEY_Return), Key (GDK_KEY_KP_Enter)`
> 
> which, if uncommented, doesn't run (since the proper command would be searches.open=Return
> Another issue with the documentation is that it is totally unclear how to set multiple keys to the same action. The commented out lines don't even show this being done, but just say that it has been done.
> 
> I am happy to make some of these changes, I am just new to the community and wanted to know what peoples' feelings are about this and what this should be changed to.

Hi,

It would be great to get a proper system for this, the hardcoded list
was something of a quick fix. There is the:

`gdk_keval_from_name ()` and `gdk_keyval_name ()` functions that can be
used for this: https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#gdk-keyval-from-name.

Which could be used to use any of the key definitions in the GDK. Worth
mentioning is that the Shift modifier does not work yet either [#170].
Perhaps this could be made to work when the user has access to all of
GDKs keys.

These could probably be accessed from the `get_keys.py` script as well
(using GIR) when generating the key bindings file.

Both the documentation and the behavior needs improvements here, and if
you are interested in working on that, that would be great!

In case you did not figure it out already: You can just add multiple
key definitions to the same target to create aliases for that
key-binding. Once you set up a user defined binding all the _original_
definitions and aliases are dropped.

Regards, Gaute

**Comment by gauteh** [comment]
fixed in #216.
