### ISSUE TITLE
Config: how to open html sibling_container

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#222]
Depending on how well the HTML part of an email is formatted, the opening program may or may not be the right one in my experience.

Instead of having firefox open the part, more often than not I find myself with an emacs window. 

Maybe we could configure a special program for opening html "sibling_container" parts, in order to specify a web browser rather than, say, xdg-open.

**Comment by gauteh** [comment]
Currently the attachment.external_open_cmd configuration option is used.
I can see that this would be useful. Something like:
thread_view.open_external_part.

**Comment by hugoroy** [comment]
FYI, the new Firefox (v57) seems to have problems with opening files on "file:///" URI. Thus making it impossible for those who use firefox by default to see HTML-only emails. I think this makes this option even more important :-)

**Comment by gauteh** [comment]
Is this still relevant with the improved inline HTML support?

**Comment by gauteh** [comment]
Closing, probably not relevant anymore since we have much safer inline showing of html emails.
