### ISSUE TITLE
Distribute astroid using Flatpak

### ISSUE THREAD

**Issue by mardukbp** [astroidmail/astroid#224]
Given the difficulty to compile astroid under Debian-based distributions (#211) and the awesomeness of astroid, I would like to propose joining the new era of stand-alone Linux applications and distribute astroid using [Flatpak](http://flatpak.org/). Then astroid will be available in Gnome Software, i.e. one click away.

**Comment by gauteh** [comment]
I'm all for it!

**Comment by gauteh** [comment]
I'm all for it!

Marduk Bolaños writes on oktober 26, 2016 22:26:

**Comment by emdete** [comment]
i doubt that just copying the solutions of OSses like OSX for their problems is a good idea. i would rather convince a potential debian (or other distro) maintainer to include astroid and keep it up to date.

**Comment by gauteh** [comment]
Original (and distro-specific) packing systems is still just as possible, and not at all discouraged. But making a flatpak-package would make astroid easily available at systems that support flatpak as well.

**Comment by gauteh** [comment]
Closing, please go ahead and make a Flatpak if you have the time.
