### ISSUE TITLE
Cannot build Astroid against Archlinux's boost 1.62.0-2

### ISSUE THREAD

**Issue by grazzolini** [astroidmail/astroid#227]
Ever since the boost upgrade, astroid doesn't build against boost anymore. I am attaching the relevant build log.

[astroid-v0.6.r88.gc9ba5be-1-x86_64-build.txt](https://github.com/astroidmail/astroid/files/563979/astroid-v0.6.r88.gc9ba5be-1-x86_64-build.txt)

**Comment by gauteh** [comment]
Hi, I just pushed a fix for this - please try again with latest master.

**Comment by gauteh** [comment]
If you have issues try to do a full: `scons -c` and delete the .sconsign and .sconf_temp files/directories.

**Comment by grazzolini** [comment]
The push fixed the error for me. But whenever I face such rebuild errors, I always try to reproduce them in a clean chroot, using devtools and makechrootpkg. That log I provided was created using it. But I also just did rebuild it outside the chroot successfully, without needing to deal with scons.

**Comment by gauteh** [comment]
Good! I had some issues here with the gobject introspection file still
targeting the old boost libraries.

-gaute
