### ISSUE TITLE
Capital tab-complete bug

### ISSUE THREAD

**Issue by Radvendii** [astroidmail/astroid#228]
I've noticed that when I type a tag that begins with all-caps, it won't tab complete, but it will tab-complete if I type in the lowercase version of that tag.

For example, if I have a tag TAG, and I type in 'TA<tab>', it stays TA, but if I type in 'ta<tab>' it completes to TAG

**Comment by gauteh** [comment]
Please try #229, the completion should now be case-insensitive both
ways.
