### ISSUE TITLE
Doesn't jump to first unread mail in long threads

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#232]
I love the feature of astroid jumping to the first unread mail in a thread. Unfortunately this doesn't work in all cases, especially for long threads (>20 messages).

In those cases, astroid jumps to an already read mail, but marks the first unread mail as read (I use the auto-read feature after 0.5 seconds). This way, when I press TAB to go to the next unread mail, it either doesn't work (because there is no other unread mail in the thread anymore) or I skip the originally first unread mail in the thread and go to the second one instead. Both is not desired.

The issue is reproducible. When I mark the "faulty" mail as unread again and repeat the steps, the same bug arises. Maybe it's because the thread needs longer to load than the 0.5 seconds until the active email is marked as read? Please tell me whether you need any logs.

**Comment by gauteh** [comment]
Yes - sounds like a timing issue. Could you test #233?



Otherwise, is there any pattern to which e-mail is selected?

**Comment by mxmehl** [comment]
Will do so as soon as I find a thread where the issue arises, thanks. I don't find my reproducible example from yesterday anymore...

**Comment by gauteh** [comment]
mxmehl writes on november 18, 2016 0:31:
> Will do so as soon as I find a thread where the issue arises, thanks. I don't find my reproducible example from yesterday anymore...

Ok, I merged to master since I think this is a more correct way anyway.

**Comment by gauteh** [comment]
Closing, re-open if issue persists.

**Comment by mxmehl** [comment]
I'd reopen this issue. With longer threads (>15 mails) and especially with encrypted mails, sometimes astroid doesn't jump to the selected email but stays at top. I was able to catch one occurence (see below). Interestingly, when opening the thread another time, it works. Seems like something's getting cached.

Long log: https://p.mehl.mx/?92c7ecf4c87dacb8#y6GkdLKDxMP7HGjd2e8GN/RyjYaPqxWiKBIZDlBWZH4=

**Comment by gauteh** [comment]
Max writes on mars 6, 2017 15:10:
> I'd reopen this issue. With longer threads (>15 mails) and especially with encrypted mails, sometimes astroid doesn't jump to the selected email but stays at top. I was able to catch one occurence (see below). Interestingly, when opening the thread another time, it works. Seems like something's getting cached.
> 
> Long log: https://p.mehl.mx/?92c7ecf4c87dacb8#y6GkdLKDxMP7HGjd2e8GN/RyjYaPqxWiKBIZDlBWZH4=
> 

Sounds like we try to scroll to and set focus to the correct message
because not everything has been loaded and displayed yet. It goes faster
the second time (or second time one opens a thread in astroid after
startup) because the webkit libraries have been loaded.

**Comment by gauteh** [comment]
Might be able to use the 'document-load-finished' or 'web-view-ready'
signal/properties of webview.

https://webkitgtk.org/reference/webkitgtk/stable/webkitgtk-webkitwebview.html#WebKitWebView-web-view-ready

**Comment by mxmehl** [comment]
Doesn't happen that often to me but again with a longer thread. 

Long log: https://p.mehl.mx/?7bde1efe55a10093#4ucNBBPQL8GU09czP0v+BAffhfVBS61zQgVRyRxV5Kg=

**Comment by yeled** [comment]
Oh! This happens to me too. I assumed some OSX glitch.

**Comment by kirschner** [comment]
* Max [2017-05-29 12:53 +0200]:
> Doesn't happen that often to me but again with a longer thread. 
> 
> Long log: https://p.mehl.mx/?7bde1efe55a10093#4ucNBBPQL8GU09czP0v+BAffhfVBS61zQgVRyRxV5Kg=

I also had that a few times.

**Comment by yeled** [comment]
Can we re-open this? I have a thread I can replicate it in.

**Comment by gauteh** [comment]
Charlie Allom writes on juni 2, 2017 13:37:
> Can we re-open this? I have a thread I can replicate it in.

Yes.

**Comment by gauteh** [comment]
Closing, re-open if still an issue after webkit2.

**Comment by mxmehl** [comment]
Well, astroid jumps to the first unread mail but this sometimes causes usability problems on threads with multiple subthreads and an indented view.

Let's assume the following structure (I hope I've analysed this correctly):

```
mail1
- mail2
-- mail5 (unread)
- mail3
-- mail4 (unread)
```

Now, if I open this thread in astroid, I will start with seeing `mail4`, because it's the oldest unread email. When I press `TAB` to see the next unread email, I won't jump to `mail5` because it's above the currently selected `mail4`. The expected behaviour would be that when opening the thread, one sees the topmost mail first, disregarded its age.

Before webkit2, this somehow worked.

**Comment by rnav** [comment]
> Well, astroid jumps to the first unread mail but this sometimes causes usability problems on threads with multiple subthreads and an indented view.
> 
> Let's assume the following structure (I hope I've analysed this correctly):
> 
> ```
> mail1
> - mail2
> -- mail5 (unread)
> - mail3
> -- mail4 (unread)
> ```
> 
> Now, if I open this thread in astroid, I will start with seeing `mail4`, because it's the oldest unread email. When I press `TAB` to see the next unread email, I won't jump to `mail5` because it's above the currently selected `mail4`. The expected behaviour would be that when opening the thread, one sees the topmost mail first, disregarded its age.
> 
> Before webkit2, this somehow worked.

I'm facing issues due to this. What I see now is that astroid jumps to and shows `mail5` in the thread view (the topmost/first unread email). However, since `mail4` is older, astroid would have highlighted that email and ends up marking it as read. I end up having to scroll the view using mouse to try and figure out which email astroid has highlighted.
