### ISSUE TITLE
duplicated sig after a draft

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#234]
When a draft is editied the signiture is doublicated.

**Comment by gauteh** [comment]
We need to keep some extra properties for the messages to implement this
in a clean way. I belive newer notmuch supports that. If it is released
we could use that, and set a higher notmuch version requirement.

**Comment by gauteh** [comment]
Also need encryption / signed state in this way.

**Comment by mrvdb** [comment]
I have been using this as a workaround, not very clean, but seems to work for me:

``` diff
diff --git a/src/modes/edit_message.cc b/src/modes/edit_message.cc
index 754ab6b..a937a18 100644
--- a/src/modes/edit_message.cc
+++ b/src/modes/edit_message.cc
@@ -572,7 +572,7 @@ namespace Astroid {
   bool EditMessage::save_draft () {
     LOG (info) << "em: saving draft..";
     draft_saved = false;
-    ComposeMessage * c = make_message ();
+    ComposeMessage * c = make_draft_message ();
     ustring fname;
 
     bool add_to_notmuch = false;
@@ -1204,6 +1204,15 @@ namespace Astroid {
     return c;
   }
 
+  ComposeMessage * EditMessage::make_draft_message () {
+    ComposeMessage * c = setup_message ();
+    Bool sigsave = c->account->has_signature;
+    c->account->has_signature = false;
+    finalize_message (c);
+    c->account->has_signature = sigsave;
+
+    return c;
+  }
   /* }}} */
 
   void EditMessage::make_tmpfile () {
diff --git a/src/modes/edit_message.hh b/src/modes/edit_message.hh
index 6c5f88d..c99a8a1 100644
--- a/src/modes/edit_message.hh
+++ b/src/modes/edit_message.hh
@@ -100,6 +100,7 @@ namespace Astroid {
       ComposeMessage * setup_message ();
       void             finalize_message (ComposeMessage *);
       ComposeMessage * make_message ();
+      ComposeMessage * make_draft_message ();
 
       ComposeMessage * sending_message;
       std::atomic<bool> sending_in_progress;
```

**Comment by gauteh** [comment]
Marcel van der Boom writes on november 28, 2017 11:46:
> I have been using this as a workaround, not very clean, but seems to work for me:
> 
> ``` diff
> diff --git a/src/modes/edit_message.cc b/src/modes/edit_message.cc
> index 754ab6b..a937a18 100644
> --- a/src/modes/edit_message.cc
> +++ b/src/modes/edit_message.cc
> @@ -572,7 +572,7 @@ namespace Astroid {
>    bool EditMessage::save_draft () {
>      LOG (info) << "em: saving draft..";
>      draft_saved = false;
> -    ComposeMessage * c = make_message ();
> +    ComposeMessage * c = make_draft_message ();
>      ustring fname;
>  
>      bool add_to_notmuch = false;
> @@ -1204,6 +1204,15 @@ namespace Astroid {
>      return c;
>    }
>  
> +  ComposeMessage * EditMessage::make_draft_message () {
> +    ComposeMessage * c = setup_message ();
> +    Bool sigsave = c->account->has_signature;
> ```

This wouldn't track whether you have enabled/disabled the signature 
manually. It should probably cover most cases though.

- gaute

**Comment by mrvdb** [comment]
Excerpts from Gaute Hope's message of november 28, 2017 12:03:
> This wouldn't track whether you have enabled/disabled the signature 
> manually. It should probably cover most cases though.
> 
Correct, on every edit, it's basically a new choice to include sig or not, which is what I would like anyway.

**Comment by gauteh** [comment]
Marcel van der Boom writes on november 28, 2017 12:16:
> Excerpts from Gaute Hope's message of november 28, 2017 12:03:
>> This wouldn't track whether you have enabled/disabled the signature 
>> manually. It should probably cover most cases though.
>> 
> Correct, on every edit, it's basically a new choice to include sig or not, which is what I would like anyway. 
> 

Sounds reasonable, but what if:

* signature disabled by default
* new draft
* enable signature
* save
* re-open
* enable signature

**Comment by mrvdb** [comment]
what is your question exactly? for me it still works, i.e. choose signature only when sending, not on saving draft (regardless of the setting, the saved draft won't have the signature)

**Comment by gauteh** [comment]
Marcel van der Boom writes on november 28, 2017 12:30:
> what is your question exactly? for me it still works, i.e. choose signature only when sending, not on saving draft (regardless of the setting, the saved draft won't have the signature)
> 

Because in the case I described the signature would be duplicated.

**Comment by mrvdb** [comment]
how so? on save, the signature is not saved with it, or am I misunderstanding?

**Comment by gauteh** [comment]
Marcel van der Boom writes on november 28, 2017 12:47:
> how so? on save, the signature is not saved with it, or am I misunderstanding?

Hm, maybe I didn't read your patch correctly - in that case it would 
have to be re-enabled on the next edit even if you manually enabled it 
before saving?

**Comment by mrvdb** [comment]
yep

**Comment by gauteh** [comment]
Marcel van der Boom writes on november 28, 2017 12:49:
> yep

Ok, maybe this could be a temporary solution then. Maybe re-use the code 
in make_draft_.. and make_message..

**Comment by mrvdb** [comment]
I'll create a PR
