### ISSUE TITLE
Ability to configure default content part

### ISSUE THREAD

**Issue by deuill** [astroidmail/astroid#236]
Certain sources produce very, very bad plaintext emails, or do not even produce any *cough* *cough* *JIRA*, so it would be useful if there was a configuration variable for determining which part to show by default, or at the very least have the HTML part open if there's no plain-text part.

**Comment by gauteh** [comment]
Alex Palaistras writes on desember 2, 2016 10:29:
> Certain sources produce very, very bad plaintext emails, or do not even produce any *cough* *cough* *JIRA*, so it would be useful if there was a configuration variable for determining which part to show by default, or at the very least have the HTML part open if there's no plain-text part.

Yeah - at least for known sources. I have some security concerns with
HTML parts which has led me to make it off-by-default, so that the user
can turn it on only for sources that are trusted:

The whole thread is the same html-page in webkit in the thread-view.

This means that potentially the whole content of a thread can be
accessed from a malicious script that somehow made it through. Think an
attacker sending a message to a recipient where you know the message-id
of an target e-mail, these will get grouped together, upon opening the
same thread the javascript could potentially access the content of the
other e-mails.

Secondly; a malicious e-mail could break the HTML of the original
thread-view - appearing changing the content of the original e-mails
(think bank info, addresses.. etc).

Currently; I do not know a way that this _can_ happen - but to be on the
safe side I've just disabled HTML by default.

The best would be a simple config option, but perhaps it would be better
with a plugin where the user can specify his own logic for deciding
whether to open the HTML part? Too complicated?

# On the UI side:

Ideally it should be possible to collapse the expanded part again. Then
the original plain-text part should be collapsed at the same time.

**Comment by deuill** [comment]
I suppose you could wrap HTML email in a sandboxed iframe, as described here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox
https://msdn.microsoft.com/en-us/hh563496.aspx

However iframes have their own disadvantages, especially when it comes to setting the parent element height with regards to the iframe content, which needs to be scripted with `postMessage` and other fun stuff.

I believe Google do some processing using a framework called Caja, which cleans up HTML, CSS and Javascript for safety, and there's Content Security Policy, which I'm not sure fits as a solution but may be worth looking into...

Even if HTML email isn't open by default, the security implications remain, I suppose, so it may be worth looking into.

**Comment by gauteh** [comment]
Alex Palaistras writes on desember 4, 2016 17:27:
> I suppose you could wrap HTML email in a sandboxed iframe, as described here:
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox
> https://msdn.microsoft.com/en-us/hh563496.aspx
> 
> However iframes have their own disadvantages, especially when it comes to setting the parent element height with regards to the iframe content, which needs to be scripted with `postMessage` and other fun stuff.
> 
> I believe Google do some processing using a framework called Caja, which cleans up HTML, CSS and Javascript for safety, and there's Content Security Policy, which I'm not sure fits as a solution but may be worth looking into...
> 
> Even if HTML email isn't open by default, the security implications remain, I suppose, so it may be worth looking into.
> 

Sandboxed iframes looks promising, good idea. 

I agree, it is still a security concern. Note that none of the content
is actually loaded before you expand the part. The text part is
sanitized so it should not be possible to inject any HTML/JS there.

**Comment by gauteh** [comment]
Gaute Hope writes on desember 4, 2016 21:24:
> Alex Palaistras writes on desember 4, 2016 17:27:
>> I suppose you could wrap HTML email in a sandboxed iframe, as described here:
>> 
>> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox
>> https://msdn.microsoft.com/en-us/hh563496.aspx
>> 
>> However iframes have their own disadvantages, especially when it comes to setting the parent element height with regards to the iframe content, which needs to be scripted with `postMessage` and other fun stuff.
>> 
> 
> Sandboxed iframes looks promising, good idea. 
> 

Tried out sandboxed iframes, this will require quite a bit of
restructuring of how that content is rendered. It seems that the content
cannot be set at load time, but rather has to be entered after the
iframe has been rendered.

**Comment by deuill** [comment]
Hmmm, even when including the static HTML using `srcdoc`? I assumed that would work, but don't know enough about Astroid internals to say for certain.

**Comment by gauteh** [comment]
Alex Palaistras writes on desember 7, 2016 22:34:
> Hmmm, even when including the static HTML using `srcdoc`? I assumed that would work, but don't know enough about Astroid internals to say for certain.
> 

srcdoc would work - but then the html would still be in the original
namespace.

**Comment by gauteh** [comment]
Gaute Hope writes on desember 7, 2016 22:39:
> Alex Palaistras writes on desember 7, 2016 22:34:
>> Hmmm, even when including the static HTML using `srcdoc`? I assumed that would work, but don't know enough about Astroid internals to say for certain.
>> 
> 
> srcdoc would work - but then the html would still be in the original
> namespace.
 
Or, I guess it should be escaped - that could work.

**Comment by hugoroy** [comment]
Okay maybe this is a stupid idea, but since we have a webkit engine, why don't we open an HTML part in a new Astroid tab as a standalone page?

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 0:21:
> Okay maybe this is a stupid idea, but since we have a webkit engine, why don't we open an HTML part in a new Astroid tab as a standalone page?

That could work, but it would take it out of the thread context.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 2, 2017 9:35:
> Hugo Roy writes on mars 2, 2017 0:21:
>> Okay maybe this is a stupid idea, but since we have a webkit engine, why don't we open an HTML part in a new Astroid tab as a standalone page?
> 
> That could work, but it would take it out of the thread context.

Yes. But right now, it's opening another web browser so it's taken out
of the email context which is even worse :^)

So it seems like a good compromise to me, especially if it helps for
security (help by not tying to the "normal" web browser activity and
help by not spreading the HTML email to other emails in a tab).

**Comment by gauteh** [comment]
Yes, but this is as an alternative to showing the part internally.

**Comment by yeled** [comment]
fwiw, if you want HTML as default right now, apply this patch: https://gist.github.com/yeled/e85034afae7ad690d7e332a5157aa477

thanks @gauteh 😉

**Comment by hugoroy** [comment]
↪ Charlie Allom / novembre 9, 2017 11:51:
> fwiw, if you want HTML as default right now, apply this patch: https://gist.github.com/yeled/e85034afae7ad690d7e332a5157aa477
> 
> thanks @gauteh 😉 
> 

Thanks, but I prefer text by default :-)

**Comment by gauteh** [comment]
Do you have any suggestions for UI for swapping between alternative parts? Tabs? Something low-key HTML'y.

**Comment by iain-buclaw-sociomantic** [comment]
Actually, having swapped the preferred mime type, I now see the reverse happen, where text-only emails are hidden with `Alternative part (type: text/plain)`. So it seems that the preferred_type setting is a bit stronger than it needs to be.

Ideal behaviour should be:
- Mixed text + html: Show preferred content.
- text only: Always show text
- html only: Always show html
