### ISSUE TITLE
By default: encrypt emaill in answer to encrypted email

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#238]
I think this is quite important. If the user receives encrypted email (and that you're able to decrypt it), then his/her reply by default should be encrypted.

**Comment by gauteh** [comment]
Hugo Roy writes on desember 6, 2016 17:33:
> I think this is quite important. If the user receives encrypted email (and that you're able to decrypt it), then his/her reply by default should be encrypted.
> 

Agreed.

**Comment by gauteh** [comment]
Please try #240.

**Comment by hugoroy** [comment]
Maybe I'm wrong but I think it's a good idea to always sign when you encrypt.
Otherwise it's working correctly as far as I can test :-)

**Comment by gauteh** [comment]
Yeah, also notmuch doesn't make the distinction it seems - that might be a bug though.

**Comment by gauteh** [comment]
sign when encrypt. merged and closed.
