### ISSUE TITLE
libsass 3.4 breaks astroid on Arch Linux

### ISSUE THREAD

**Issue by micha-a-schmidt** [astroidmail/astroid#248]
After the update of libsass from 3.3.6 to 3.4.0 on Arch Linux, astroid crashes when opening an email with the error message:

[debug] (17:19:54): theme: loading..
[info ] (17:19:54): re: using installed resource: /home/mschmidt/.local/share/astroid/ui/thread-view.html
[debug] (17:19:54): tv: testing version: 3
[info ] (17:19:54): re: using installed resource: /home/mschmidt/.local/share/astroid/ui/thread-view.scss
[debug] (17:19:54): tv: testing version: 3
[info ] (17:19:54): theme: processing: /home/mschmidt/.local/share/astroid/ui/thread-view.scss
[ERROR] (17:19:54): theme: error processing: Internal Error: File context has no input path

(astroid:2467): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: theme: could not process scss: Internal Error: File context has no input path

[1]    2467 trace trap (core dumped)  astroid

**Comment by micha-a-schmidt** [comment]
Sorry, I just noticed that it is a duplicate of #244 .

**Comment by gauteh** [comment]
Thanks, posted bug to libsass. Will continue discussion in #244.
