### ISSUE TITLE
Show which pane is focused

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#251]
I started to use astroid's panes more often, especially opening threads in panes. However, I have noticed two unwanted behaviours:

1. Switching between panes is possible with C-Tab. But if I want to switch from right (thread view) to left (thread index), I have to press C-Tab twice. The other way round, pressing it once is sufficient.

2. There is no way how to tell which pane is active currently. When opening a thread in a new pane, it is the right pane by default, but as soon as I start to work in the other pane or different tabs, I start to get confused. Can we mark the active pane optically, for example by a horizontal blue bar on the bottom or top of the active pane, equivalently to how we mark active messages in thread view?

**Comment by gauteh** [comment]
Hi,

there was a discussion earlier were I was considering dropping the
panes. I no longer use them myself, and tracking focus between them has
proven a bit tricky.

The reasoning for dropping them is that the functionality can
essentially be achieved by using two windows (you can open a message
directly in a new window using: C-Return).

more below...:


mxmehl writes on desember 23, 2016 16:47:
> I started to use astroid's panes more often, especially opening threads in panes. However, I have noticed two unwanted behaviours:
> 
> 1. Switching between panes is possible with C-Tab. But if I want to switch from right (thread view) to left (thread index), I have to press C-Tab twice. The other way round, pressing it once is sufficient.

Usually it should be M-Tab, C-Tab is probably a Gtk binding for focusing
the previous element. That is why it behaves a bit unlogical. Does M-Tab
work ok?

 
> 2. There is no way how to tell which pane is active currently. When opening a thread in a new pane, it is the right pane by default, but as soon as I start to work in the other pane or different tabs, I start to get confused. Can we mark the active pane optically, for example by a horizontal blue bar on the bottom or top of the active pane, equivalently to how we mark active messages in thread view?

Yeah - that's a good point.

**Comment by mxmehl** [comment]
Am 24.12.2016 um 16:52 schrieb Gaute Hope:
> there was a discussion earlier were I was considering dropping the
> panes. I no longer use them myself, and tracking focus between them has
> proven a bit tricky.
> 
> The reasoning for dropping them is that the functionality can
> essentially be achieved by using two windows (you can open a message
> directly in a new window using: C-Return).

Hm, I wanted to start using panes on my large 16:9 screen because I'm
used to having all content in one window (except the new message
editor). But if this causes too much maintenance work, I could live with
dropping panes.

>> 1. Switching between panes is possible with C-Tab. But if I want to
>> switch from right (thread view) to left (thread index), I have to press
>> C-Tab twice. The other way round, pressing it once is sufficient.
> 
> Usually it should be M-Tab, C-Tab is probably a Gtk binding for focusing
> the previous element. That is why it behaves a bit unlogical. Does M-Tab
> work ok?

Ah, I noticed that I remapped `thread_index.pane_swap_focus` to `C-Tab`
because M-Tab is already taken system-wide (circle open windows).
However, using another keybinding works like expected. I assume this is
because C-Tab also has some meaning in my window manager or something.

**Comment by gauteh** [comment]
Max writes on desember 24, 2016 17:03:
> Am 24.12.2016 um 16:52 schrieb Gaute Hope:
>> there was a discussion earlier were I was considering dropping the
>> panes. I no longer use them myself, and tracking focus between them has
>> proven a bit tricky.
>> 
>> The reasoning for dropping them is that the functionality can
>> essentially be achieved by using two windows (you can open a message
>> directly in a new window using: C-Return).
> 
> Hm, I wanted to start using panes on my large 16:9 screen because I'm
> used to having all content in one window (except the new message
> editor). But if this causes too much maintenance work, I could live with
> dropping panes.
> 

Yeah - Is there anything that doesn't work now? (except that it's not
possible to distinguish which pane is focused). Could keep them, at
least for a while, I like the concept - its just extra maintenance.

**Comment by mxmehl** [comment]
Am 24.12.2016 um 17:12 schrieb Gaute Hope:
> Max writes on desember 24, 2016 17:03:
>> Hm, I wanted to start using panes on my large 16:9 screen because I'm
>> used to having all content in one window (except the new message
>> editor). But if this causes too much maintenance work, I could live with
>> dropping panes.
> 
> Yeah - Is there anything that doesn't work now? (except that it's not
> possible to distinguish which pane is focused). Could keep them, at
> least for a while, I like the concept - its just extra maintenance.

Nothing I know of. Maybe I'll test a few other keybindings for the
pane-switch to see if I can reproduce the strange behaviour with them,
or to find out how it is caused with C-Tab.

It would be good to hear a few other opinions. Panes are a cool concept
and they could also be handy for people who used the two/three column
design of Thunderbird or Outlook before, and who don't like multiple
open windows. Maybe we should advertise them a bit more, similar to as
we explain tabs in the wiki.

**Comment by gauteh** [comment]
Could you please try #280.
