### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by mardukbp** [astroidmail/astroid#253]
I have been experiencing random crashes after polling or while writing an email. I had compiled astroid a few months ago and so I decided to compile it again this week. However, the crashes still happen.

The log is filled with these errors:

```
(astroid:14920): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
```

I do not know if that is related.

OS: Ubuntu 16.04
Editor: Emacs

**Comment by gauteh** [comment]
Marduk Bolaños writes on desember 24, 2016 16:37:
> I have been experiencing random crashes after polling or while writing an email. I had compiled astroid a few months ago and so I decided to compile it again this week. However, the crashes still happen.
> 
> The log is filled with these errors:
> 
> ```
> (astroid:14920): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> ```

It might be: I've seen this error when I've had several windows open
with an editor open, then closing the window again. Have you had several
windows of Astroid open? It has proven tricky to reliably track focus in
this case.

Does the error happen when using an external editor?

If you could get a backtrace using gdb that would be very useful, ubuntu
might store the core dump somewhere else [0]. Also please post the log
leading up to a crash.

[0] http://stackoverflow.com/questions/2065912/core-dumped-but-core-file-is-not-in-current-directory

**Comment by gauteh** [comment]
Closing untill we get some more information.
