### ISSUE TITLE
astroid icon

### ISSUE THREAD

**Issue by mardukbp** [astroidmail/astroid#254]
I made an icon using the astroid curve. It is easy to change the color with gimp.

![astroid-icon](https://cloud.githubusercontent.com/assets/1140106/21484176/b93bec2c-cb8e-11e6-8285-31e5ee62c2e3.png)

**Comment by gauteh** [comment]
Hi, thanks - maybe this could be combined with an e-mail icon? At the moment it is very similar to this projects: https://www.astroid.org/

**Comment by mardukbp** [comment]
What do you think of this?

![astroid-icon-2](https://cloud.githubusercontent.com/assets/1140106/21572776/61077074-cedd-11e6-86f9-780c2c84b5bd.png)

**Comment by mardukbp** [comment]
I like this one better.

![astroid-icon-3](https://cloud.githubusercontent.com/assets/1140106/21576407/42d5c744-cf2e-11e6-9008-eafe86eb6ea4.png)

**Comment by gauteh** [comment]
Hm, I haven't really thought much about a icon for astroid, but I think it should be related to email, be fairly simple, be recognizable (indicate what the application does), and look good in few colors. Perhaps @hugoroy  and @jancborchardt have some insights.

**Comment by mxmehl** [comment]
The name "astroid" makes me thinking of asteroids. Maybe a burning envelope (flying into orbit) with a comet tail? I'd also prefer a clean and simple icon.

**Comment by gauteh** [comment]
@mxmehl: yeah, something along those lines would be fine.

**Comment by emdete** [comment]
how about somthing like this:

![astroid](https://cloud.githubusercontent.com/assets/3251523/21645527/99656efe-d292-11e6-8513-2e7549c68377.png)

comet tail + simple icon :)

**Comment by jancborchardt** [comment]
I recommend you post it on the Open Source Design job board at http://opensourcedesign.net/jobs/ :)
cc @gauteh

**Comment by MarcinWieczorek** [comment]
I'd add an envelope or an `@` to the first picture, inside the star. Keep it simple ;)

**Comment by elioqoshi** [comment]
![1](https://cloud.githubusercontent.com/assets/5436686/22371158/bfb8adc2-e495-11e6-9ca2-e61feb7f2978.jpg)

Took the time to work on a proposal. What do you think?

**Comment by gauteh** [comment]
@elioqoshi: not bad! I like it. I'm a bit afraid that the colors might confuse it with the python astroid package, but that can be remedied :) what do you think? I appreciate any opinions by the other contributors here as well.

**Comment by hugoroy** [comment]
Kudos! I like this. 
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by elioqoshi** [comment]
@gauteh Sure, we can change the colors if you think it can be confusing. Thanks for the comments :)

**Comment by kirschner** [comment]
@elioqoshi nice one!

**Comment by MarcinWieczorek** [comment]
I haven't noticed it until you said it :)

**Comment by elioqoshi** [comment]
@mxmehl That's true, I will fix that :)
I will tweak the font and icons and get back to you tomorrow

**Comment by koolfy** [comment]
I really really like this last icon set :)
(and will probably like any variation!)

**Comment by elioqoshi** [comment]
New version, using Exo 2 (licensed under an Open Font License). What do you think?

![2](https://cloud.githubusercontent.com/assets/5436686/22396334/a7da804c-e556-11e6-9402-a2587e4a93d9.jpg)

**Comment by asd0912** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/25403432/22397243/7c39baea-e53b-11e6-9f06-b1000b5a6a74.png)

Did something a bit more punchy.

**Comment by MarcinWieczorek** [comment]
A star inside an envelope might be a nice idea. I have poor imagination and no design skills unfortunately. I can only give opinions ;)

**Comment by ajmos** [comment]
Fresh iteration for your consideration

![screenshot from 2017-01-30 21 44 53](https://cloud.githubusercontent.com/assets/25403432/22450549/68ba2f6c-e735-11e6-9896-ad99e643029e.png)

**Comment by elioqoshi** [comment]
I like the 2nd "classy" proposal by @ajmos as well.

What are the next steps on deciding for the logo? Don't forget that you need to have a wordmark too

**Comment by jancborchardt** [comment]
@elioqoshi the logo is good in general, but there are a lot of lines and different shapes going on (squares, triangles, the strange astroid shape). Maybe simplify that somehow.

Also, I wouldn’t make a negative version of it as a favicon, as it looks very different to the normal one. Why not just the normal logo with transparent background? Having it in a container with its own form makes it look even more complicated, and smaller.

**Comment by gauteh** [comment]
@elioqoshi maybe it'd look better with a quadratic envelope so that the triangles will be equal on all edges?

**Comment by elioqoshi** [comment]
![3](https://cloud.githubusercontent.com/assets/5436686/22486815/564bc1e8-e80b-11e6-9b46-7888cf51967c.jpg)

@gauteh This with a quadratic envelope/

@jancborchardt I agree, but that's rather hard to do while still keeping this exact star shape intact. Depends if we want to break out of it

**Comment by mardukbp** [comment]
Here's a variation of elioqoshi's logo.

![astroid5](https://cloud.githubusercontent.com/assets/1140106/22488777/40d503b6-e814-11e6-8706-720a237184c6.png)

**Comment by ajmos** [comment]
Why is this logo so hard

![screenshot from 2017-01-31 21 19 44](https://cloud.githubusercontent.com/assets/25403432/22493018/07ade3dc-e7fb-11e6-99c5-45f2ccddb364.png)

**Comment by elioqoshi** [comment]
Will we have a decision soon? :)

**Comment by gauteh** [comment]
Sorry for the delay, I am super-busy this week. If the other
contributors here would cast their vote on the contributions they think
should be chosen I will take that into account. We might have to do
some final polishing, but we can figure that out afterwards. The logo
used must be licensed under GPL3+ like the rest of Astroid.

**Comment by hugoroy** [comment]
fwiw, my favourite so far is https://github.com/astroidmail/astroid/issues/254#issuecomment-275843335

**Comment by mxmehl** [comment]
From the shape, I like #254 the most so far, but I have two concerns:
1. No idea how to do the favicon while taking the comments of @jancborchardt into account.
2. Colour-wise it doesn't really strike me, mainly because the two colours are to similar to each other IMO. Is there a possibility to increase the contrast a bit, like with the python colours? :P

**Comment by ajmos** [comment]
Am I allowed to comment if I designed a logo myself?
I like the concise design that @elioqoshi made, but the bulk of the logo is still a commonly-used envelope pictogram that in all likelihood will not excel at being a unique identifier in the software world.
I also think that colourlind people will have a tough time differentiating the blues, but I'm no expert.

**Comment by elioqoshi** [comment]
The color concerns are valid. I'd be happy to adjust them, but I thought the purple one was the color Astroid used to have :)

**Comment by jancborchardt** [comment]
@mxmehl the favicon can just be exactly the same as the logo. :) No color inversion or containing shape needed.

**Comment by gauteh** [comment]
Hi, 

first: thanks for all the contributions and variations, I appreciate all the effort that has gone into this.

I think that set of logos created by @elioqoshi in https://github.com/astroidmail/astroid/issues/254#issuecomment-275843335 are the best fit, and we will go for that!

As for final polishing:
It might be that the round-background astroid is the best general icon since the different size of the triangles might be less confusing there.

Thanks again. Gaute

![a7da804c-e556-11e6-9402-a2587e4a93d9](https://cloud.githubusercontent.com/assets/56827/23212168/c27f2e3a-f905-11e6-9425-a9a7908d4390.jpg)

**Comment by MarcinWieczorek** [comment]
Is it official already?
@gauteh I can handle a patch for AUR if you want.

**Comment by gauteh** [comment]
Yes. Always great with contributions! But I'm not sure I understand what you mean :)

**Comment by MarcinWieczorek** [comment]
Oh the desktop entry is in the upstream. I forgot you're the maintainer in AUR. We usually provide a desktop entry in the package.

**Comment by elioqoshi** [comment]
In my humble opinion, I'd suggest going without the circle background for the reasons @jancborchardt stated. To accommodate this, I tweaked the shape a bit, so it looks more uniform now without making the envelope look weird. I also changed the colors to something which might suit here.

What do you think?

![astroid](https://cloud.githubusercontent.com/assets/5436686/23262001/5e79bb56-f9d9-11e6-9f14-7a24f3850e12.jpg)

**Comment by gauteh** [comment]
@MarcinWieczorek: Ok, it's not really installed anywhere sensible so it'd be good with a patch for that (and the icon once it is included upstream).

**Comment by MarcinWieczorek** [comment]
The desktop entry should be as it is, no worries

**Comment by gauteh** [comment]
@elioqoshi: Yeah, I like that version better. Not sure 100% sure about the colors, but I am not sure :)

**Comment by hugoroy** [comment]
I like the yellow of the envelope, old-school feeling. I felt the previous font had more character though.

**Comment by elioqoshi** [comment]
Thanks! I accidentally changed the font, will switch back to it

**Comment by gauteh** [comment]
Ok, let's go for the yellow colors with the original font. We need .svg and .png versions with and without the text, could you please create those? As I said originally, the contributions should be made under the GPLv3+ license. The font is probably already licensed in some other way?

**Comment by MarcinWieczorek** [comment]
GPL for such artworks? Why not use a CC license?

**Comment by hugoroy** [comment]
Best case:

Please release under both licenses, that way we may include it in astroid without adding a new license (so please use any of the already-used licenses, such as GPLv3+); and for those who only need to use the icon without using the program (e.g. to display the icon in an article talking about Astroid) these people may do so with a more lightweight license (e.g. CC-BY).

@gauteh: unless we include the font itself I don't think the font license would apply. Now, @elioqoshi needs to make sure he has the rights to use the font to make this logo :-)

**Comment by elioqoshi** [comment]
@hugoroy the font is licensed under an Open Font License, so that should be okay. I only use Open Fonts, not proprietary ones. Exporting now as we speak.

**Comment by elioqoshi** [comment]
The font is Exo 2, licensed under a SIL Open Font License:
https://www.fontsquirrel.com/fonts/exo-2

http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

**Comment by elioqoshi** [comment]
Here we go:
https://cloud.ura.design/s/hjpt6lgyPMvW9fK

As a sidenote: I'd appreciate if you can support and share with your connections our Patreon, which allows us to help FLOSS projects with design :)

https://patreon.com/ura

**Comment by hugoroy** [comment]
↪ Elio Qoshi / mars 1, 2017 19:40:
> As a sidenote: I'd appreciate if you can support and share with your connections our Patreon, which allows us to help FLOSS projects with design :)
> 
> https://patreon.com/ura

Good idea! :-)

**Comment by gauteh** [comment]
Elio Qoshi writes on mars 1, 2017 19:40:
> Here we go:
> https://cloud.ura.design/s/hjpt6lgyPMvW9fK

thanks! I think .svg versions of the icons are missing?

**Comment by elioqoshi** [comment]
Sorry, you are right. Here it's fixed:
https://cloud.ura.design/s/9sqWp0f5falRtsU

**Comment by gauteh** [comment]
Elio Qoshi writes on mars 2, 2017 10:20:
> Sorry, you are right. Here it's fixed:
> https://cloud.ura.design/s/9sqWp0f5falRtsU

Thanks! These have now been added to the repository. I've noted the
patreon url in History which will go into the release notes for the next
release.

**Comment by gauteh** [comment]
Thanks again to all contributions and suggestions!

**Comment by hugoroy** [comment]
@elioqoshi Could you create a text file called LICENSE in https://github.com/astroidmail/astroid/new/master/ui/icons with the following text?

    Astroid logos by Elio Qoshi <email/username/whateveryouwant> - 2017

    This work is licensed as part of the Astroid project. You can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version, or (at your option) under the Creative Commons Attribution 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

Thanks!

**Comment by elioqoshi** [comment]
Just did :)
https://github.com/astroidmail/astroid/pull/304

**Comment by gauteh** [comment]
Elio Qoshi writes on mars 5, 2017 16:18:
> Just did :)
> https://github.com/astroidmail/astroid/pull/304

Thanks, merged!

**Comment by comradekingu** [comment]
To illustrate an interesting idea

![astero](https://user-images.githubusercontent.com/13802408/27854823-7a4ef32c-6168-11e7-9703-51974fdd56d5.png)

**Comment by gauteh** [comment]
Allan Nordhøy writes on juli 5, 2017 9:58:
> To illustrate an interesting idea

Nice :) Looks like a stone-age version.

**Comment by Erioldoesdesign** [comment]
Hey there! can we close the associated open source design issue: https://opensourcedesign.net/jobs/jobs/2017-01-25-Logo%20design%20for%20the%20Astroid%20Mail%20User%20Agent

(If we don't get a reply in 2 weeks we'll close anyways :) )

**Comment by gauteh** [comment]
Yes 👍

man. 21. jun. 2021, 21:59 skrev Eriol Fox ***@***.***>:
