### ISSUE TITLE
Conflict when adding attachment

### ISSUE THREAD

**Issue by mardukbp** [astroidmail/astroid#257]
Using S as the mnemonic for Select conflicts with `Alt+S`, the default shortcut for the [search-shortcut](https://developer.gnome.org/gtk3/stable/GtkFileChooserWidget.html#GtkFileChooserWidget-search-shortcut) signal.

I would suggest using `_Attach` in order to avoid this conflict.

EDIT: I think a mnemonic is not necessary for the button that closes the dialog. Pressing Return has the same effect.

**Comment by gauteh** [comment]
Pressing return adds the attachment (or selects the file), while Escape closes the dialog without adding. Do you still think we need to change the text of Select?

**Comment by mardukbp** [comment]
Yes. Changing it to "Select" allows using `Alt+S` for quickly finding the file you want to attach.

**Comment by gauteh** [comment]
It is already "Select", what do you want it to be updated to?

**Comment by mardukbp** [comment]
I checked yesterday and it is "_Select", which makes `S` the mnemonic for "clicking" the button with `Alt+S`.

**Comment by gauteh** [comment]
Yes - and what do you want to change?

**Comment by mardukbp** [comment]
I want "Select" instead of "_Select".

**Comment by gauteh** [comment]
On my GTK+ I can just start typing and it will filter the files.

**Comment by mardukbp** [comment]
Yes, but it only matches the first characters of the filename. `Alt+S` matches anywhere in the filename and allows filtering the directory to only show files with a given extension. It is very handy.

**Comment by gauteh** [comment]
Not here..: 
![2017-01-03-104028_2560x1600_scrot](https://cloud.githubusercontent.com/assets/56827/21603999/1d5db66e-d1a1-11e6-9f8b-fb77da6caf9a.png)

**Comment by mardukbp** [comment]
Maybe that is new behaviour in the latest Gtk. Keep in mind that not everybody is using the bleeding edge.

**Comment by gauteh** [comment]
That may be, in that case it is good to figure out if that is really the issue. I think it is better to change the text to _Attach. Does that work for you?

**Comment by mardukbp** [comment]
Yes. Thanks!
