### ISSUE TITLE
Reply-To causes buggy replies-to-all

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#261]
It seems replying to mails containing the Reply-To header causes some strange behaviour of astroid. I couldn't exactly reproduce it with my own tests but they caused another (edge-case) flaw:

Header 1 (shortened):
```
To: xxyyzz@q.fsfe.org
From: ****** <****@fsfe.org>
Reply-To: xxyyzz@q.fsfe.org
In-Reply-To: <1483715512.******.max.****@fsfe.org>
Precedence: bulk
X-ML-Address: xxyyzz@q.fsfe.org
```

Pressing Reply-all (my default on mailing lists) causes astroid to use `xxyyzz@q.fsfe.org` *twice* as recipient of the new mail. Simple Reply work correctly, using the xxyyzz address.

Header 2 (shortened):
```
From: Max Mehl <****@mehl.mx>
Reply-To: "max.****@fsfe.org" <max.****@fsfe.org>
To: "max.****@fsfe.org" <max.****@fsfe.org>
```

Reply-all causes astroid to use no recipient at all. Simple reply again works as expected.

**Comment by gauteh** [comment]
Uh, oh, yeah. That doesn't look right...

**Comment by gauteh** [comment]
Please try #281
