### ISSUE TITLE
Translate tags

### ISSUE THREAD

**Issue by hgvhgv** [astroidmail/astroid#262]
Are there any plans to implement the tag translation mentioned in #38, along the lines of the example given before? It would be great!

> ```
> "astroid": {
>   "tags": {
>     "translate" : {
>       "signed" : "",
>       "encrypted" : "E",
>     },
>   },
> },
> ...
> ```

**Comment by gauteh** [comment]
I haven't any immediate plans, but it is not too difficult to implement. If we are going to translate tags reversely when editing tags it will not be possible to assign the alias as a tag. This might not be a big issue though. What do you think?

**Comment by hgvhgv** [comment]
In my case, that's a feature rather than a limitation, as I like have short tags that are easy to remember/unique, that are then mapped to aliases that show the larger "grouping" that tag lives under (e.g., the tag "dk" is assigned to the aliases "who/org/dk" next to lots of other "who/org/*" aliases). So sounds great to me!

**Comment by gauteh** [comment]
hgvhgv writes on januar 20, 2017 12:42:
> In my case, that's a feature rather than a limitation, as I like have short tags that are easy to remember/unique, that are then mapped to aliases that show the larger "grouping" that tag lives under (e.g., the tag "dk" is assigned to the aliases "who/org/dk" next to lots of other "who/org/*" aliases). So sounds great to me!

Right, so you still want the tag to be displayed as 'who/org/dk' in the
thread-index and thread-view, but you want to be able to assign a
thread/message the 'dk' tag which aliases to 'who/org/dk'. I assumed you
wanted it to be the other way, so that a short alias can be assigned for
long tags.

We might need to have different groups of aliases, one general that
works for all context both ways. And one that works only on editing, and
one that work only on showing.

```
"astroid": {
  "tags": {
    "translate" : 
      "uniform" : {
        "signed" : "",
        "encrypted" : "E",
      },

      "edit" : {
        "who/org/dk" : "dk",
       },

      "view" : {
        "encrypted" : "E",
      }

  },
},
```

**Comment by hgvhgv** [comment]
Something that comprehensive seems ideal, as it would cover (apparently?) all use cases!

**Comment by gauteh** [comment]
You can use #336 to set up custom tag to icon maps.

**Comment by hgvhgv** [comment]
Wow, just saw this, thanks!

**Comment by gauteh** [comment]
Actually I don't think I merged the translate tag part yet - there were some discussions about where to place things!

**Comment by matclab** [comment]
What is the status of this ? 
I'd love to be able to translate some tags into smaller icons.

**Comment by gauteh** [comment]
@matclab: we never got around to making a decision in #336 where custom icons and translations could be defined. I don't know if the PR can still be merged as it is, but you could try!
