### ISSUE TITLE
Add a page with build dependencies for fedora

### ISSUE THREAD

**Issue by koolfy** [astroidmail/astroid#264]
I've recently had to compile astroid on a fedora system, and I noticed there weren't any list of build deps to install for fedora.

Here is my current list for a fedora24:
`scons notmuch-devel boost-devel glibmm24-devel webkitgtk-devel webkitgtk3-devel libsass-devel gmime-devel gtkmm30-devel gobject-introspection-devel libpeas-devel gcc-c++`

I'll confirm tomorrow against a brand new fedora 24 vanilla that this list is sufficient to build astroid :)

**Comment by gauteh** [comment]
Great, please feel free to update the wiki.

koolfy writes on januar 12, 2017 0:27:

**Comment by koolfy** [comment]
Updated the wiki, closing this issue ;)

**Comment by gauteh** [comment]
thanks !

koolfy writes on januar 12, 2017 12:46:
