### ISSUE TITLE
Possible to refresh all thead indices at once?

### ISSUE THREAD

**Issue by vodik** [astroidmail/astroid#265]
Trying to make sense of the documentation/source, is there a version of `thread_index.refresh` function that refreshes everything at once?

**Comment by gauteh** [comment]
The refresh keybinding reloads the entire query and all the entries in
the thread-index. 

Normally you would never need to use this key binding. The only time
something isn't updated automatically is when you update the notmuch
database outside of astroid. 

Note that anything that happens in the poll script is updated
automatically.

**Comment by gauteh** [comment]
Closing, need more information.
