### ISSUE TITLE
Boost update breaks build

### ISSUE THREAD

**Issue by hughwilliams94** [astroidmail/astroid#266]
When using the AUR package the install no longer works after the 1.63 boost and boost-libs update. Initial workaround is to downgrade the packages in the meantime.

**Comment by gauteh** [comment]
Please post the error message

**Comment by gauteh** [comment]
I am not able to reproduce this bug, perhaps astroid just needed an rebuild after the upgrade?

**Comment by hughwilliams94** [comment]
Perhaps yes, should the AUR package do this automatically or should I do
this manually?

**Comment by gauteh** [comment]
You have to do this manually. There are probably some scripts out there to figure out which AUR packages need to be rebuilt.

**Comment by gauteh** [comment]
I mean, you don't need to do anything with the AUR package. Just re-install it like you did the first time.

**Comment by hughwilliams94** [comment]
I am away from my computer but will do this when I get back.

**Comment by hughwilliams94** [comment]
Thanks everything works fine now!

**Comment by gauteh** [comment]
Great!

Hugh Williams writes on januar 18, 2017 22:21:
