### ISSUE TITLE
strange missing attachment warning

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#267]
the warning to attach a file when the word "attach" was found in the mail and no file was attached is given even if that word is in a quoted sentence.

furthermore it even says "you have mentioned ...". maybe a more abstract wording would do for now like "astroid found the word attach in the mail while no file was attached" or the like.

**Comment by gauteh** [comment]
Hi,

Yeah - I can see that it is a bit weird in this case. Optimally quoted
'attach' words wouldn't count, but for now I don't think I will
prioritize fixing that. 

I like the personal, maybe friendly, tone of how it is now. It just seems a bit
more cumbersome and distant with something like 'astroid found..'? Even
if it slightly more accurate in some situations. what do you think?

**Comment by mxmehl** [comment]
+1 for adding exceptions of quoted occurences of the attachment words.

Regarding the text I don't have a strong opinion. Maybe a compromise could be "astroid found/noticed your message contains ..."?

**Comment by emdete** [comment]
i consider this a ki against moderate algorithm problem 😉 just removing "you mention" is needed as astroid doesnt know. i would not pimp the algorithm to enhance detection because it always wont be sufficient.
