### ISSUE TITLE
No Error Raised When Specified Config file Not Found

### ISSUE THREAD

**Issue by jackdesert** [astroidmail/astroid#270]
I specified the config file 

    astroid -c <file>

but the specified file did not exist. Astroid opened using the default config file instead. 

I was confused for a while, thinking astroid must not support specifying a config file. 

Least surprising (better, in my opinion) would be if it raised an error that the specified config file was not found.

**Comment by emdete** [comment]
this is a feature: if the file does not exist it will be created with defaults and serves as a template for personal changes.

**Comment by gauteh** [comment]
I think this is a bug, if `-c` and not `-n` is specified, astroid should fail rather than creating a new config. If neither `-c` nor `-n` is specified it should work as it currently does.

**Comment by gauteh** [comment]
I'm going to close this as a feature for now.
