### ISSUE TITLE
Tag multiple workflow

### ISSUE THREAD

**Issue by jackdesert** [astroidmail/astroid#271]
Steps to recreate:

1. From the thread index, press "t" a few times to mark multiple threads which checkmarks
2. press "+" to add a tag
3. type an additional tag into the box
4. Press "ENTER" to save changes

The result is that the new tag only gets added to the highlighted thread, not for all the threads that were marked.

Using v0.7 on Ubuntu 16.04

**Comment by hugoroy** [comment]
It seems that this is not the current flow for tagging multiple emails. See: https://github.com/astroidmail/astroid/wiki/Tagging-multiple-threads

I am wondering if maybe this could be improved.

**Comment by jackdesert** [comment]
I am confused. I assume the screenshot that you referenced is out of date, since when I press "T", then "+", there is no plus sign in my tags bar. 

Also, it says to press  the ell key, but pressing the ell key simply enters the letter ell in the tags bar. 

Am I missing something? Tagging multiple does not work for me.

**Comment by gauteh** [comment]
You have to press: `t` to mark one or more threads, then `;` to open the multiple actions thing, then choose `+` to tag (or any other action). The wiki is outdated, if someone finds the time, please update!

**Comment by gauteh** [comment]
I think one possible improvement is to make actions work on all marked threads when they are marked, otherwise work on the currently selected thread.
