### ISSUE TITLE
Inline PGP / GPG

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#289]
This is a bad idea, but there is still a lot of clients sending this around. We will never support sending inline PGP, but might support parsing in some cases.

Resources:
* https://mail.gnome.org/archives/gmime-devel-list/2014-October/msg00003.html
* #288

**Comment by hugoroy** [comment]
I think that's the right approach! Accept everything and be strict in what you send ;-)

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 0:13:
> I think that's the right approach! Accept everything and be strict in what you send ;-)

Yes, the problem is that parsing all the different formats of inline pgp
is royal pain in the neck. It will require a lot of effort to get it
right unfortunately.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 2, 2017 8:56:
> Hugo Roy writes on mars 2, 2017 0:13:
>> I think that's the right approach! Accept everything and be strict in what you send ;-)
> 
> Yes, the problem is that parsing all the different formats of inline pgp
> is royal pain in the neck. It will require a lot of effort to get it
> right unfortunately.

It could be interesting to see how Mailpile does it. They probably have
run into many GPG issues recently.

**Comment by gauteh** [comment]
Good news! GMime gets inline PGP in version 3.0:

* https://mail.gnome.org/archives/gmime-devel-list/2017-March/msg00003.html
* https://mail.gnome.org/archives/gmime-devel-list/2017-March/msg00000.html

**Comment by gauteh** [comment]
I'm going to close this. Too low priority.

**Comment by mxmehl** [comment]
Hm, that's sad. I still get many inline-gpg signed messages and they are a real PITA to read. Encrypted messages are rarer fortunately.

**Comment by gauteh** [comment]
Max writes on september 21, 2017 15:18:
> Hm, that's sad. I still get many inline-gpg signed messages and they are a real PITA to read. Encrypted messages are rarer fortunately.
> 

Maybe the new decrypt_message code can handle it more easily. Shouldn't 
be too hard to write a small test case to see.

**Comment by gauteh** [comment]
Note to self: If we support this, makes sure to handle inlined PGP (separate iframe?) as safely as regular PGP/MIME w.r.t. #499.
