### ISSUE TITLE
Open thread in pane bugs

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#290]
Some people are really interested in having the thread pane-view, i.e. viewing threads in a pane above the index-view, rather than opening a new tab for threads.

Right now, astroid has the feature, but it used to be buggy.

The first problem I see: I don't see how to close the pane. All I can do is close the tab that contains the pane.

Should we try to fix that or should we just abandon this feature and go tab-only?

**Comment by gauteh** [comment]
Hugo Roy writes on februar 25, 2017 19:37:
> Some people are really interested in having the thread pane-view, i.e. viewing threads in a pane above the index-view, rather than opening a new tab for threads.
> 
> Right now, astroid has the feature, but it used to be buggy.
> 
> The first problem I see: I don't see how to close the pane. All I can do is close the tab that contains the pane.
> 
> Should we try to fix that or should we just abandon this feature and go tab-only?

I have recently worked a little bit on this one again (#280, #251), I
think it will become more relevant with the message-view (#269, #100),
especially in tree-view mode. The close pane key should currently be
'x', probably a left over from before, which should be changed to 'C-w'
now so that it is closed before closing the tab.

The key for swapping focus is 'M-space'.

- gaute

**Comment by hugoroy** [comment]
↪ Gaute Hope / février 25, 2017 22:35:
> I have recently worked a little bit on this one again (#280, #251), I
> think it will become more relevant with the message-view (#269, #100),
> especially in tree-view mode. The close pane key should currently be
> 'x', probably a left over from before, which should be changed to 'C-w'
> now so that it is closed before closing the tab.

I realised afterwards browsing the issues that some work was done there!
That’s good.

I agree that C-w would be more coherent with the rest.

> The key for swapping focus is 'M-space'.

This key triggers some Gnome dialog for me (see attached).

**Comment by hugoroy** [comment]
> This key triggers some Gnome dialog for me (see attached).

(OK i suppose now this is simply because I wasn't using astroid compiled from the right branch!)

**Comment by gauteh** [comment]
Hugo Roy writes on februar 25, 2017 22:57:
> ↪ Gaute Hope / février 25, 2017 22:35:
>> The key for swapping focus is 'M-space'.
> 
> This key triggers some Gnome dialog for me (see attached).

That is some window-manager keybinding that catches the key before
astroid gets it. Suggestions for other keybindings?

**Comment by gauteh** [comment]
Hugo Roy writes on februar 25, 2017 23:00:
>> This key triggers some Gnome dialog for me (see attached).
> 
> (OK i suppose now this is simply because I wasn't using astroid compiled from the right branch!)
> 

It should all have been merged into 'master' a while ago.

**Comment by gauteh** [comment]
Are there any bugs left here now? Otherwise I think this bug should be
closed, and you can open a bug if you run into anything specific.

**Comment by hugoroy** [comment]
↪ Gaute Hope / février 25, 2017 23:01:
> Hugo Roy writes on februar 25, 2017 22:57:
>> ↪ Gaute Hope / février 25, 2017 22:35:
>>> The key for swapping focus is 'M-space'.
>> 
>> This key triggers some Gnome dialog for me (see attached).
> 
> That is some window-manager keybinding that catches the key before
> astroid gets it. Suggestions for other keybindings?

Maybe C-Tab?

**Comment by hugoroy** [comment]
↪ Gaute Hope / février 26, 2017 17:18:
> Are there any bugs left here now? Otherwise I think this bug should be
> closed, and you can open a bug if you run into anything specific.

Well, it's just that the focus still feels weird when I try it :)

**Comment by gauteh** [comment]
C-tab also doesnt work. Weird?

**Comment by hugoroy** [comment]
I don't know. I guess I find astroid's tab approch so much better that I don't even remember how mutt felt like with the pane view :-)

Anyway, I assume that people who want the pane view would need some way to easily jump from one thread to the next without having to move focus all the time between the pane and the thread list. But at this point I'm out of ideas.

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 0:12:
> I don't know. I guess I find astroid's tab approch so much better that I don't even remember how mutt felt like with the pane view :-)
> 
> Anyway, I assume that people who want the pane view would need some way to easily jump from one thread to the next without having to move focus all the time between the pane and the thread list. But at this point I'm out of ideas. 
> 

Right, that makes sense. Will probably use similar mechanisms as for
#91. Will close this one for now.
