### ISSUE TITLE
Add Reply-to-list option

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#294]
Many MUAs have the ability to make a reply-to-list. Currently, when replying to a message on a mailing list (I've tested Mailman), astroid replies to the list **and** the sender of the mail I reply to.

Many people don't like this behaviour. So I'd like to ask for adding a reply-to-list alongside the already existing simple reply and reply-to-all, including a configurable shortcut of course. 

I guess, astroid should respect the `List-*` headers therefore, like `List-Post: <mailto:abc@lists.fsfe.org>`. 

Details:
- If such headers do not exist, and the user uses reply-to-list anyway, reply-to-all should be chosen instead.
- Other `To` and `Cc` values should still be respected. Only the sender should be left out (I guess this is the logic other MUAs use).

**Comment by kirschner** [comment]
I'd like to second this. List-reply is really one of the most crucial features for me as it is considered impolite on many mailing lists if you additionally include the sender. 

Thank you for considering it!

**Comment by hugoroy** [comment]
I think there are two things here:

1. Ensure that the "Astroid Reply-To Suggestions" work correctly. See the bottom right-hand corner screenshot which has a drop-down list of available Astroid Reply-To Suggestions: https://raw.githubusercontent.com/astroidmail/astroid/master/doc/full-demo-external.png 


    However in my experience, I often have to manually make custom edits to the Reply-To. I find that sometimes the Astroid Reply-To Suggestions do not work as expected. Am I the only one? Should I file a separate issue for these?


2. Provide some keybindings when replying on an email which will select the desired Astroid Reply-To Suggestion. For instance, here are some suggestions of keybindings from the top of my head which would need to be checked:

    - "r" should follow the "Reply-to:" field given by the email responding to; 
    - "g" should override the "Reply-to:" field and select the group of all participants in the email instead; 
    - "L" should override the "Reply-to:" field and select the "List-*" field, 
    - "R" should override the "Reply-to:" field and select the sender only instead;
    - "c" should be like "R" but in a new thread.

I think these above already exist but maybe ensuring that this is consistent and coherent could be good. I will try to make a list of what the current default keybindings for these are, if they exist.

**Comment by gauteh** [comment]
`r`, `g` already works as you describe. `c` composes a new e-mail to the sender, like you describe but not to reply-to.

**Comment by gauteh** [comment]
Check out #297. There's also a config option for not including the sender in to (by default included).

**Comment by gauteh** [comment]
Closed in #297

**Comment by hugoroy** [comment]
@gauteh : however "Mailing List" is missing in the drop-down Astroid Reply-To Suggestions:
![capture d ecran de 2017-03-02 21-00-40](https://cloud.githubusercontent.com/assets/1629771/23524590/91461bb2-ff8b-11e6-87de-39e2de63140a.png)

**Comment by gauteh** [comment]
It's only there if there's a mailing list :)

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 2, 2017 21:06:
> It's only there if there's a mailing list :)

Well, I tested on one with a mailing list in it :-)

But you're right. I checked and here's what happened:

The person emailed to the list and to me in "To:"

So the actual email source, when I hit "V" shows me that the email got
to me without going through the list.

So for astroid there's no list.

I guess there's no way around that ;)

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 21:33:
> ↪ Gaute Hope / mars 2, 2017 21:06:
>> It's only there if there's a mailing list :)
> 
> Well, I tested on one with a mailing list in it :-)
> 
> But you're right. I checked and here's what happened:
> 
> The person emailed to the list and to me in "To:"
> 
> So the actual email source, when I hit "V" shows me that the email got
> to me without going through the list.
> 
> So for astroid there's no list.
> 
> I guess there's no way around that ;)

Hm, no :) but 'M' should fallback to reply-all which should work in this
case I think.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 2, 2017 22:23:
> Hm, no :) but 'M' should fallback to reply-all which should work in this
> case I think.

Yes, perfect!

I will try to test around more to see if the Reply-to suggestions always
work as expected.

**Comment by kirschner** [comment]
It seems to me this is not working correctly. I list-replied to several messages which were just send to the mailing list, but the message would be send to the mailing list, plus the sender of the original message.

In the New Message window I see "Reply to: Mailinglist", but is is never different than "all". Doing a list reply to the same messages with another MUA creates a reply just to the mailinglist in "to".

**Comment by kirschner** [comment]
And I did not yet read https://github.com/astroidmail/astroid/pull/297 to figure out that I have to change the config option. Sorry. Just tested a few of the the messages I tried before, and it works as expected now. 

I was wondering if `"mailinglist_reply_to_sender": "false"`should not be the default for the feature.

**Comment by gauteh** [comment]
Matthias Kirschner writes on april 21, 2017 19:30:
> And I did not yet read https://github.com/astroidmail/astroid/pull/297 to figure out that I have to change the config option. Sorry. Just tested a few of the the messages I tried before, and it works as expected now. 
> 
> I was wondering if `"mailinglist_reply_to_sender": "false"`should not be the default for the feature.
> 

Yeah, I'm necessarily opposed to that. I prefer it 'true' myself though.
I was just thinking, we should start to document all the configuration
options on a wiki page. In a similar way as it exists for Mutt. It is
pretty hard to figure out these things unless there is a general place
to look for it. The docs could then link to relevant places in the Tour.

**Comment by kirschner** [comment]
* Gaute Hope [2017-04-21 21:20 +0200]:
 
> Yeah, I'm necessarily opposed to that. I prefer it 'true' myself though.
> I was just thinking, we should start to document all the configuration
> options on a wiki page. In a similar way as it exists for Mutt. It is
> pretty hard to figure out these things unless there is a general place
> to look for it. The docs could then link to relevant places in the Tour.

That sounds good. I went through the config file several times, but I
missed this option before, and did not remember it when dealing with
this behaviour. 

What is the way forward with that? Would we start manually writing
things down and separated chapters by the sections in the config? 

Would it also be an option to add comments in the config file itself? It
is not as accessible as the other option, but on the other hand in the
long run we would not forget to document chapters in the config file. 

What do you prefer?

**Comment by hugoroy** [comment]
Ideally, the config file should be exposed through a web page directly
in Astroid, similarly to what Chrome or Firefox do these days.

**Comment by gauteh** [comment]
Hugo Roy writes on april 22, 2017 16:36:
> Ideally, the config file should be exposed through a web page directly
> in Astroid, similarly to what Chrome or Firefox do these days.

Yes, but this requires the config to be reloaded without re-starting
astroid, not impossible, but needs a bit of work.

What I would like first is default/user-set state configuration
variables, meaning: either the configuration option is default or it is
set by the user. So that if we change the default upstream, it will
propagate to all users who have not set the config explicitly.

**Comment by hugoroy** [comment]
↪ Gaute Hope / avril 23, 2017 11:44:
> What I would like first is default/user-set state configuration
> variables, meaning: either the configuration option is default or it is
> set by the user. So that if we change the default upstream, it will
> propagate to all users who have not set the config explicitly.

I agree that, ideally, changes should apply immediately without the need
to resetart Astroid.

However, it does not seem like a hard requirement to me and does not
have to be blocking if somebody wants to start working on a web
interface that can read/write the config file(s).

I could imagine a “Save” button with a message appearing when you click it, saying:

    “Your new config has been saved. Changes will apply after you restart Astroid”

Of course, this would only be temporary until changes may apply
immediately when the config file is modified.

Best,
Hugo

**Comment by gauteh** [comment]
Hugo Roy writes on april 23, 2017 13:04:
> ↪ Gaute Hope / avril 23, 2017 11:44:
>> What I would like first is default/user-set state configuration
>> variables, meaning: either the configuration option is default or it is
>> set by the user. So that if we change the default upstream, it will
>> propagate to all users who have not set the config explicitly.
> 
> I agree that, ideally, changes should apply immediately without the need
> to resetart Astroid.
> 
> However, it does not seem like a hard requirement to me and does not
> have to be blocking if somebody wants to start working on a web
> interface that can read/write the config file(s).
> 
> I could imagine a “Save” button with a message appearing when you click it, saying:
> 
>     “Your new config has been saved. Changes will apply after you restart Astroid”
> 
> Of course, this would only be temporary until changes may apply
> immediately when the config file is modified.

Yep! Good plan!

**Comment by gauteh** [comment]
Matthias Kirschner writes on april 22, 2017 6:59:
> * Gaute Hope [2017-04-21 21:20 +0200]:
>  
>> Yeah, I'm necessarily opposed to that. I prefer it 'true' myself though.
>> I was just thinking, we should start to document all the configuration
>> options on a wiki page. In a similar way as it exists for Mutt. It is
>> pretty hard to figure out these things unless there is a general place
>> to look for it. The docs could then link to relevant places in the Tour.
> 
> That sounds good. I went through the config file several times, but I
> missed this option before, and did not remember it when dealing with
> this behaviour. 
> 
> What is the way forward with that? Would we start manually writing
> things down and separated chapters by the sections in the config? 
> 
> Would it also be an option to add comments in the config file itself? It
> is not as accessible as the other option, but on the other hand in the
> long run we would not forget to document chapters in the config file. 
> 
> What do you prefer? 
> 

Matthias,

I think the best is to create one reference page with all the
configuration options. This should be done manually, there is a full
list of config options in `src/config.cc`. 

These should be organized according to section, we might think about
splitting the page on section at a later time. The rest of the Tour and
various examples in the wiki should then link to the config-option in
the reference. There should also be links from the config-option to
useful places it is referred to in the Tour or the wiki-elsewhere, so
that it is easy to find examples and we do not need to duplicate
information.

Any comments?

Regards, Gaute

**Comment by gauteh** [comment]
I created a separate issue in #328, please continue discussion there.
