### ISSUE TITLE
Improve right-click actions in ThreadView

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#296]
In ThreadView it would be nice to copy an email address via mouse right click. Currently, it's just possible to copy it like `mailto:john@example.com`. Instead, having it like `john@example.com` in the clipboard would be better for most usage scenarios.

Additionally, it may also be nice to be able to copy the name alongside the email address, like `John Doe <john@example.com>`.

Plus, it seems that the right-click actions don't make much sense in ThreadView generally, apart from the "inspect element" action. The reload action causes a blank site and the other ones are greyed out. The context actions in ThreadIndex are much more useful.

**Comment by gauteh** [comment]
Related to #291. Perhaps we can move this issue as an item onto that list?

**Comment by mxmehl** [comment]
Oh yes, makes sense. Could you merge these issues or is this something only @hugoroy can do?

**Comment by gauteh** [comment]
I think we both can, but I think @hugoroy has the better overview :)

**Comment by gauteh** [comment]
Nice :) Let's close this one as it should be covered by #291 now.
