### ISSUE TITLE
Minus does not work as keybinding 

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#299]
I used to be able to add/remove tags using both + and - by having this in the keybindings:

```
thread_view.tag_message=Minus
```

But it hasn't been working for a while.

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 20:52:
> I used to be able to add/remove tags using both + and - by having this in the keybindings:
> 
> ```
> thread_view.tag_message=Minus
> ```
> 

I'm guessing its being converted into a dash which converts it into the
delimiter for the keybindings, maybe we can move the conversion till
after the splitting.

**Comment by gauteh** [comment]
Gaute Hope writes on mars 2, 2017 21:19:
> Hugo Roy writes on mars 2, 2017 20:52:
>> I used to be able to add/remove tags using both + and - by having this in the keybindings:
>>
>> ```
>> thread_view.tag_message=Minus
>> ```

You have to use:

```
thread_view.tag_message=minus
```

**Comment by hugoroy** [comment]
Hi, BTW this does not work any more :-)

**Comment by gauteh** [comment]
Hi, `minus` works for me

**Comment by hugoroy** [comment]
It works in thread view but not thread index for me.

Le 6 août 2017 11:16:05 GMT+02:00, Gaute Hope <notifications@github.com> a écrit :
>Hi, `minus` works for me 

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gauteh** [comment]
Hugo Roy writes on august 6, 2017 11:49:
> It works in thread view but not thread index for me.

That's were I tested.

  thread_index.tag=minus

works for me.

**Comment by hugoroy** [comment]
↪ Gaute Hope / août 6, 2017 11:53:
> Hugo Roy writes on august 6, 2017 11:49:
>> It works in thread view but not thread index for me.
> 
> That's were I tested.
> 
>   thread_index.tag=minus
> 
> works for me.

For some reason I had label instead of tag. Ok that works :)

sorry!
