### ISSUE TITLE
Clean install; blank "new message" window

### ISSUE THREAD

**Issue by jimcheetham** [astroidmail/astroid#307]
I've just installed astroid for the first time, and I've been unable to get a new mail to compose/send - an editor would start up just fine (on the way I had to discover that I needed the Ubuntu package vim-gnome in order to support the --socketid argument, because I'm not using Gnome and the vim-gtk package didn't provide it) but the "New message" tab was blank/black, and there was no way to send the message after editing it.

I also had a symptom where the program would fail at start-up, complaining about a missing icon - I didn't initially get this problem as I was running the executable from the build directory, it only because visible after I tried to install into /usr/local and execute from $HOME

Testing has been complicated because I don't see an easy way to clean the .o files that scons has already compiled, I didn't find any equivalent to "make clean".

```
[14:29:14.103705] [0x00007f80902caac0] [info] re: using installed resource: /usr/local/share/astroid/ui/icons/icon_color.png
[14:29:14.109170] [0x00007f80902caac0] [info] astroid: got query: inbox: tag:inbox
[14:29:14.113834] [0x00007f80902caac0] [error] re: could not find resource: ui/no-mail.png or /usr/local/share/astroid/ui/no-mail.png

```

Turns out the cause was in the install SConstruct failing to copy all the UI files that were needed, and the fix was in PR #305.

I'm just logging this issue to provide a better description of the symptoms than #305 realised.

**Comment by gauteh** [comment]
Hi,

I've just merged #305. You can clean out the compiled objects by doing:

$ scons -c

sometimes scons doesn't detect new dependencies if you have installed
them, then you need to delete the .scons files.
