### ISSUE TITLE
Allow typing/pasting of filename in Attach dialog box

### ISSUE THREAD

**Issue by jimcheetham** [astroidmail/astroid#309]
The Attach operation fires up a dialog box (on my system) that only allows click/select - there doesn't seem to be any way to type or paste a filename directly. I hope that this is just a case of asking the OS/desktop to provide a dialog box with this option :-)

**Comment by gauteh** [comment]
Jim Cheetham writes on mars 20, 2017 5:08:
> The Attach operation fires up a dialog box (on my system) that only allows click/select - there doesn't seem to be any way to type or paste a filename directly. I hope that this is just a case of asking the OS/desktop to provide a dialog box with this option :-) 
> 

Can you get it up by pressing Ctrl+L in the attach dialog?

**Comment by jimcheetham** [comment]
Yes, Ctrl+L does reveal an input area. How did you know that? :-) Can I have this available by default?

**Comment by gauteh** [comment]
It's a Gtk thing :) You can usually get up the text input in vaious places using Ctrl+l. Not sure, maybe there is a Gtk option somewhere? If we have to do it when opening the astroid dialog (API) then we can add a config option for that.
