### ISSUE TITLE
Display variations of tag names

### ISSUE THREAD

**Issue by jimcheetham** [astroidmail/astroid#310]
A feature I like from alot is the ability to change the visual display of a tag name; I use this to replace common names like "inbox" with a single Unicode character. http://alot.readthedocs.io/en/latest/configuration/theming.html#custom-tagstring-formatting

Is this a plugin issue, perhaps? I've been reading old issues but I'm not totally sure at the moment.

Of course, you may run into problems calculating the output width of a string if you start using Unicode a lot.

**Comment by gauteh** [comment]
Jim Cheetham writes on mars 20, 2017 8:05:
> A feature I like from alot is the ability to change the visual display of a tag name; I use this to replace common names like "inbox" with a single Unicode character. http://alot.readthedocs.io/en/latest/configuration/theming.html#custom-tagstring-formatting
>
> Is this a plugin issue, perhaps? I've been reading old issues but I'm not totally sure at the moment.
>
> Of course, you may run into problems calculating the output width of a string if you start using Unicode a lot.
>

You can do this using plugins now, have a look at: https://github.com/astroidmail/astroid-plugin-hls-hsv-tagcolor for how the tags are formatted now. Currently the tags field just have a fixed width available, anything more will be cropped.

Translating tags has been on the table for a while, I would really like
to see this as well, here's the issue: #262. I'd say this is a core
feature, but it could also be implemented in that plugin. We should
probably keep the references you give here in the original issue as well
(#262).
