### ISSUE TITLE
Quote html message as text when replying

### ISSUE THREAD

**Issue by kirschner** [astroidmail/astroid#320]
At the moment I do not find a way in my reply to quote the text from someone who sent me a html e-mail (yes, there are some people out there which do not end up in my spam folder). When I reply with astroid the quote is empty. Is there a way to include only the text from the received html e-mail? 

(In mutt I had a line to change html to text: `text/html;  links -dump %s; nametemplate=%s.html; copiousoutput`.)

**Comment by kirschner** [comment]
Sorry, just saw that https://github.com/astroidmail/astroid/issues/319 was posted yesterday, but I did not get a notification about it before submitting this one.

**Comment by gauteh** [comment]
Closing as duplicated of #319.

**Comment by gauteh** [comment]
Should be fixed now.
