### ISSUE TITLE
Signature handling with different accounts

### ISSUE THREAD

**Issue by kirschner** [astroidmail/astroid#321]
There is a minor inconsistency with the signature handling using several accounts with different settings. When write a new e-mail my default account is used; which is using a signature file.
I then change the from: to my other (private) account; which is not using a signature file (`         "signature_default_on": "false",`)
After this change it still says "signature: on".

It is not a big issue for me, but I think most people would expect that this setting is changing then.

**Comment by gauteh** [comment]
Yeah, I don't think that's how it supposed to work. Is this still an issue?

**Comment by gauteh** [comment]
Re-open if issue persists.
