### ISSUE TITLE
Not being able to use shortcuts "alt+1"... in compose mode

### ISSUE THREAD

**Issue by kirschner** [astroidmail/astroid#322]
When I compose a new message I am not able to use the shortcut "alt + 1" (or other numbers) to switch to other views. When the message was sent and I am in the "New message" tab, the shortcut works again. Is that intended, or is it not possible to use the shortcuts because of the editor (in my case gvim). Thanks!

**Comment by gauteh** [comment]
Matthias Kirschner writes on april 18, 2017 20:38:
> When I compose a new message I am not able to use the shortcut "alt + 1" (or other numbers) to switch to other views. When the message was sent and I am in the "New message" tab, the shortcut works again. Is that intended, or is it not possible to use the shortcuts because of the editor (in my case gvim). Thanks!
> 

This is probably with the default embedded editor? It works better to
navigate the astroid interface if you use an external editor. Ideally,
all keys should be swallowed by the embedded editor, since it is
otherwise really tricky to keep track of focus.

**Comment by kirschner** [comment]
> This is probably with the default embedded editor? It works better to
> navigate the astroid interface if you use an external editor. Ideally,
> all keys should be swallowed by the embedded editor, since it is
> otherwise really tricky to keep track of focus. 

It is with gvim. Here the relevant part. 

    "editor": {
        "cmd": "gvim --servername %2 --socketid %3 -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' %1",
        "external_editor": "false",
        "charset": "utf-8",
        "save_draft_on_force_quit": "true",
        "attachment_words": "attach,anbei,anhang,angehängt",
        "attachment_directory": "~/Downloads/attachments"
    },

So if I want to use the shortcuts, you recommend using gvim as external
editor?

**Comment by gauteh** [comment]
Matthias Kirschner writes on april 20, 2017 15:50:
>> This is probably with the default embedded editor? It works better to
>> navigate the astroid interface if you use an external editor. Ideally,
>> all keys should be swallowed by the embedded editor, since it is
>> otherwise really tricky to keep track of focus. 
> 
> It is with gvim. Here the relevant part. 
> 
>     "editor": {
>         "cmd": "gvim --servername %2 --socketid %3 -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' %1",
>         "external_editor": "false",
>         "charset": "utf-8",
>         "save_draft_on_force_quit": "true",
>         "attachment_words": "attach,anbei,anhang,angehängt",
>         "attachment_directory": "~/Downloads/attachments"
>     },
> 
> So if I want to use the shortcuts, you recommend using gvim as external
> editor? 

Yes, either temporarily close the editor and re-open it afterwards, or
you can also open a new main window and browse around there.  Have a
look here for how to use the external editor:

  https://github.com/astroidmail/astroid/wiki/Customizing-editor#gvim-default

then you should be free to navigate the main window while writing your
email in a different window.

**Comment by kirschner** [comment]
* Gaute Hope [2017-04-20 17:43 +0200]:

> Yes, either temporarily close the editor and re-open it afterwards, or
> you can also open a new main window and browse around there.  Have a
> look here for how to use the external editor:
> 
>   https://github.com/astroidmail/astroid/wiki/Customizing-editor#gvim-default
> 
> then you should be free to navigate the main window while writing your
> email in a different window.

I had a problem before with that. (I have to mention I have not
installed Goyo and Limelight, so I get the error messages about that.)

When I want to write an e-mail, gvim is opened in another window. I type
my mail, but then afterwards astroid behaves strange. There is a "New
message" tab, but I do not see anything there. I have to test if that
has something todo with my window manager. Will report about that.

-- 
Matthias Kirschner - President - Free Software Foundation Europe
Schönhauser Allee 6/7, 10119 Berlin, Germany | t +49-30-27595290
Registered at Amtsgericht Hamburg, VR 17030  |   (fsfe.org/join)
Contact (fsfe.org/about/kirschner)  -  Weblog (k7r.eu/blog.html)

**Comment by gauteh** [comment]
Matthias Kirschner writes on april 21, 2017 9:00:
> * Gaute Hope [2017-04-20 17:43 +0200]:
> 
>> Yes, either temporarily close the editor and re-open it afterwards, or
>> you can also open a new main window and browse around there.  Have a
>> look here for how to use the external editor:
>> 
>>   https://github.com/astroidmail/astroid/wiki/Customizing-editor#gvim-default
>> 
>> then you should be free to navigate the main window while writing your
>> email in a different window.
> 
> I had a problem before with that. (I have to mention I have not
> installed Goyo and Limelight, so I get the error messages about that.)
> 
> When I want to write an e-mail, gvim is opened in another window. I type
> my mail, but then afterwards astroid behaves strange. There is a "New
> message" tab, but I do not see anything there. I have to test if that
> has something todo with my window manager. Will report about that.
> 

You have to set the correct option in the config as well
(external_editor : "false"). You can remove the `-c Goyo` and
limelight parts.

Note that the command is slightly different for external and embedded
editors (there are examples on that wiki page).

**Comment by kirschner** [comment]
> You have to set the correct option in the config as well
> (external_editor : "false"). You can remove the `-c Goyo` and
> limelight parts.

Ok, that was stupid that I forgot to change that part. Sorry for that.

> Note that the command is slightly different for external and embedded
> editors (there are examples on that wiki page).

Yes, I saw that. Now using the external editor and I am very happy with
the improvement.

-- 
Matthias Kirschner - President - Free Software Foundation Europe
Schönhauser Allee 6/7, 10119 Berlin, Germany | t +49-30-27595290
Registered at Amtsgericht Hamburg, VR 17030  |   (fsfe.org/join)
Contact (fsfe.org/about/kirschner)  -  Weblog (k7r.eu/blog.html)

**Comment by gauteh** [comment]
Matthias Kirschner writes on april 21, 2017 13:24:
>> You have to set the correct option in the config as well
>> (external_editor : "false"). You can remove the `-c Goyo` and
>> limelight parts.
> 
> Ok, that was stupid that I forgot to change that part. Sorry for that.
> 
>> Note that the command is slightly different for external and embedded
>> editors (there are examples on that wiki page).
> 
> Yes, I saw that. Now using the external editor and I am very happy with
> the improvement.
> 

Good stuff! I'll close this issue then.

- Gaute
