### ISSUE TITLE
Option to not wait for sendmail to deliver the mail (support for msmtpq)

### ISSUE THREAD

**Issue by rnav** [astroidmail/astroid#326]
It would be good if we can submit the mail for delivery and not have to wait for it. This is especially helpful when working offline, or if the smtp server is down. Analogous to the below mutt setting:
> set sendmail = /path/to/msmtpq
> set sendmail_wait = -1

**Comment by mxmehl** [comment]
I recommend using msmtpqueue for that: https://wiki.archlinux.org/index.php/MSMTP#Using_msmtp_offline

This is especially useful if you're offline, but you could also have a regular cronjob sending all emails in that queue automatically while online. For astroid, a delivery to the queue happens almost instantly so you won't have to wait anymore.

If you mean the waiting counter of by default 2 seconds, you can configure that in astroid's configs.

**Comment by rnav** [comment]
[Apologies for reverting back after all this time]
I have been using msmtpq, but mail delivery is still not instant (compared to mutt). What mutt seems to do is to background the msmtpq process, so email delivery is instant and I am quickly returned back to the thread index. With astroid, delivery to the msmtpq itself sometimes takes a couple of seconds. So, what would be good to have is a similar mode for astroid (perhaps mail:send_delay: -1).

**Comment by gauteh** [comment]
rnav writes on november 15, 2017 11:32:
> [Apologies for reverting back after all this time]
> I have been using msmtpq, but mail delivery is still not instant (compared to mutt). What mutt seems to do is to background the msmtpq process, so email delivery is instant and I am quickly returned back to the thread index. With astroid, delivery to the msmtpq itself sometimes takes a couple of seconds. So, what would be good to have is a similar mode for astroid (perhaps mail:send_delay: -1).

Hi, e-mail delivery is already done in a separate process so that you 
can switch away from the current buffer. How should the UI work for 
this? Should it be:

* Close and hide somewhere?
* You can navigate away, should the messagewindow be closed 
  automatically when the message is sent. In that case you can just 
  forget about it afterwards.
* Should it be closeable; so that it is auto-closed when done, but waits 
  untill it is done before sent.

**Comment by rnav** [comment]
Hi,

Gaute Hope wrote:
> rnav writes on november 15, 2017 11:32:
>> [Apologies for reverting back after all this time]
>> I have been using msmtpq, but mail delivery is still not instant (compared to mutt). What mutt seems to do is to background the msmtpq process, so email delivery is instant and I am quickly returned back to the thread index. With astroid, delivery to the msmtpq itself sometimes takes a couple of seconds. So, what would be good to have is a similar mode for astroid (perhaps mail:send_delay: -1).
> 
> Hi, e-mail delivery is already done in a separate process so that you 
> can switch away from the current buffer. How should the UI work for 
> this? Should it be:
> 
> * Close and hide somewhere?
> * You can navigate away, should the messagewindow be closed 
>   automatically when the message is sent. In that case you can just 
>   forget about it afterwards.
> * Should it be closeable; so that it is auto-closed when done, but waits 
>   untill it is done before sent.

Yes, the approach I prefer would be to just close the buffer immediately
and go back to the previous view (thread view or index). Normally, I 
expect such mail deliveries to happen without errors, but if there is an
error, astroid could perhaps indicate to the user through some means 
(probably a tick mark or a cross icon at the top-right next to the open 
buffers?).

As an alternative, astroid could simply save such messages as 'drafts' 
if it was unable to deliver the mail. Users will then be able to monitor
the 'drafts' folder to discover mails that were not sent?

**Comment by gauteh** [comment]
rnav writes on november 15, 2017 12:49:
> Hi,
> 
> Gaute Hope wrote:
>> rnav writes on november 15, 2017 11:32:
>>> [Apologies for reverting back after all this time]
>>> I have been using msmtpq, but mail delivery is still not instant (compared to mutt). What mutt seems to do is to background the msmtpq process, so email delivery is instant and I am quickly returned back to the thread index. With astroid, delivery to the msmtpq itself sometimes takes a couple of seconds. So, what would be good to have is a similar mode for astroid (perhaps mail:send_delay: -1).
>> 
>> Hi, e-mail delivery is already done in a separate process so that you 
>> can switch away from the current buffer. How should the UI work for 
>> this? Should it be:
>> 
>> * Close and hide somewhere?
>> * You can navigate away, should the messagewindow be closed 
>>   automatically when the message is sent. In that case you can just 
>>   forget about it afterwards.
>> * Should it be closeable; so that it is auto-closed when done, but waits 
>>   untill it is done before sent.
> 
> Yes, the approach I prefer would be to just close the buffer immediately
> and go back to the previous view (thread view or index). Normally, I 
> expect such mail deliveries to happen without errors, but if there is an
> error, astroid could perhaps indicate to the user through some means 
> (probably a tick mark or a cross icon at the top-right next to the open 
> buffers?).
> 
> As an alternative, astroid could simply save such messages as 'drafts' 
> if it was unable to deliver the mail. Users will then be able to monitor
> the 'drafts' folder to discover mails that were not sent?
> 

Ok, makes sense.. have to figure out a way to lock the draft while 
sending is happening. This feature would only work if a draft folder has 
been configured.

**Comment by rnav** [comment]
Indeed. Should this issue be re-opened or do you want me to open a separate issue for this?

**Comment by gauteh** [comment]
rnav writes on november 16, 2017 13:58:
> Indeed. Should this issue be re-opened or do you want me to open a separate issue for this?
> 

Can probably re-open this.

**Comment by rnav** [comment]
I don't seem to have the permissions to re-open this.

**Comment by gauteh** [comment]
#478 is merged and allows the message to be closed automatically after it is sent. Not exactly what this issue is about, but should probably solve it as you can just send and forget about the buffer. Closing unless strong objections.

**Comment by rnav** [comment]
Thanks, that does make things faster! I suppose this eliminates 1-2 seconds and if we can close as soon as we press 'y', that'll be able to eliminate another second or two. I think this is pretty good for now.
