### ISSUE TITLE
Create configuration option reference in wiki

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#328]
#294:

> I think the best is to create one reference page with all the configuration options. This should be done manually, there is a full list of config options in `src/config.cc`. These should be organized according to section, we might think about splitting the page on section at a later time. The rest of the Tour and various examples in the wiki should then link to the config-option in the reference. There should also be links from the config-option to useful places it is referred to in the Tour or the wiki-elsewhere, so that it is easy to find examples and we do not need to duplicate information.

ping: @kirschner @hugoroy @mxmehl

**Comment by hugoroy** [comment]
↪ Gaute Hope / juin 8, 2017 15:04:
> Assigned #328 to @hugoroy.

Yes, I'll try in the future but right now I don't have time :(

**Comment by gauteh** [comment]
Hugo Roy writes on juni 17, 2017 11:20:
> ↪ Gaute Hope / juin 8, 2017 15:04:
>> Assigned #328 to @hugoroy.
> 
> Yes, I'll try in the future but right now I don't have time :(

Ok! thanks for the effort so far though.

**Comment by gauteh** [comment]
#374: `astroid.notmuch.db` is deprecated.

**Comment by mrvdb** [comment]
I can make a few strides in editting the wiki page. (started by changing the format a bit to make it easier)

**Comment by gauteh** [comment]
Marcel van der Boom writes on juli 26, 2017 15:08:
> I can make a few strides in editting the wiki page. (started by changing the format a bit to make it easier)

Great! That's really useful!

**Comment by gauteh** [comment]
@mrvdb went through and re-structured and completed this. Thanks a lot both, this will be very useful!

**Comment by hugoroy** [comment]
Awesome! Thanks a lot!
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
