### ISSUE TITLE
attach message (id: or thread:) as mime attachment to draft

### ISSUE THREAD

**Issue by yeled** [astroidmail/astroid#333]
`mutt` had a great feature to attach a message as a MIME attachment. This was great to be able to say: "I've attached the email I received from so-and-so with their requirements".

As it was MIME, all the original attachments would be there.

It is cleaner than fwd'ing in other threads, if you care for that kind of email thread etiquette.

**Comment by gauteh** [comment]
You can do this with configuring default forward disposition, or use a keybinding that uses either inline or attachment disposition (these may be unbound by default).

**Comment by yeled** [comment]
I can only open a dialog that opens files. Do you mean to export an mbox via the cli first, then attach that?

**Comment by yeled** [comment]
`attach-mail` (`A`) is the function I am thinking to replicate. Instead of opening a file-selection dialog, it opens a thread-view where you can select one or multiple emails via tagging. On quitting from that thread-view, the emails are MIME attachments

**Comment by gauteh** [comment]
Charlie Allom writes on mai 2, 2017 22:00:
> I can only open a dialog that opens files. Do you mean to export an mbox via the cli first, then attach that?
> 

Do you want to attach arbitrary e-mails? If, its just one then you
find it and press 'f' on it to forward it (by default as inline).

**Comment by gauteh** [comment]
Charlie Allom writes on mai 2, 2017 22:02:
> `attach-mail` (`A`) is the function I am thinking to replicate. Instead of opening a file-selection dialog, it opens a thread-view where you can select one or multiple emails via tagging. On quitting from that thread-view, the emails are MIME attachments
> 

Hm, I think the best way to do this to avoid creating too many states is
to be able to attach messages by 'mid:'. Then you can navigate somewhere
while you have your e-mail open and just yank the mids you want and
attach them.

**Comment by yeled** [comment]
`mid:` would be perfect.

**Comment by yeled** [comment]
Thanks @gauteh !
