### ISSUE TITLE
Contextual menu in Thread index: missing 2 icons

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#338]
Reply and Forward icons are missing (it's been like this for a while but I never reported).

![capture d ecran de 2017-05-05 16-47-53](https://cloud.githubusercontent.com/assets/1629771/25750779/0d9d693c-31b3-11e7-8f51-95a7d580dc55.png)

**Comment by gauteh** [comment]
Hugo Roy writes on mai 5, 2017 16:51:
> Reply and Forward icons are missing (it's been like this for a while but I never reported).
> 
> ![capture d ecran de 2017-05-05 16-47-53](https://cloud.githubusercontent.com/assets/1629771/25750779/0d9d693c-31b3-11e7-8f51-95a7d580dc55.png)
> 

I thought these icons were part of the default theme, are you using an
icon-theme that does not inherit 'default'?

Regards, Gaute

**Comment by hugoroy** [comment]
↪ Gaute Hope / mai 8, 2017 10:06:
> 
> I thought these icons were part of the default theme, are you using an
> icon-theme that does not inherit 'default'?


I guess. I don't think I bothered changing the icon theme. The Gnome
tweak tools tell me I'm using “Adwaita (default)”.

**Comment by gauteh** [comment]
Hugo Roy writes on mai 8, 2017 12:17:
> ↪ Gaute Hope / mai 8, 2017 10:06:
>> 
>> I thought these icons were part of the default theme, are you using an
>> icon-theme that does not inherit 'default'?
> 
> 
> I guess. I don't think I bothered changing the icon theme. The Gnome
> tweak tools tell me I'm using “Adwaita (default)”.
> 

It should work with Adawaita, do you have gnome-hicolor installed?

**Comment by hugoroy** [comment]
↪ Gaute Hope / mai 8, 2017 12:27:
> It should work with Adawaita, do you have gnome-hicolor installed?

I have `hicolor-icon-theme` installed.

**Comment by gauteh** [comment]
Ok, maybe the icon cache needs to be updated? We have to check if the missing icons are part of the default gnome icons.

**Comment by hugoroy** [comment]
I reinstalled adwaita and hicolor. I suppose this also updates the cache.

Le 13 mai 2017 20:30:07 GMT+02:00, Gaute Hope <notifications@github.com> a écrit :
>Ok, maybe the icon cache needs to be updated? We have to check if the
>missing icons are part of the default gnome icons.

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gauteh** [comment]
Try #343

**Comment by hugoroy** [comment]
↪ Gaute Hope / mai 14, 2017 13:07:
> Try #343 

Yes, I can see them now.

**Comment by gauteh** [comment]
Hugo Roy writes on mai 14, 2017 13:25:
> ↪ Gaute Hope / mai 14, 2017 13:07:
>> Try #343 
> 
> Yes, I can see them now.

Ok, merged. Seems like Adawaita is the default theme now. These should
be part of that theme.
