### ISSUE TITLE
latest homebrew notmuch and gmime breaks astroid

### ISSUE THREAD

**Issue by yeled** [astroidmail/astroid#342]
`astroid` crashes with later notmuch with their own gmime:

```

(<unknown>:55008): GLib-GObject-WARNING **: cannot register existing type 'InternetAddressList'

(<unknown>:55008): GLib-GObject-CRITICAL **: g_object_newv: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(<unknown>:55008): GLib-GObject-WARNING **: cannot register existing type 'InternetAddress'

(<unknown>:55008): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(<unknown>:55008): GLib-GObject-CRITICAL **: g_object_newv: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
zsh: segmentation fault  astroid --no-auto-poll
```

The workaround is in https://github.com/astroidmail/homebrew-astroid/pull/7

**Comment by gauteh** [comment]
Charlie Allom writes on mai 12, 2017 18:50:
> `astroid` crashes with later notmuch with their own gmime:
> 
> ```
> 
> (<unknown>:55008): GLib-GObject-WARNING **: cannot register existing type 'InternetAddressList'
> 
> (<unknown>:55008): GLib-GObject-CRITICAL **: g_object_newv: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
> 
> (<unknown>:55008): GLib-GObject-WARNING **: cannot register existing type 'InternetAddress'
> 
> (<unknown>:55008): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
> 
> (<unknown>:55008): GLib-GObject-CRITICAL **: g_object_newv: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
> zsh: segmentation fault  astroid --no-auto-poll
> ```
> 
> The workaround is in https://github.com/astroidmail/homebrew-astroid/pull/7

Is this fixed now?

**Comment by yeled** [comment]
Yes, closing. If someone finds issues we can re-open.
