### ISSUE TITLE
TI: Sort threads by date of last message

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#346]
Currently, astroid seems to sort threads in thread_index by the date of the first message in a thread. I think it makes more sense if the last message's date is considered.

**Comment by gauteh** [comment]
Max writes on mai 22, 2017 11:06:
> Currently, astroid seems to sort threads in thread_index by the date of the first message in a thread. I think it makes more sense if the last message's date is considered.
> 

When it sorts oldest first it uses the oldest message (ascending), when
sorting newest first it uses the newest message (descending). 

oldest message and newest message are the two date fields available
without loading all the messages from the db as well.

**Comment by gauteh** [comment]
You can swap by using `C-s`.

**Comment by mxmehl** [comment]
> When it sorts oldest first it uses the oldest message (ascending), when sorting newest first it uses the newest message (descending).

I normally use "newest" but as I said it doesn't seem to work correctly.

![20170522_auswahl_01](https://cloud.githubusercontent.com/assets/6170081/26301144/907436bc-3ee0-11e7-9e6a-57d0aaba8c55.png)

For example in the last thread in the screenshot (with Anke) I sent an email a few hours ago. So the thread is much more current than many others. Can you reproduce that?

**Comment by gauteh** [comment]
Max writes on mai 22, 2017 11:21:
>> When it sorts oldest first it uses the oldest message (ascending), when sorting newest first it uses the newest message (descending).
> 
> I normally use "newest" but as I said it doesn't seem to work correctly.
> 
> ![20170522_auswahl_01](https://cloud.githubusercontent.com/assets/6170081/26301144/907436bc-3ee0-11e7-9e6a-57d0aaba8c55.png)
> 
> For example in the last thread in the screenshot (with Anke) I sent an email a few hours ago. So the thread is much more current than many others. Can you reproduce that?
> 

Not entirely sure how that is supposed to be, check the docs for
notmuch-search. Code for sorting is located at:
thread_index_list_view.cc:301, columns are set in e.g. query_loader.cc:360. dates are loaded using:

```

    newest_date = notmuch_thread_get_newest_date (nm_thread);
    oldest_date = notmuch_thread_get_oldest_date (nm_thread);
```

in db.cc:507.

**Comment by gauteh** [comment]
For reference: https://github.com/astroidmail/astroid/pull/50

**Comment by mxmehl** [comment]
I see, this seems to be a notmuch issue. Because from what the manpage says, notmuch-search should actually do what I expect: sort for the newest message in each thread:

From the man page:

>           --sort=(newest-first|oldest-first)
>                  This option can be used to present results in either  chrono‐
>                  logical  order  (oldest-first) or reverse chronological order
>                  (newest-first).
> 
>                  Note: The thread order will be  distinct  between  these  two
>                  options  (beyond being simply reversed). When sorting by old-
>                  est-first the threads will be sorted by the oldest message in
>                  each  thread,  but  when  sorting by newest-first the threads
>                  will be sorted by the newest message in each thread.

But this isn't the case for me, neither in astroid nor with notmuch-search.

**Comment by gauteh** [comment]
Max writes on mai 24, 2017 1:12:
> I see, this seems to be a notmuch issue. Because from what the manpage says, notmuch-search should actually do what I expect: sort for the newest message in each thread:
> 
> From the man page:
> 
>>           --sort=(newest-first|oldest-first)
>>                  This option can be used to present results in either  chrono‐
>>                  logical  order  (oldest-first) or reverse chronological order
>>                  (newest-first).
>> 
>>                  Note: The thread order will be  distinct  between  these  two
>>                  options  (beyond being simply reversed). When sorting by old-
>>                  est-first the threads will be sorted by the oldest message in
>>                  each  thread,  but  when  sorting by newest-first the threads
>>                  will be sorted by the newest message in each thread.
> 
> But this isn't the case for me, neither in astroid nor with notmuch-search.
> 

Ok, if it doesn't work in notmuch-search it is a notmuch bug, astroid
has to re-sort when adding to the thread-index so there is potential for
bugs there.

**Comment by emdete** [comment]
i just struggled over that sorting dilemma as well and came to the conclusion that it would be nice if it would be possible to sort by first unread email.

**Comment by gauteh** [comment]
Any sorting that isn't supported by notmuch will affect the load order, so you won't be sure to have a correct order before the entire query is loaded. @mxmehl did you figure out if this is a notmuch or astroid bug?

**Comment by mxmehl** [comment]
Neither of both. I learnt that if I search for `tag:XX`, notmuch sorts the threads for the newest message with this tag, and not the newest message of the whole thread. Because the sent mails weren't tagged with XX, only the received mails were tagged and considered for sorting.

So I would have to find a way to automatically tag the sent messages accordingly as well. Because this isn't astroid's misbehaviour, I'll close this issue.

**Comment by gauteh** [comment]
Max writes on juli 3, 2017 11:35:
> Neither of both. I learnt that if I search for `tag:XX`, notmuch sorts the threads for the newest message with this tag, and not the newest message of the whole thread. Because the sent mails weren't tagged with XX, only the received mails were tagged and considered for sorting.
> 
> So I would have to find a way to automatically tag the sent messages accordingly as well. Because this isn't astroid's misbehaviour, I'll close this issue.
> 

Ah, that explains it.
