### ISSUE TITLE
Add minimize to tray

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#350]
It would be nice to let astroid minimize or close to tray optionally.

This is already somehow possible with external tools like alltray but also bugs around sometimes. So a native solution would be great.

**Comment by gauteh** [comment]
Max writes on mai 24, 2017 1:04:
> It would be nice to let astroid minimize or close to tray optionally.
> 
> This is already somehow possible with external tools like alltray but also bugs around sometimes. So a native solution would be great.
> 

Does new GTK3 / Gnome3 have tray support? I still use trays, but it
seems to be dying out.. (regretfully).

- gaute

**Comment by mxmehl** [comment]
> Does new GTK3 / Gnome3 have tray support?

I don't use Gnome3 so no idea. But according to a quick search, Gnome3 has a legacy tray and a extension called "topicons". I assume moving an application to the tray is somehow standardised in various DEs?

Btw, I'm an XFCE user, and I doubt that tray are dying out forever very soon ;)

**Comment by gauteh** [comment]
I think I'm going to close this one, since it will be low priority and I dont see how I will be able to implement it in the near future.
