### ISSUE TITLE
too many open files on open attachment

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#357]
i got an 'to many open files' again when opening an attachment:

```
[14:13:43.071115] [0x00007f13c93f3700] [debug] chunk: spawning: xdg-open, /home/.../.cache/astroid/84vkx9g951-....pptx

(astroid:17521): glibmm-WARNING **: Glib::Error::throw_exception():
  unknown error domain 'g-unix-error-quark': throwing generic Glib::Error exception


(astroid:17521): glibmm-CRITICAL **: 
unhandled exception (type Glib::Error) in signal handler:
domain: g-unix-error-quark
code  : 0
what  : To many open files
```

**Comment by gauteh** [comment]
Is this caused by opening the attachment e.g. many times? You can provoke the error more easily by setting a lower resource limit using `ulimit`.

**Comment by gauteh** [comment]
Need more info, or will close.

**Comment by emdete** [comment]
no i opened that attachment once only. 

i used `lsof -p <PID>` to see the opened files and it shows many open mails which are already deleted (renamed). in my case i had 120 deleted files open. 222 email files where opened.

i restarted astroid and did a `lsof -p <PID>|grep Maildir|wc` which gave 0. after opening and closing an email it was 1, after opening and closing 6 emails i got 3. after opening and closing a thread with 34 emails it was 16. is that desired?

**Comment by gauteh** [comment]
M. Dietrich writes on juni 13, 2017 10:20:
> no i opened that attachment once only. 
> 
> i used `lsof -p <PID>` to see the opened files and it shows many open mails which are already deleted (renamed). in my case i had 120 deleted files open. 222 email files where opened.
> 
> i restarted astroid and did a `lsof -p <PID>|grep Maildir|wc` which gave 0. after opening and closing an email it was 1, after opening and closing 6 emails i got 3. after opening and closing a thread with 34 emails it was 16. is that desired?

Nope, those files are supposed to be closed. there's a leak somwhere.
