### ISSUE TITLE
Adding astroid on wikipedia

### ISSUE THREAD

**Issue by kirschner** [astroidmail/astroid#360]
What do you think about adding astroid on [Wikipedia's e-mail client page](https://en.m.wikipedia.org/wiki/Comparison_of_email_clients)? I thought it might be good to get some more users and maybe also developers in the long run. 

It would be Astroid, Gaute Hope, what about the OS?, GPL-3.0+, GUI, right?

**Comment by gauteh** [comment]
Matthias Kirschner writes on juni 20, 2017 6:08:
> What do you think about adding astroid on [Wikipedia's e-mail client page](https://en.m.wikipedia.org/wiki/Comparison_of_email_clients)? I thought it might be good to get some more users and maybe also developers in the long run. 
> 
> It would be Astroid, Gaute Hope, what about the OS?, GPL-3.0+, GUI, right?

Linux and Mac OS at least, but should work on BSDs as well. You can try! 
They tend to remove stuff that they find 'irrelevant'.

**Comment by kirschner** [comment]
I understand. Then maybe it best to first focus on other ways to get more users and developers.

**Comment by gauteh** [comment]
Yup, I'd be happy to see astroid there, but I wouldn't be surprised if they removed it :/

**Comment by emdete** [comment]
first i liked the idea very much but when scrolling through the endless tables of features and stuff i noticed that astroid does not fit well. all those MUAs are monsters while astroid concentrates on a single duty. it as well introduces a  different view on your mails which you can't even express in those tables. maybe astroid should get an separate paragraph to explain what or how you could do with your mails...
