### ISSUE TITLE
Tagging multiple threads

### ISSUE THREAD

**Issue by mgraham** [astroidmail/astroid#364]
I'm following this page in the tour:

https://github.com/astroidmail/astroid/wiki/Tagging-multiple-threads

It says: 
> You can tag multiple threads by marking them using t, then press + to apply an action to all marked threads, and finally l to tag:

I can't get this to work.  I tag three threads, then press + and add the `spam` tag.  Then I press enter.  Only thread my cursor was on gets marked as `spam`.  The other two are unchanged.

Also, what does `finally l to tag` mean?  I press `l` with multiple threads tagged, and nothing happens.

**Comment by gauteh** [comment]
I think the first `+` should be `;`. Check out the keybindings list (`?`), this brings up an action menu that applies all the actions to the marked threads. Please update the wiki if you figure it out.

**Comment by mgraham** [comment]
Ah - that gets me started - thanks!  I'll try to update the wiki once I figure things out.
