### ISSUE TITLE
Disable multiple astroid instances optionally

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#373]
It would be cool to configure astroid to allow only one main window. If a second astroid instance is launched, the initial one should be taken to foreground instead.

It would be ideal if this worked together with alltray. For example, I always start astroid with `alltray -C -- astroid -l $USER/astroid/astroid.log` to make astroid tray-able (see #350). Launching the same command should just re-open the existing window.

**Comment by gauteh** [comment]
Doesn't alltray have functionality for programatically bringing the window to the front? If a flag or commands are supplied to the astroid executable then it should be possible to specify that they should be opened in the existing window. I thought it did when you did `astroid -m ...` already.

**Comment by mxmehl** [comment]
> Doesn't alltray have functionality for programatically bringing the
> window to the front? 

No, unfortunately not.

> If a flag or commands are supplied to the astroid
> executable then it should be possible to specify that they should be
> opened in the existing window. I thought it did when you did |astroid -m
> ...| already.

That would be nice. `astroid -m ...` opens in the main window even if
trayed. But it doesn't activates the main window but the external editor
in my case (for good reasons).

**Comment by gauteh** [comment]
I don't know if we can bring the main window to the front, that seems like an alltray specific or window-manager specific thing. At best we can set the alert flag / needs-attention flag on the window.

**Comment by gauteh** [comment]
I'm closing this for now, since it is an alltray specific issue untill (if) we do make astroid trayable.

**Comment by mxmehl** [comment]
How do others do it? Just leave the windows open all the time and switch to it with the window selector? Or do they use an own work space just for astroid?

Maybe trays are an antique technique of sorting applications efficiently, and I would be happy to learn alternatives by other astroid users.

**Comment by gauteh** [comment]
Max writes on august 21, 2017 23:14:
> How do others do it? Just leave the windows open all the time and switch to it with the window selector? Or do they use an own work space just for astroid?
> 
> Maybe trays are an antique technique of sorting applications efficiently, and I would be happy to learn alternatives by other astroid users.

I just keep one window open, but I have lots of workspaces, and have one 
mostly just for email / internet / chat. I think I'd support making 
astroid trayable, if someone wants to do it, but it will require a bit 
of work to get right.

**Comment by gauteh** [comment]
https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html

**Comment by gauteh** [comment]
Actually, it is says that it is deprecated so never mind.
