### ISSUE TITLE
Make path expansion in config consistent

### ISSUE THREAD

**Issue by mrvdb** [astroidmail/astroid#374]
The documentation suggests that '~' is expanded from the config. (third example here: 	https://github.com/astroidmail/astroid/wiki/Config )

This, at least in my setup, does not seem to be the case for all paths in the config (paths in account config for example)

**Comment by gauteh** [comment]
The config option `astroid.notmuch.db` is deprecated and should be 
removed from the wiki. The config needs the full path, and is not 
expanded. It could probably use the same code as in config.cc:325. The 
same is for the duplicate code in the config.cc:57 (which can probably 
be replaced by a call to `Utils::expand`).

The paths that are not expanded yet should be handled in a similar way 
as config.cc:325.

**Comment by mrvdb** [comment]
With the merge of #378 this is resolved.
