### ISSUE TITLE
Question: Automatic BCC header?

### ISSUE THREAD

**Issue by hgvhgv** [astroidmail/astroid#379]
In the wiki page for config options, it is mentioned that "some people use an automatic BCC or FCC header" to keep their sent mail (<https://github.com/astroidmail/astroid/wiki/Config>). I tried figuring this out but haven't been able to. I use `msmtpq` (just a queuing script for `msmtp`) as my send agent with `msmtpq -t --read-envelope-from` as the line in my Android config.

Is there a simple way to do this with Astroid (or `msmtp` if anyone wants to jump in)? Searching for "auto BCC" and msmtp otherwise has not led me to any results.

Thanks!

**Comment by gauteh** [comment]
Hi, as far as I can see @mrvdb wrote that bit. Perhaps he knows :)

**Comment by mrvdb** [comment]
I'm pretty sure `msmtp` does not support this, but postfix for example uses an `always_bcc` directive to do this and the `GNUS` mailreader in emacs has something called an `FCC` header if I recall correctly. These were the two things in my mind when I wrote it. 

Note that these two mechanisms work independently of astroid. As far as I know, astroid does not have a feature for automatically injecting Bcc-like headers.

Note that if you just add the Bcc header in the editor, astroid will respect it and use it (i.e. pass it on). If your editor can automate that, you're where you want to be, no?

**Comment by gauteh** [comment]
Maybe we should make it more clear in the wiki that this is not an astroid feature, and suggest which MTA might be able to do this.

**Comment by hgvhgv** [comment]
Thanks! I did see the Postfix possibility while I was poking around but am otherwise happy with `msmtp`. And yes, setting this up in `vim` should't be that hard—so that solves it for me!

Good idea to clarify the wiki.

Great job @gauteh and everyone else here—I love Astroid!

**Comment by mrvdb** [comment]
I've rephrased the paragraph in the wiki a bit. See: [Config wiki page](../wiki/Config)

(#issue mentioning in wiki commits apparently does not work)

**Comment by gauteh** [comment]
Marcel van der Boom writes on august 11, 2017 9:48:
> I've rephrased the paragraph in the wiki a bit. See: [Config wiki page](../wiki/Config)
> 
> (#issue mentioning in wiki commits apparently does not work)

Thanks! You have to link to full URL.

**Comment by gauteh** [comment]
hgvhgv writes on august 11, 2017 9:34:
> Thanks! I did see the Postfix possibility while I was poking around but am otherwise happy with `msmtp`. And yes, setting this up in `vim` should't be that hard—so that solves it for me!
> 
> Good idea to clarify the wiki.
> 
> Great job @gauteh and everyone else here—I love Astroid!

Thanks!

**Comment by mxmehl** [comment]
> Note that if you just add the Bcc header in the editor, astroid will respect it and use it (i.e. pass it on). If your editor can automate that, you're where you want to be, no?

Does astroid respect the BCC header? I'm asking because the reply-to header is being ignored.

**Comment by gauteh** [comment]
Max writes on august 11, 2017 10:18:
>> Note that if you just add the Bcc header in the editor, astroid will respect it and use it (i.e. pass it on). If your editor can automate that, you're where you want to be, no?
> 
> Does astroid respect the BCC header? I'm asking because the reply-to header is being ignored.

Yes, Bcc is respected (edit_message.cc:780 and compose_message.cc:...). 
Have a look for existing (unfixed) issue on reply-to header, custom headers, 
header-filtering (bounce-issue).
