### ISSUE TITLE
'c' on message does not include Cc (and probably Bcc) in recipients of new message

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#381]
should include all recipients.

**Comment by mrvdb** [comment]
To be clear, is this the desired behaviour?

 - copy `Cc:` into `Cc:` of new message
 - copy `Bcc:` into `Bcc:` of new message

If message is from own account:
  - copy `From:` into `From:` of new message
  - copy `To:` into `To:` of new message 

else:
  - copy `From:`  to `To:` in new message
  - use active account `From:` for new message

**Comment by gauteh** [comment]
Marcel van der Boom writes on august 15, 2017 12:51:
> To be clear, is this the desired behaviour?
> 
>  - copy `Cc:` into `Cc:` of new message
>  - copy `Bcc:` into `Bcc:` of new message

Yes, but only if is from own account.

> If message is from own account:
>   - copy `From:` into `From:` of new message
>   - copy `To:` into `To:` of new message 
> 
> else:
>   - copy `From:`  to `To:` in new message
>   - use active account `From:` for new message 

The account matching the 'To:' in the old message.

**Comment by mrvdb** [comment]
Resolved with 8a3b443886442009c924807c031421c4b8c9b96b
