### ISSUE TITLE
Multiple email identities: associating tags with accounts

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#383]
Handling multiple identities is usually very difficult in most email clients. The issue is that a user usually ends up replying to mails with the wrong email identity.

Let's say user Usain has 2 email accounts: usain@pro and usain@personal. Usain tags his email automatically using a set of rules. Most email either gets the tag “pro” or “personal”.

Astroid is smart enough to use the correct email address when replying to mail sent to that email address. However, Astroid at the moment does not handle identities beyond that. So, let's say an email sent to a list (and not directly to Usain's pro address) is tagged with “pro”. When Usain replies to it, the email identity will be the default one. 

I think we could improve this by explictly associating tags with accounts.

So Usain can configure Astroid with, e.g.:

    "accounts": {
        "pro": {
            "name": "Usain",
            "email": "usain@pro",
            "additional_sent_tags": "pro",
            "associated_tags": "pro,work,office,project\/X,project\/Y"
    },
        "perso": {
            "name": "Usain",
            "email": "usain@personal",
            "additional_sent_tags": "perso",
            "associated_tags": "perso,friend,family"
    },
    "default_account": "perso"
    }

What do you think? Is this useful? Is this too much?

PS: I think it would be nice to be able to configure explicitly the default account BTW.

**Comment by gauteh** [comment]
Perhaps it should be associated query? Would be quite flexible.

tir. 15. aug. 2017 kl. 20.04 skrev Hugo Roy <notifications@github.com>:

**Comment by hugoroy** [comment]
> Perhaps it should be associated query? Would be quite flexible.

Yes, even better!

**Comment by gauteh** [comment]
Hugo Roy writes on august 15, 2017 20:07:
>> Perhaps it should be associated query? Would be quite flexible.
> 
> Yes, even better!

I've always wanted to set default account depending in time, but I'm 
thinking about putting anything more advanced in a plugin: then it can 
be decided depending on e.g. wifi? Or does Gnome provide a location 
service we can use?

**Comment by gauteh** [comment]
Try out #386.

**Comment by gauteh** [comment]
Fixed in #386.

**Comment by hugoroy** [comment]
@gauteh can you elaborate on how this works a bit so I can update the wiki?

**Comment by gauteh** [comment]
Hugo Roy writes on september 25, 2017 22:32:
> @gauteh can you elaborate on how this works a bit so I can update the wiki?

There's something here: https://github.com/astroidmail/astroid/wiki/Configuration-Reference#accountsaccountnameselect_query

When replying to a message a from account is chosen based on the following 
prioritized list:

1. Any of your accounts involved in the original message
2. A query `accounts.name.select_query` specified for an account which matches the original message.
3. Default account
