### ISSUE TITLE
Astroid hangs on GPG?

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#384]
After composing an email and immediately upon toggling the "Sign" GPG option, Astroid (the entire UI) hangs; as in, stops responding, and stops refreshing the UI.

What can I do to gather debugging information for this ticket?  Here's an strace of the process -- I've clipped it from where Astroid inserts the signature, so everything after is, I believe, related to GPG.

```
read(25, "---\nGPG : 09E5788F\nWire: @seaner"..., 8191) = 74
read(25, "", 8191)                      = 0
close(25)                               = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3545, ...}) = 0
pipe2([25, 30], O_CLOEXEC)              = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fd77c9d15d0) = 577
close(30)                               = 0
fcntl(25, F_SETFD, 0)                   = 0
fstat(25, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
read(25, "gpg (GnuPG) 2.1.23\nlibgcrypt 1.8"..., 4096) = 584
close(25)                               = 0
wait4(577, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 577
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=577, si_uid=1001, si_status=0, si_utime=0, si_stime=0} ---
pipe([25, 30])                          = 0
pipe([31, 32])                          = 0
pipe([33, 34])                          = 0
pipe([35, 36])                          = 0
pipe([37, 38])                          = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fd77c9d15d0) = 578
close(25)                               = 0
close(32)                               = 0
close(34)                               = 0
close(36)                               = 0
fcntl(38, F_GETFL)                      = 0x1 (flags O_WRONLY)
fcntl(38, F_SETFL, O_WRONLY|O_NONBLOCK) = 0
close(37)                               = 0
fcntl(30, F_GETFL)                      = 0x1 (flags O_WRONLY)
fcntl(30, F_SETFL, O_WRONLY|O_NONBLOCK) = 0
fcntl(31, F_GETFL)                      = 0 (flags O_RDONLY)
fcntl(31, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
fcntl(33, F_GETFL)                      = 0 (flags O_RDONLY)
fcntl(33, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
fcntl(35, F_GETFL)                      = 0 (flags O_RDONLY)
fcntl(35, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
poll([{fd=30, events=POLLOUT}, {fd=31, events=POLLIN}, {fd=33, events=POLLIN}, {fd=35, events=POLLIN}, {fd=-1}], 5, 10000) = 1 ([{fd=30, revents=POLLOUT}])
write(30, "Content-Type: text/plain; charse"..., 202) = 202
poll([{fd=30, events=POLLOUT}, {fd=31, events=POLLIN}, {fd=33, events=POLLIN}, {fd=35, events=POLLIN}, {fd=-1}], 5, 10000) = 1 ([{fd=30, revents=POLLOUT}])
close(30)                               = 0
poll([{fd=-1}, {fd=31, events=POLLIN}, {fd=33, events=POLLIN}, {fd=35, events=POLLIN}, {fd=-1}], 5, 10000) = 0 (Timeout)
poll([{fd=-1}, {fd=31, events=POLLIN}, {fd=33, events=POLLIN}, {fd=35, events=POLLIN}, {fd=-1}], 5, 10000) = 0 (Timeout)
poll([{fd=-1}, {fd=31, events=POLLIN}, {fd=33, events=POLLIN}, {fd=35, events=POLLIN}, {fd=-1}], 5, 10000^Cstrace: Process 32374 detached
 <detached ...>
```

**Comment by gauteh** [comment]
Do you have a gpg-agent running? Which is configured to use a gui 
pinentry to enter the password for you key? otherwise gmime/gpg might 
try to read the password and therefore hangs..


Sean Russell writes on august 18, 2017 15:16:

**Comment by gauteh** [comment]
You can also test if `scons test_crypto` passes.

**Comment by gauteh** [comment]
Closing, need info.

**Comment by serussell** [comment]
Boy, you don't waste any time, do you?  I was traveling and haven't been able to respond, but I'll check it now that I'm back.

**Comment by gauteh** [comment]
Ok. Please go ahead and re-open if you have the chance to test.

**Comment by serussell** [comment]
Yes, `gpg-agent` is running, and `pinentry-program` is configured:

```
➜  astroid grep pinentry ~/.gnupg/gpg-agent.conf
pinentry-program /usr/bin/pinentry-qt
```

I've also tested `pinentry` with the following:

```
➜  ~ pinentry <<EOT
heredoc> SETDESC hello
heredoc> GETPIN
heredoc> EOT
OK Pleased to meet you
OK

** (pinentry:8640): WARNING **: it took 4 tries to grab the keyboard
...
```

and `pinentry` does open up `pinentry-qt` and prompt me for a password.

`scons test-crypto` reports 3 failures:

- `crypto_compose_simple_test` fails trying to find a non-existent file `astroid/test/mail/test_config`
- `crypto_compose_test_encrypt_body` generates an invalid pointer error with `*** Error in `/home/ser/Software/astroid/test/test_crypto': munmap_chunk(): invalid pointer: 0x00007fdc93e745c0 ***`
- `crypto_compose_test_sign_body` generates a memory access violation with `[21:14:45.628797] [0x00007fdc9d9479c0] [debug] utf8: true, UTF-8
unknown location(0): fatal error: in "GPGEncryption/crypto_compose_test_sign_body": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000080)`

This is with 7eac41375cb39ac96539302ea1a65606f6036f37.

**Comment by gauteh** [comment]
Sean Russell writes on august 24, 2017 3:23:
> `scons test-crypto` reports 3 failures:
> 
> - `crypto_compose_simple_test` fails trying to find a non-existent file `astroid/test/mail/test_config`
> - `crypto_compose_test_encrypt_body` generates an invalid pointer error with `*** Error in `/home/ser/Software/astroid/test/test_crypto': munmap_chunk(): invalid pointer: 0x00007fdc93e745c0 ***`
> - `crypto_compose_test_sign_body` generates a memory access violation with `[21:14:45.628797] [0x00007fdc9d9479c0] [debug] utf8: true, UTF-8
> unknown location(0): fatal error: in "GPGEncryption/crypto_compose_test_sign_body": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000080)`
> 

Please do a `scons clean_test`,  and post the full output of:

  $ scons test --verbose

- gaute

**Comment by gauteh** [comment]
What versions of gpg2, gmime and what distro are you using?

**Comment by serussell** [comment]
```
➜  ~ gpg2 --version
gpg (GnuPG) 2.1.23
libgcrypt 1.8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/ser/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
➜  ~ pacman -Ss gmime
extra/gmime 2.6.23+4+g91dcee38-1 [installed]
```
It's Arch Linux, rolling release.  I last did a system sync (`-Syu`) about a week ago.

**Comment by gauteh** [comment]
Can you post the log from the terminal window when you try to toggle the sign button? Make sure astroid is compiled with debug symbols.

I'm using latest Arch without problems, so there must be some configuration stuff that trips this up.

**Comment by gauteh** [comment]
I seem to remember that this could be caused by an expired key or anything requiring interactive intervention, please check that as well.

**Comment by gauteh** [comment]
Perhaps related: https://github.com/jstedfast/gmime/issues/4

**Comment by serussell** [comment]
I completely uninstalled and re-installed GnuPG and messed around with the configs, and Astroid is working now.  So it was never a problem with Astroid; something was borked with GnuPG.  I'm not sure what it was; my tests with `gpg2 -esa test.txt` did open `pinentry-qt`, but since messing with GnuPG fixed it, it was obviously not Astroid.

**Comment by gauteh** [comment]
Ok, good that it worked out!
