### ISSUE TITLE
Webpage says "Astorid" in one place

### ISSUE THREAD

**Issue by gusnan** [astroidmail/astroid#387]
There's a typo in one place on http://astroidmail.github.io/ - astorid instead of astroid.

**Comment by gauteh** [comment]
Andreas Rönnquist writes on august 25, 2017 16:40:
> There's a typo in one place on http://astroidmail.github.io/ - astorid instead of astroid.
> 

Thanks, should be fixed. Allow some time for the page to be 
re-generated.
