### ISSUE TITLE
segmentation fault on startup

### ISSUE THREAD

**Issue by jonassmedegaard** [astroidmail/astroid#388]
After a fresh compile and install, astroid segmentation faults for me.

Possibly relevant is that I use xmonad - I notice some of the last debugging messages seem related to window management - perhaps Astroid makes assumptions on X11 environment being a rich desktop?

[...]
[16:36:10.918018] [0x00007fc633e9dac0] [debug] pm: add pane
[16:36:10.918323] [0x00007fc614f4f700] [info] db: open db read-only, waiting for lock..
[16:36:10.918384] [0x00007fc614f4f700] [debug] db: read-only got lock.
[16:36:10.918639] [0x00007fc614f4f700] [debug] db: open time: 0.348 ms.
[16:36:10.918676] [0x00007fc614f4f700] [debug] ql: refresh stats..
[16:36:10.919579] [0x00007fc633e9dac0] [debug] mw: does not have focus, will not grab modal.
[16:36:10.919668] [0x00007fc633e9dac0] [debug] mw: does not have focus, will not grab modal.
[16:36:10.919711] [0x00007fc633e9dac0] [debug] mw: does not have focus, will not grab modal.
[16:36:10.943470] [0x00007fc633e9dac0] [info] poll: emitted poll state: false
[16:36:10.943635] [0x00007fc633e9dac0] [info] poll: emitted poll state: false
[16:36:10.960324] [0x00007fc633e9dac0] [debug] mw: focus-in: 1 active: true, in_quit: false
Segmentfejl (smed kerne)

I can install debugging symbols and trace, but then need step-by-step guidance for that.

**Comment by gauteh** [comment]
Jonas Smedegaard writes on august 27, 2017 16:37:
> After a fresh compile and install, astroid segmentation faults for me.
> 
> Possibly relevant is that I use xmonad - I notice some of the last debugging messages seem related to window management - perhaps Astroid makes assumptions on X11 environment being a rich desktop?

Not that I am aware, but could be of course. Do you have a working 
notmuch setup?

> [16:36:10.960324] [0x00007fc633e9dac0] [debug] mw: focus-in: 1 active: true, in_quit: false
> Segmentfejl (smed kerne)
> 
> I can install debugging symbols and trace, but then need step-by-step guidance for that.
> 

That would be very helpful, here's how to run astroid through gdb and 
print a backtrace: 

  https://github.com/astroidmail/astroid/wiki/Development#debugging-using-gdb

do you see the main-window flicker before it crahes? Has it ever worked?

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-08-27 17:16:29)
> Jonas Smedegaard writes on august 27, 2017 16:37:
> > After a fresh compile and install, astroid segmentation faults for 
> > me.
> > 
> > Possibly relevant is that I use xmonad - I notice some of the last 
> > debugging messages seem related to window management - perhaps 
> > Astroid makes assumptions on X11 environment being a rich desktop?
> 
> Not that I am aware, but could be of course. Do you have a working 
> notmuch setup?

Yes, I currently use notmuch with "alot" MUA.


> > [16:36:10.960324] [0x00007fc633e9dac0] [debug] mw: focus-in: 1 
> > active: true, in_quit: false Segmentfejl (smed kerne)
> > 
> > I can install debugging symbols and trace, but then need 
> > step-by-step guidance for that.
> > 
> 
> That would be very helpful, here's how to run astroid through gdb and 
> print a backtrace:
> 
>   https://github.com/astroidmail/astroid/wiki/Development#debugging-using-gdb

Thanks (and sorry I didn't look closely enough before asking)!

Here's a bracktrace:

#0  0x00007f3c029b6f17 in g_mime_parser_options_get_address_compliance_mode () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
#1  0x00007f3c029c742f in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
#2  0x00007f3c029c8cbb in internet_address_list_parse () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
#3  0x00007f3c0c48718e in ?? () from /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
#4  0x00007f3c0c483ea9 in notmuch_threads_get () from /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
#5  0x00005555558aa1a4 in Astroid::QueryLoader::loader() ()
#6  0x00005555558acff9 in void std::__invoke_impl<void, void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>(std::__invoke_memfun_deref, void (Astroid::QueryLoader::*&&)(), Astroid::QueryLoader*&&) ()
#7  0x00005555558ac64c in std::__invoke_result<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>::type std::__invoke<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>(void (Astroid::QueryLoader::*&&)(), Astroid::QueryLoader*&&) ()
#8  0x00005555558af28d in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)())) std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
#9  0x00005555558af243 in std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> >::operator()() ()
#10 0x00005555558af222 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> > >::_M_run() ()
#11 0x00007f3c03b9472f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f3c033a9494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007f3c030edabf in clone () from /lib/x86_64-linux-gnu/libc.so.6

(I didn't follow the guide to the letter, but instead installed the 
packaged debugging symbols - tell me if above looks broken, because then 
something is wrong in how I built those packages).


> do you see the main-window flicker before it crahes? Has it ever 
> worked?

Perhaps - If "flicker" comes in a singuar form ("a flick", perhaps?). 
White window is drawn in a split second, then disappears again.

I played with it before, but that was quite some time ago - eg. likely 
before I switched to xmonad - so not sure that is of much help.

I use Debian unstable, and am currently in the process of packaging 
Astroid officially for Debian - initial work (though crashing for me) 
has been uploaded to our experimental branch and now awaits ftpmaster 
approval: https://ftp-master.debian.org/new/astroidmail_0.9.1-1.html

For those reading this email in the future where above URL is gone, try 
instead https://tracker.debian.org/astroidmail - or if that is missing 
too the https://tracker.debian.org/astroid (see why at 
https://bugs.debian.org/873248 ).


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on august 27, 2017 18:20:
> Quoting Gaute Hope (2017-08-27 17:16:29)
>> Jonas Smedegaard writes on august 27, 2017 16:37:
>> > After a fresh compile and install, astroid segmentation faults for 
>> > me.
>> > 
>> > Possibly relevant is that I use xmonad - I notice some of the last 
>> > debugging messages seem related to window management - perhaps 
>> > Astroid makes assumptions on X11 environment being a rich desktop?
>> 
>> Not that I am aware, but could be of course. Do you have a working 
>> notmuch setup?
> 
> Yes, I currently use notmuch with "alot" MUA.
> 
> 
>> > [16:36:10.960324] [0x00007fc633e9dac0] [debug] mw: focus-in: 1 
>> > active: true, in_quit: false Segmentfejl (smed kerne)
>> > 
>> > I can install debugging symbols and trace, but then need 
>> > step-by-step guidance for that.
>> > 
>> 
>> That would be very helpful, here's how to run astroid through gdb and 
>> print a backtrace:
>> 
>>   https://github.com/astroidmail/astroid/wiki/Development#debugging-using-gdb
> 
> Thanks (and sorry I didn't look closely enough before asking)!
> 
> Here's a bracktrace:
> 
> #0  0x00007f3c029b6f17 in g_mime_parser_options_get_address_compliance_mode () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
> #1  0x00007f3c029c742f in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
> #2  0x00007f3c029c8cbb in internet_address_list_parse () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
> #3  0x00007f3c0c48718e in ?? () from /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
> #4  0x00007f3c0c483ea9 in notmuch_threads_get () from /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
> #5  0x00005555558aa1a4 in Astroid::QueryLoader::loader() ()
> #6  0x00005555558acff9 in void std::__invoke_impl<void, void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>(std::__invoke_memfun_deref, void (Astroid::QueryLoader::*&&)(), Astroid::QueryLoader*&&) ()
> #7  0x00005555558ac64c in std::__invoke_result<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>::type std::__invoke<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>(void (Astroid::QueryLoader::*&&)(), Astroid::QueryLoader*&&) ()
> #8  0x00005555558af28d in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)())) std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
> #9  0x00005555558af243 in std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> >::operator()() ()
> #10 0x00005555558af222 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> > >::_M_run() ()
> #11 0x00007f3c03b9472f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #12 0x00007f3c033a9494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
> #13 0x00007f3c030edabf in clone () from /lib/x86_64-linux-gnu/libc.so.6
> 

It seems like gmime 3 is being used here, astroid only supports gmime 2 
yet (as does notmuch I thought). I don't see how that would even 
compile?

Debian package is great news!

Regards, Gaute

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-08-27 20:29:49)
> It seems like gmime 3 is being used here, astroid only supports gmime 
> 2 yet (as does notmuch I thought). I don't see how that would even 
> compile?

Notmuch uses gmime 3 now, in Debian unstable.  Is it much work to adjust 
astroid to support it too?


> Debian package is great news!

 :-)


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on august 27, 2017 23:32:
> Quoting Gaute Hope (2017-08-27 20:29:49)
>> It seems like gmime 3 is being used here, astroid only supports gmime 
>> 2 yet (as does notmuch I thought). I don't see how that would even 
>> compile?
> 
> Notmuch uses gmime 3 now, in Debian unstable.  Is it much work to adjust 
> astroid to support it too?

Not too much, but was hoping to avoid supporting both gmime 2 and gmime 
3. Since gmime 3 is so new I didn't think it would be available in 
debian for a while yet anyway, most other packages depending on it would 
probably not be ready? How do those packages do it?

Gmime 3 is for instance not yet available on Arch Linux.

- gaute

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-08-28 07:23:37)
> Jonas Smedegaard writes on august 27, 2017 23:32:
> > Quoting Gaute Hope (2017-08-27 20:29:49)
> >> It seems like gmime 3 is being used here, astroid only supports 
> >> gmime 2 yet (as does notmuch I thought). I don't see how that would 
> >> even compile?
> > 
> > Notmuch uses gmime 3 now, in Debian unstable.  Is it much work to 
> > adjust astroid to support it too?
> 
> Not too much, but was hoping to avoid supporting both gmime 2 and 
> gmime 3. Since gmime 3 is so new I didn't think it would be available 
> in debian for a while yet anyway, most other packages depending on it 
> would probably not be ready? How do those packages do it?

GMime 3.0.1 entered Debian unstable early July, and is by now used in 
Debian for Grilo, Totem and Notmuch.  If that is any help.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Alright, I guess we should just get going for Gmime 3 then!

**Comment by gauteh** [comment]
This bug seems to be caused by trying to run astroid against gmime 3, which ABI does not match gmime 2. See #389 for porting to Gmime 3.

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-08-28 09:07:33)
> This bug seems to be caused by trying to run astroid against gmime 3, 
> which ABI does not match gmime 2. See #389 for porting to Gmime 3.

Uhm, not sure it makes sense to close this issue yet:

I *did* link with GMime 2.6. Problem must've been that Astroid linked 
with GMime 2.6 crash when Notmuch is linked with GMime 3.0.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on august 28, 2017 9:33:
> Quoting Gaute Hope (2017-08-28 09:07:33)
>> This bug seems to be caused by trying to run astroid against gmime 3, 
>> which ABI does not match gmime 2. See #389 for porting to Gmime 3.
> 
> Uhm, not sure it makes sense to close this issue yet:
> 
> I *did* link with GMime 2.6. Problem must've been that Astroid linked 
> with GMime 2.6 crash when Notmuch is linked with GMime 3.0.

Hm - you might be right. But, if you do have gmime-2 installed 
concurrently then you should be able to start astroid with setting 
LD_LIBRARY_PATH to point to gmime 2. Astroid does not rely on using the 
same gmime as notmuch.

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-08-28 09:42:06)
> Jonas Smedegaard writes on august 28, 2017 9:33:
> > Quoting Gaute Hope (2017-08-28 09:07:33)
> >> This bug seems to be caused by trying to run astroid against gmime 3, 
> >> which ABI does not match gmime 2. See #389 for porting to Gmime 3.
> > 
> > Uhm, not sure it makes sense to close this issue yet:
> > 
> > I *did* link with GMime 2.6. Problem must've been that Astroid linked 
> > with GMime 2.6 crash when Notmuch is linked with GMime 3.0.
> 
> Hm - you might be right. But, if you do have gmime-2 installed 
> concurrently then you should be able to start astroid with setting 
> LD_LIBRARY_PATH to point to gmime 2. Astroid does not rely on using the 
> same gmime as notmuch.

GMime 2.6 and GMime 3.0 are both installed as system shared libraries.

Are you saying that Astroid need to be spoonfed which of them to use?  
That sounds wrong to me.

Could it perhaps be that we are chasing a non-issue here? I mean, you 
were surprised to see GMime 3.0 being involved in my stack trace (or 
whatever it is called what I produced for you) but could it be totally 
harmless and called via Notmuch - and the real bug causing segfault be 
something else entirely?

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on august 28, 2017 10:02:
> Quoting Gaute Hope (2017-08-28 09:42:06)
>> Jonas Smedegaard writes on august 28, 2017 9:33:
>> > Quoting Gaute Hope (2017-08-28 09:07:33)
>> >> This bug seems to be caused by trying to run astroid against gmime 3, 
>> >> which ABI does not match gmime 2. See #389 for porting to Gmime 3.
>> > 
>> > Uhm, not sure it makes sense to close this issue yet:
>> > 
>> > I *did* link with GMime 2.6. Problem must've been that Astroid linked 
>> > with GMime 2.6 crash when Notmuch is linked with GMime 3.0.
>> 
>> Hm - you might be right. But, if you do have gmime-2 installed 
>> concurrently then you should be able to start astroid with setting 
>> LD_LIBRARY_PATH to point to gmime 2. Astroid does not rely on using the 
>> same gmime as notmuch.
> 
> GMime 2.6 and GMime 3.0 are both installed as system shared libraries.
> 
> Are you saying that Astroid need to be spoonfed which of them to use?  
> That sounds wrong to me.

Should not be necessary, astroid should've been linked to a 
major-version so-name of the gmime library. But, sometimes things go 
wrong with that and it might be worth checking out with manually setting 
the library path.

 
> Could it perhaps be that we are chasing a non-issue here? I mean, you 
> were surprised to see GMime 3.0 being involved in my stack trace (or 
> whatever it is called what I produced for you) but could it be totally 
> harmless and called via Notmuch - and the real bug causing segfault be 
> something else entirely?

Hm-- yeah, now that you mention it, that seems like the most sensible 
option.. 

Are you running astroid from source? Perhaps you can see if you can 
start the test version:

$ scons 
$ scons test # this creates the test home directory
$ gdb --args ./astroid -t

**Comment by gauteh** [comment]
That segfault does happen in a gmime call from notmuch. The bug might also lay in that gmime / notmuch function.

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-08-27 20:29:49)
> Debian package is great news!

Package now accepted into Debian, which means we have a development 
overview: https://tracker.debian.org/pkg/astroidmail

...which links (in right side) to build logs that you might find useful: 
https://tracker.debian.org/pkg/astroidmail

...but only if you find it useful!  You certainly do not need to bother 
understanding my possibly weird ways of treating your code if it does 
not bring you joy to do so :-)


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on august 28, 2017 15:44:
> Quoting Gaute Hope (2017-08-27 20:29:49)
>> Debian package is great news!
> 
> Package now accepted into Debian, which means we have a development 
> overview: https://tracker.debian.org/pkg/astroidmail
> 
> ...which links (in right side) to build logs that you might find useful: 
> https://tracker.debian.org/pkg/astroidmail
> 
> ...but only if you find it useful!  You certainly do not need to bother 
> understanding my possibly weird ways of treating your code if it does 
> not bring you joy to do so :-)

Nice :) You may not be aware of --install-sandbox for SConstruct which 
works a bit like DESTDIR.

Did you have a chance to test the test config of astroid. If this truly 
is a notmuch/gmime3 bug then there probably is a particular message somewhere 
in your system causing problems.

Regards, Gaute

**Comment by gauteh** [comment]
Do you have any more information on this seg fault? (as per some of the discussion here you might want to check out #395 for Gmime 3 support)

**Comment by gauteh** [comment]
Gmime 3 support has now been merged into master, hope to make a release soon. Need some more info on this issue or am going to close.

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-09-19 15:13:20)
> Gmime 3 support has now been merged into master, hope to make a release soon. Need some more info on this issue or am going to close.

That is very exciting news!

I will try make time to do the tests you requested - sorry I failed to 
do that already.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-09-19 15:13:20)
> Gmime 3 support has now been merged into master, hope to make a 
> release soon. Need some more info on this issue or am going to close.

Works when compiled with libgmime-3.0-dev.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
yes
