### ISSUE TITLE
Port to Gmime 3

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#389]
https://github.com/jstedfast/gmime/blob/master/PORTING

I am thinking about only supporting Gmime 3 since it is now available by default in Debian unstable, and the rest will probably follow shortly. Notmuch has a system for dealing with both gmime 2 and 3 (see [notmuch:util/gmime-extra.h](https://git.notmuchmail.org/git?p=notmuch;a=blob;f=util/gmime-extra.h;hb=HEAD)) - but I'd really like to avoid that if possible to reduce maintenance.

As distros start to move to gmime 3 this issue will be quite important. Not many will keep both gmime2 and 3 at the same time I think.

Related issues:
#388

**Comment by mxmehl** [comment]
I have no idea about gmime version but in general we should find a way to support Debian Stable or later Ubuntu LTS version users . If it's not possible by enabling backward compatibility (I understand the reasons) we should at least provide some documentation how people can install gmime3 in their distro to make astroid working.

**Comment by gauteh** [comment]
Max writes on august 28, 2017 9:55:
> I have no idea about gmime version but in general we should find a way to support Debian Stable or later Ubuntu LTS version users . If it's not possible by enabling backward compatibility (I understand the reasons) we should at least provide some documentation how people can install gmime3 in their distro to make astroid working.
> 

Yes - I guess there really is no way around supporting both versions. At 
least we can scavenge most of the dual-support stuff from notmuch.

**Comment by gauteh** [comment]
Please test #395 on both gmimes.

**Comment by gauteh** [comment]
Merged.
