### ISSUE TITLE
Tagging all messages in a thread

### ISSUE THREAD

**Issue by guillaumecherel** [astroidmail/astroid#390]
Maybe related to #376 

Say a thread contains one message tagged X. I would like to tag all messages of the thread with the tag X, so I select the thread in thread view and type `+X`, but the messages that do not already have the tag X won't get tagged.

**Comment by gauteh** [comment]
guillaumecherel writes on august 30, 2017 16:00:
> Maybe related to #376 
> 
> Say a thread contains one message tagged X. I would like to tag all messages of the thread with the tag X, so I select the thread in thread view and type `+X`, but the messages that do not already have the tag X won't get tagged.

Hm, yeah - I don't think this is possible at the moment. We should 
either make this possible through 'apply action to all messages' or even 
a multi action that applies to all messages in the thread.

Apply action path:
T - Toggle mark all
; - apply action
+ - tag

All messages action:
?? - All messages action
+  - tag

**Comment by gauteh** [comment]
Gaute Hope writes on august 30, 2017 16:27:
> guillaumecherel writes on august 30, 2017 16:00:
>> Maybe related to #376 
>> 
>> Say a thread contains one message tagged X. I would like to tag all messages of the thread with the tag X, so I select the thread in thread view and type `+X`, but the messages that do not already have the tag X won't get tagged.
> 
> Hm, yeah - I don't think this is possible at the moment. We should 
> either make this possible through 'apply action to all messages' or even 
> a multi action that applies to all messages in the thread.
> 
> Apply action path:
> T - Toggle mark all
> ; - apply action
> + - tag

this path is now possible on latest master.

**Comment by gauteh** [comment]
If you tag the thread in thread-index all the messages will get those tags.
