### ISSUE TITLE
Weird scroll behavior in threaded view

### ISSUE THREAD

**Issue by manishrjain** [astroidmail/astroid#391]
In a threaded view, `j` or `ctrl+j` (and corresponding `k`s) are used to scroll up or down. A blue vertical bar on the left indicates the cursor position. If the cursor is at the top, and j is pressed, the whole screen moves down. Similarly, if the cursor is all the way at the bottom, and you want to move by one email, the whole pane moves -- even though the cursor has plenty of travel left before it reaches the top. This is weird.

Typically, the cursor must travel around 75-80% of the height before the entire pane moves. That's the scroll behavior that feels normal.

**Comment by gauteh** [comment]
Manish R Jain writes on september 3, 2017 15:03:
> In a threaded view, `j` or `ctrl+j` (and corresponding `k`s) are used to scroll up or down. A blue vertical bar on the left indicates the cursor position. If the cursor is at the top, and j is pressed, the whole screen moves down. This is weird.
> 
> Typically, the cursor must travel around 75-80% of the height before the entire pane moves. That's the scroll behavior that feels normal.

The scrolling is centered around the messages, you can also use 'J' and 
'K' to just scroll the pane.

**Comment by manishrjain** [comment]
That's a tangential thing. The issue is around how navigating messages is happening right now. A good example is how Gmail does this (using p/n). It shows the cursor, and on going upwards or downwards, it travels across the screen, before scrolling it.

**Comment by gauteh** [comment]
Manish R Jain writes on september 7, 2017 2:31:
> That's a tangential thing. The issue is around how navigating messages is happening right now. A good example is how Gmail does this (using p/n). It shows the cursor, and on going upwards or downwards, it travels across the screen, before scrolling it.

You can do that with n/p.

**Comment by gauteh** [comment]
I guess it would make sense to swap n/p with the j/k keybindings.

**Comment by gauteh** [comment]
Or, that has to be C-j (or move to next element) so that it also works on expanded messages.

**Comment by manishrjain** [comment]
Yes, n/p works as intended. Also agree that j/k would be the natural way to do it -- in fact, my next question would have been about how to switch n/p to j/k.

**Comment by gauteh** [comment]
Manish R Jain writes on september 7, 2017 9:09:
> Yes, n/p works as intended. Also agree that j/k would be the natural way to do it -- in fact, my next question would have been about how to switch n/p to j/k.
> 

Hopefully, you'll find everything you need here:

  https://github.com/astroidmail/astroid/wiki/Customizing-key-bindings

let me know if you have any questions.

**Comment by gauteh** [comment]
Closing, is configurable.
