### ISSUE TITLE
Push out Linux 64-bit binaries per release

### ISSUE THREAD

**Issue by manishrjain** [astroidmail/astroid#394]
My desktop is running Arch Linux, i5-6600, 4.12.8-2-ARCH kernel with 16GB of RAM. Currently, webkitgitk is taking too long on my computer to compile. I had to run it overnight on my laptop, and it's been half a day spent on my desktop (still compiling). This is really annoying when the end game is just to run astroid.

It would be useful if the binary is placed in the release, so it can just be copy-pasted into `/usr/bin` and started.

**Comment by gauteh** [comment]
Manish R Jain writes on september 4, 2017 6:32:
> My desktop is running Arch Linux, i5-6600, 4.12.8-2-ARCH kernel with 16GB of RAM. Currently, webkitgitk is taking too long on my computer to compile. I had to run it overnight on my laptop, and it's been half a day spent on my desktop (still compiling). This is really annoying when the end game is just to run astroid.
> 
> It would be useful if the binary is placed in the release, so it can just be copy-pasted into `/usr/bin` and started.

I don't think I will do that, but you can find webkitgtk2 here: 

http://gaute.vetsj.com/arkiv/astroid/webkitgtk/webkitgtk-2.4.11-6-x86_64.pkg.tar.xz

sha256sum:
4fb1078f94173f610dc31ff9edd7ae323c810946260a3043b8db5af5a1062e6c webkitgtk-2.4.11-6-x86_64.pkg.tar.xz

**Comment by manishrjain** [comment]
If you don't want to provide binaries, then consider adding instructions in the documentation to install webkitgtk2 without compiling (potentially using the link you shared above).

**Comment by gauteh** [comment]
Manish R Jain writes on september 4, 2017 9:12:
> If you don't want to provide binaries, then consider adding instructions in the documentation to install webkitgtk2 without compiling (potentially using the link you shared above).

Feel free to add a note about this to the Arch Linux wiki page. This 
package was previously provided as a binary by Arch Linux.
