### ISSUE TITLE
Create serialization of Message

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#404]

**Comment by gauteh** [comment]
@Ramblurr: 

Full mime-structure with signature and encryption status is now provided to add_message.

**Comment by gauteh** [comment]
Attachments:
```
attachments - array of attachment:
attachment {
filename - string
size        - human readable string
thumbnail - base64 encoded image src with suitable size (defined in thread_view.hh)
signed    - is attachment signed
signature - signature status (same as for body)
encrypted - is attachment encrypted
encryption - encryption status
}
```

Mime message
```
mime_messages - array of mime_message:
mime_message {
message - full body tree of message (probably not needed)
filename - string
size - human readable size
}
```
> Mime messages should just be opened in their own window, so we just need to render a place holder (like for alternative parts now).

**Comment by Ramblurr** [comment]
Encryption Status

```
{
name - string - name of the signer/encrypter
email - string - email of the signer/enrypter
key - string - key id of signing/encrypting key 
}
```

Signature Status

```
{
name - string - name of the signer
email - string - email of the signer
key - string - key id of signing key
status - ? 
trust - ?
}
```

**Comment by Ramblurr** [comment]
In my one example, an email with 1 signature, the errors field is a string not an array. Not sure how to pop another error in there to test what happens.

But could the C++ always send an array? So in the case of the example above,
 `"errors": [ "no-pub-key" ]`

**Comment by gauteh** [comment]
Yes, that is a bug. Check latest master, I've created an utilty `Utils::extend_ptree` for creating JSON arrays.

**Comment by gauteh** [comment]
https://github.com/GNOME/json-glib does seem to be pretty active.

**Comment by gauteh** [comment]
Closing, obsolete now that #455 is merged.
