### ISSUE TITLE
Bundling JS depenencies and library

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#411]
Sub issue of #403:

The JS library requires a bunch of dependencies that need to be built, additionally the JS library should be bundled together with the astroid JS library. This bundling (using `closure-compiler`) needs to be done after each change to the astroid JS library to make sure that all necessary functions are pulled in from the rest of the deps. The dependencies are:

* hyperx
* preact
* ramda

do these pull in additional dependencies?

We have to make a setup where no internet connection is required for building astroid, that is, we have to ship these depdendecies as e.g. submodules. Additionally, it would be great to limit the build-dependencies, but not having generated files in the repository is a very high priority: if we do, then we should perhaps have the bundle in a separate repository and then submodule it into the main astroid repo. In this case, the bundle should be generated (or check that the latest has been generated!) as part of a `pre-push` hook.

Suggested setup:
``` 
ui/thread_view/     # root
ui/thread_view/SConstruct # stand-alone (if in a separate repo) and SConscriptable in all cases
ui/thread_view/thread-view.html
ui/thread_view/thread-view.scss
ui/thread_view/*.js # astroid JS libs
ui/thread_view/js-dependencies/ # all submodules of other repos in here
ui/thread_view/bundle.min.js # generated bundle
```

**Comment by Ramblurr** [comment]
From IRC:

```
<gauteh> ramblurr: unless we actually want to include generated code in the
            repo i dont think it is necessary to have a separate repo for the depdendencies
<gauteh> that depends a bit on how hard it is to build the js-dependencies
<ramblurr> Yea, so that is what I've been struggling with the past days. I
            chose closure compiler because it is one jar, and all you need is java
            installed to use it. But it's been causing quite a few problems with the new
            code I've written. Basically it hs bugs in its ES6 langauge standard which
            makes it essentially impossible to use it without writing in an older version
            of the language (which is quite crappy)
<ramblurr> I've been following the bug's progress on the closure-compiler
            github, but i'm not optimistic it will be fixed soon.
            (https://github.com/google/closure-compiler/issues/2664 if you're curious)
<ramblurr> The idea of js_dependencies/ with submodules underneath won't work,
            because the srcs for those modules pull in other deps. 
<ramblurr> There's no way around including generated code unless the build can
            use the internet.
<ramblurr> I'm polishing up a separate repo for the js source, with a dist
            branch we can submodule into the main project

```

**Comment by gauteh** [comment]
Ok, I'm starting to wonder whether it is better to assume an internet
connection during compile time - and rather create a scons dist target to
make it easier for distros that creates the bundle in the source package.

lør. 30. sep. 2017 kl. 14.46 skrev Casey Link <notifications@github.com>:

**Comment by gauteh** [comment]
Testing your astroid-js repo. Seems to work pretty good with `yarn`! Let's try without including any generated code for now and rather ship the js-bundle when we do releases.

**Comment by Ramblurr** [comment]
By the way, t hanks for being patient @gauteh, I don't have as much free time for FOSS development as I would like :)

I'll add a README to the js repo today.

So what do you think? Make a dist branch and commit the generated bundle to it, and then submodule the js repo into the main astroid repo?

**Comment by gauteh** [comment]
Ditto. I'm impressed by the effort so far. Let us do it this way first: 
Keep everything in the main repo in a similar way as in gauteh:yarn, no 
generated code - and we make yarn/npm (?) a build dependency. If this 
turns out to be a bad choice during testing we move to a submodule setup 
before merging to 'master'.

**Comment by gauteh** [comment]
Closing this. Going for including everything in main repo. Incorporating yarn in build process still remains.
