### ISSUE TITLE
astroid created an email with weird timezone

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#415]
astroid created an email with (seen when 'V' is pressed):

```
Date: Tue, 10 Oct 2017 17:52:15 +3208
```

which is displayed correctly in astroid as the proper time:

```
Oktober 9, 2017 11:44 (10-09 11:44:15)
```

this is deterministic, constructing an email, either new or as reply give the same TZ in the reply (3208). the environment does not contain a TZ.

if TZ is set the bahavior changes in a strange way. asrtroid seems to do some calculation, i saw +3600, +0000 and others.

**Comment by gauteh** [comment]
Are you on gmime2?

**Comment by emdete** [comment]
yes, gmime 2.6.

**Comment by gauteh** [comment]
did you try #416?

**Comment by mxmehl** [comment]
FYI: For an immediate workaround, you can run `TZ=UTC astroid` to set the TZ just for astroid to +0000 (UTC). Thanks to emdete for this hint!

**Comment by gauteh** [comment]
Max writes on oktober 10, 2017 17:04:
> FYI: For an immediate workaround, you can run `TZ=UTC astroid` to set the TZ just for astroid to +0000 (UTC). Thanks to emdete for this hint!
> 

Please try latest tip of the PR, now also adding TZ info when on gmime2. 
We didn't do this previously.

**Comment by gauteh** [comment]
Will make a minor release once this is confirmed working.

**Comment by gauteh** [comment]
Should be fixed in master.
