### ISSUE TITLE
undo user-defined actions

### ISSUE THREAD

**Issue by Radvendii** [astroidmail/astroid#417]
Would it be possible to undo user defined actions? Like if I bind the Delete key to my script that adds the 'delete' tag to a message, right now it can't be undone with 'u', is that feasible to add? Can we do it by having people also specify an inverse script?

**Comment by gauteh** [comment]
Taeer Bar-Yam writes on oktober 11, 2017 22:20:
> Would it be possible to undo user defined actions? Like if I bind the Delete key to my script that adds the 'delete' tag to a message, right now it can't be undone with 'u', is that feasible to add? Can we do it by having people also specify an inverse script?

Yes, I've missed this as well - some actions are undoable without 
keeping any history. I think specifying a second command would work:

e.g., here a script taking an `-u` flag to undo the action.

```
  thread_index.run(hooks::defer queue %1,hooks::defer -u queue %1)=w
```

**Comment by gauteh** [comment]
Check out #492

**Comment by gauteh** [comment]
Fixed.
