### ISSUE TITLE
Screen casts from tour (in wiki) no longer available

### ISSUE THREAD

**Issue by benjumanji** [astroidmail/astroid#424]
So sad!

**Comment by mxmehl** [comment]
@hugoroy Could you upload them again? They were be found on https://github.com/astroidmail/astroid/wiki

**Comment by hugoroy** [comment]
Oh, sorry. I deleted them when purging temp data. I need to make them again and host them somewhere more stable (i.e. where I'm not going to just delete everything...)

Le 24 octobre 2017 23:30:39 GMT+02:00, Max <notifications@github.com> a écrit :
>@hugoroy Could you upload them again? They were be found on
>https://github.com/astroidmail/astroid/wiki

-- 
Envoyé de mon appareil mobile
Sent from my mobile device

**Comment by yeled** [comment]
Just upload them to github :)

**Comment by gauteh** [comment]
Closing this, please upload if you have time in the future :)
