### ISSUE TITLE
Closing the tab after removing a draft

### ISSUE THREAD

**Issue by MarcinWieczorek** [astroidmail/astroid#431]
Hello

Every time I remove a draft in a thread with `D` key the tab closes and I need to re-open the thread to remove a next draft. I think it should check if it is a lonely message in a thread first.

The code responsible for it is under:
`src/modes/thread_view/thread_view.cc:2647`

**Comment by gauteh** [comment]
Currently we don't have a way of removing messages from a rendered thread. We plan to have this implemented in webkit2 (#408). Until that the old message would still show if we didn't close the thread.

**Comment by MarcinWieczorek** [comment]
Why not just reopen it for now?

**Comment by gauteh** [comment]
It is possible. Haven't done that mainly because it would cause a flicker, the focus and expansion state would change, the same would happen by just reloading the thread in the thread-view.

**Comment by gauteh** [comment]
In that code; you could just reload the thread (if messages.size() > 1).

**Comment by MarcinWieczorek** [comment]
Yup. I guess we're waiting.
