### ISSUE TITLE
Astroid stops marking messages as 'read' when navigating threads using #327

### ISSUE THREAD

**Issue by rnav** [astroidmail/astroid#434]
I've setup the below keybinding to help quickly navigate through unread threads (#327):

> thread_view.next_unread_thread=C-Tab
> thread_view.previous_unread_thread=M-Tab

However, when going through threads, after a while, astroid stops marking threads as 'read'. When that happens, the only way to mark that thread as read would be using the keybinding ('N') -- no other action results in the thread being marked read.

Also, once this happens, all subsequent threads won't be marked read. I end up having to close the thread view and re-open the thread for astroid to again start marking threads as read. Any pointers on what could be going wrong?

Editing to add that I am on the latest astroid level: 0.10.2-1, on archlinux.

**Comment by gauteh** [comment]
So the automatic mark by read once you focus a message doesn't work in some cases?

**Comment by rnav** [comment]
Yes, my workflow in this case is:
- go to the thread index that has the list of messages I am interested in (l, h keybindings)
- open the first message there ('Return' key): message opens and after a brief pause, the 'unread' tag goes away
- Ctrl-<tab> to go to the next unread message..

After some time, the 'unread' tag stops disappearing from the messages. Usually, these are messages from rss feeds, so the message length varies, but this happens whether all of these are single messages, or multiple message threads. I have `max_unread_delay` set to `0.1` since I want to be able to go through some of these messages fast.

**Comment by gauteh** [comment]
rnav writes on november 16, 2017 13:56:
> Yes, my workflow in this case is:
> - go to the thread index that has the list of messages I am interested in (l, h keybindings)
> - open the first message there ('Return' key): message opens and after a brief pause, the 'unread' tag goes away
> - Ctrl-<tab> to go to the next unread message..
> 
> After some time, the 'unread' tag stops disappearing from the messages. Usually, these are messages from rss feeds, so the message length varies, but this happens whether all of these are single messages, or multiple message threads. I have `max_unread_delay` set to `0.1` since I want to be able to go through some of these messages fast.

Ok, does the same happen with max_unread_delay = 0.0?

**Comment by rnav** [comment]
With `max_unread_delay = 0.0`, on navigating to the next message, I see that it doesn't get marked as read at all (I suppose this is why I had chosen to set it to 0.1 previously, as I now recall).

**Comment by gauteh** [comment]
rnav writes on november 16, 2017 16:15:
> With `max_unread_delay = 0.0`, on navigating to the next message, I see that it doesn't get marked as read at all (I suppose this is why I had chosen to set it to 0.1 previously, as I now recall).

Ok, does sound lika a bug. With unread_delay set to 0.0 it should mark 
the message 'read' immediately.

**Comment by gauteh** [comment]
Gaute Hope writes on november 16, 2017 19:02:
> rnav writes on november 16, 2017 16:15:
>> With `max_unread_delay = 0.0`, on navigating to the next message, I see that it doesn't get marked as read at all (I suppose this is why I had chosen to set it to 0.1 previously, as I now recall).
> 
> Ok, does sound lika a bug. With unread_delay set to 0.0 it should mark 
> the message 'read' immediately.

Do you have any large queries still loading or anything else 
modifying/reading the db while this happens? It might be that the unread 
tagging is waiting in the queue.

**Comment by rnav** [comment]
Gaute Hope wrote:
> Gaute Hope writes on november 16, 2017 19:02:
>> rnav writes on november 16, 2017 16:15:
>>> With `max_unread_delay = 0.0`, on navigating to the next message, I see that it doesn't get marked as read at all (I suppose this is why I had chosen to set it to 0.1 previously, as I now recall).
>> 
>> Ok, does sound lika a bug. With unread_delay set to 0.0 it should mark 
>> the message 'read' immediately.
> 
> Do you have any large queries still loading or anything else 
> modifying/reading the db while this happens? It might be that the unread 
> tagging is waiting in the queue.

No, this happens regardless. With `unread_delay` set to 0.0, this 
happens every single time. With a non-zero `unread_delay`, this starts 
happening after I navigate through a few mails. I've confirmed this by 
running astroid from the terminal and looking at the output there.

**Comment by gauteh** [comment]
Can you try #441?

**Comment by rnav** [comment]
Gaute Hope wrote:
> Can you try #441?

Awesome -- this looks like it solves the problem for me! I tried this 
briefly and it seems to be working fine. I will report back if things 
change. Thanks for the fix!

**Comment by gauteh** [comment]
Great! Merged to master, marking as fixed for now.
