### ISSUE TITLE
Editor doesn't launch (sometimes)

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#435]
When replying to a message, sometimes the editor doesn't launch.  I see the window with the draft and the "Press Enter to edit" hint, but the editor did not launch and pressing "Enter" does not launch the editor.  Once this starts happening, the editor will never launch again (for compose, reply, or forward functions), and the resolution is to exit and restart astroid.  It smells like a socket corruption issue.

Sometimes the issue happens when astroid is first launched; sometimes after composing or replying to a few emails.  It always happens, eventually.

Astroid was built from source, commit bc7e6eab5338770d95d032ebc59d7bdbbab9e0a8
Editor is gvim from arch, extra/gvim 8.0.1176-1
xorg is from arch, extra/xorg-server 1.19.5-1
Running i3 as the WM, installed from AUR, aur/i3-gaps 4.14.1-1 [installed] (63) (5.87) 

A log starting from pressing "r" to reply to a message, resulting in not being able to edit, is [here](https://cloud.germane-software.com/public.php?service=files&t=5db2006905ddd89dcbee095176b7db5b).

P.S. this is not new behavior; astroid has always behaved like this for me.

**Comment by gauteh** [comment]
Sean Russell writes on november 15, 2017 11:38:
> When replying to a message, sometimes the editor doesn't launch.  I see the window with the draft and the "Press Enter to edit" hint, but the editor did not launch and pressing "Enter" does not launch the editor.  Once this starts happening, the editor will never launch again (for compose, reply, or forward functions), and the resolution is to exit and restart astroid.  It smells like a socket corruption issue.
> 
> Sometimes the issue happens when astroid is first launched; sometimes after composing or replying to a few emails.  It always happens, eventually.
> 
> Astroid was built from source, commit bc7e6eab5338770d95d032ebc59d7bdbbab9e0a8
> Editor is gvim from arch, extra/gvim 8.0.1176-1
> xorg is from arch, extra/xorg-server 1.19.5-1
> 
> A log starting from pressing "r" to reply to a message, resulting in not being able to edit, is [here](https://cloud.germane-software.com/public.php?service=files&t=5db2006905ddd89dcbee095176b7db5b).
> 

does this happen with the embedded editor or the external editor?

- gaute

**Comment by serussell** [comment]
The embedded editor.

There's an external editor? How do I get to this mythical beast?

**Comment by gauteh** [comment]
Sean Russell writes on november 15, 2017 11:53:
> The embedded editor.
> 
> There's an external editor? How do I get to this mythical beast?

The solution lurks in the wiki: https://github.com/astroidmail/astroid/wiki/Customizing-editor

**Comment by serussell** [comment]
It happens with both.  Actually, in the 60 seconds I've been playing with it, I haven't seen an external editor.  No external window is opened by astroid, on compose or reply, or on subsequent "Enter"s in the window.

"gvim," by itself, does open gvim.

**Comment by serussell** [comment]
How about these errors in the output:

(astroid:11517): glibmm-WARNING **: invalid substitution "%2" in fmt string "gvim -geom 10x10 --servername %2 --socketid %3 -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' %1"

(astroid:11517): glibmm-WARNING **: invalid substitution "%3" in fmt string "gvim -geom 10x10 --servername %2 --socketid %3 -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' %1"

External.

**Comment by gauteh** [comment]
Sean Russell writes on november 15, 2017 12:01:
> How about these errors in the output:
> 
> (astroid:11517): glibmm-WARNING **: invalid substitution "%2" in fmt string "gvim -geom 10x10 --servername %2 --socketid %3 -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' %1"
> 
> (astroid:11517): glibmm-WARNING **: invalid substitution "%3" in fmt string "gvim -geom 10x10 --servername %2 --socketid %3 -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' %1"
> 
> External.

You have to change the command line when changing to external editor - 
removing all the severname socketid stuff: See the wiki for examples for 
various editors.

- -gaute

**Comment by serussell** [comment]
Ok -- got your message and will try that.  I changed back to embedded editor (which sometimes works), started astroid, and tried to compose an email, which failed.  I looked for the gvim command and ran it on the command line with strace; it hangs with a bunch of these:

```
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=9, events=POLLIN}], 3, -1) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="U\2\307\2w\3323E\3\4\4\0\0\0\0\0\0\0\0\4\4\4\4\4\0\0\3\37%\2\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
```

I'll try changing the command -- I saw it in the wiki, but was moving too fast (limited time this morning).

**Comment by gauteh** [comment]
Sean Russell writes on november 15, 2017 12:09:
> Ok -- got your message and will try that.  I changed back to embedded editor (which sometimes works), started astroid, and tried to compose an email, which failed.  I looked for the gvim command and ran it on the command line with strace; it hangs with a bunch of these:
> 
> ```
> poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=9, events=POLLIN}], 3, -1) = 1 ([{fd=3, revents=POLLIN}])
> recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="U\2\307\2w\3323E\3\4\4\0\0\0\0\0\0\0\0\4\4\4\4\4\0\0\3\37%\2\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
> recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
> recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
> ```

Those could stem from the socket not being open on the astorid side 
where it would have been embedded.

Havnen't had the chance to look on the first log either. Generally 
external editor works less buggy. With wayland and on mac os the only 
thing that works is the external editor.

I use it myself just because I like it better.

**Comment by serussell** [comment]
External seems to be working -- thanks!

**Comment by gauteh** [comment]
Sean Russell writes on november 15, 2017 13:03:
> External seems to be working -- thanks!

Good stuff!
