### ISSUE TITLE
Move project further up in CMakeLists.txt?

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#436]
Move project further up in CMakeLists.txt: https://gitlab.kitware.com/cmake/cmake/issues/17467#note_343217

**Comment by gauteh** [comment]
@c-alpha

**Comment by c-alpha** [comment]
I'm not using Ninja, but make. The more diverse tools we test against, the more stable the build should be.

Can you take 9cb6b2740bba7ed0af176deebf2675563e1a5ba0 for a spin to see if that solves your issue?

**Comment by gauteh** [comment]
c-alpha writes on november 15, 2017 15:53:
> I'm not using Ninja, but make. The more diverse tools we test against, the more stable the build should be.
> 
> Can you take 9cb6b2740bba7ed0af176deebf2675563e1a5ba0 for a spin to see if that solves your issue?
> 

It does, pushed to master.

**Comment by c-alpha** [comment]
I guess we can close this one?

**Comment by gauteh** [comment]
Yes

tor. 16. nov. 2017 kl. 21:42 skrev c-alpha <notifications@github.com>:
