### ISSUE TITLE
move COPYING-CMAKE-SCRIPTS to cmake?

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#439]
@c-alpha, @hugoroy: I assume this only applies to the cmake scripts inside this directory? In that case we could move the COPYING-CMAKE--- file in there. In the spirit of keeping the top-level dir clean.

**Comment by gauteh** [comment]
Actually, I see that the COPYING-CMAKE-SCRIPTS is contained in its entirety in licence.md. In that case we can just delete it.

**Comment by c-alpha** [comment]
On 2017-11-20, at 12:51 , Gaute Hope <notifications@github.com> wrote:

> Actually, I see that the COPYING-CMAKE-SCRIPTS is contained in its entirety in licence.md. In that case we can just delete it.
> [...]

I would not have any concerns with either option (moving or deleting). In both cases, the license.md would need minor adjustments though. Happy for @gauteh to make which ever way you and @hugoroy prefer.

**Comment by gauteh** [comment]
Went with deletion.
