### ISSUE TITLE
CMake Error: Generator: execution of make failed. Make command was: ""

### ISSUE THREAD

**Issue by gerroon** [astroidmail/astroid#443]
Hi

I do not know much about cmake and I need a front end for notmuch. So I just tried the installation on Debian testing x64

(in the asteroid directory)
cmake --build build
No such file or directory
CMake Error: Generator: execution of make failed. Make command was: ""

When I try the other command

cmake -H. -Bbuild -GNinja                                                                                                                                                                   ⏎
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

thanks

**Comment by gauteh** [comment]
Hi,

did you run:

$ cmake -H. -Bbuild

first?
