### ISSUE TITLE
astroid unusable with gtk dark theme

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#444]
you can use theming with gtk and if you switch to the dark theme astroid doesnt display the index well. some text is in same color as the background and so on (there is a subject_color but no authors_color, so these can't be easily changed).

isnt there a way to detect these theme-colors and use it accordingly?

**Comment by Ashymad** [comment]
I have stumbled upon this bug as well. The problem is that Astroid does not change the colour of it's background to one specified by the theme, but it does change font colour for date and sender columns.
Screenshot:
![image](https://user-images.githubusercontent.com/15618637/34101358-c853973a-e3e5-11e7-8c3f-cb80db5a752e.png)

**Comment by tkerber** [comment]
I can't confirm this issue. I am using astroid just fine with the Arc-Dark theme. Maybe you are using a dark GTK2 theme and light GTK3 or something similar?

**Comment by gauteh** [comment]
M. Dietrich writes on desember 5, 2017 22:19:
> isnt there a way to detect these theme-colors and use it accordingly?

I remember having looked for ways to do this without success (also to 
get the default font color, which seems to be the main problem here). In 
this theme; is the background supposed to be dark?

**Comment by gauteh** [comment]
Could you see how it looks if you comment out line 107 in src/modes/thread_index/thread_index_list_cell_renderer.cc?

**Comment by gauteh** [comment]
Between read and unread the difference is bold vs regular font, perhaps a
different font makes this clearer? Also, you can configure the color of
those other hard to see fields.

With this change, you can probably not see the difference of marked and
unmarked messages.

tor. 4. jan. 2018 kl. 21:30 skrev Szymon Mikulicz <notifications@github.com

**Comment by Ashymad** [comment]
Yes, changing the font and configuring the color helped. And indeed I can't see if a message is marked or not.

**Comment by gauteh** [comment]
Szymon Mikulicz writes on januar 4, 2018 22:33:
> Yes, changing the font and configuring the color helped. And indeed I can't see if a message is marked or not.
> 

Can you test if everything works with #449?

**Comment by Ashymad** [comment]
Now it works very well, thank you. The only problem left is that the colour for marked messages is extremely bright, it would be nice to be able to configure it.

**Comment by gauteh** [comment]
You can 😊

fre. 5. jan. 2018 kl. 11:26 skrev Szymon Mikulicz <notifications@github.com

**Comment by emdete** [comment]
hm, it did not change anything in the first place. so i removed all *color* setting in my config and restarted. afterwords it looked much better but i dont like blue. so i opened the config again and tried to figure out where that came from. i could not find any blue rgb value but found background_color_selected which was empty. so i put in some value (#555555 or such) but that brought me back to the design as before (white back&foreground for unselected)... what did i do wrong?

**Comment by gauteh** [comment]
On latest master right? I’ll check if I handle that case correctly.

fre. 5. jan. 2018 kl. 21:03 skrev M. Dietrich <notifications@github.com>:

**Comment by emdete** [comment]
config: i removed all occurences of config setting which have "color" in its name, started & stopped astroid to have defaults. i saw `background_color_selected` being empty. so i put `#ee9900` in. the screensots show astroid with empty `background_color_selected`:

![empty](https://mister-muffin.de/p/xD6w.png)

and with yellow:

![yellow](https://mister-muffin.de/p/jgC6.png)

i changed only this single setting but the whole background is set to white (with white foreground).

**Comment by gauteh** [comment]
M. Dietrich writes on januar 9, 2018 8:37:
> config: i removed all occurences of config setting which have "color" in its name, started & stopped astroid to have defaults. i saw `background_color_selected` being empty. so i put `#ee9900` in. the screensots show astroid with empty `background_color_selected`:
> 
> ![empty](https://mister-muffin.de/p/xD6w.png)
> 
> and with yellow:
> 
> ![yellow](https://mister-muffin.de/p/jgC6.png)
> 
> i changed only this single setting but the whole background is set to white (with white foreground). 
> 

Hm, weird - and you're sure you are on the latest version from master?

- gaute

**Comment by emdete** [comment]
yes, its latest master. can't you reproduce the bahaviour? i forgot to mention to set

```
[Settings]
gtk-application-prefer-dark-theme=1
```

in `~/.config/gtk-3.0/settings.ini` in the last post to "switch to the dark theme" as initially said.

**Comment by Ashymad** [comment]
I cannot reproduce this. It works as intended on my system. Maybe post your full config?

**Comment by emdete** [comment]
i did the following:

i set `gtk-application-prefer-dark-theme=1` (see above), removed the config entirely, started & stopped astroid, set `"background_color_selected": "#ee9900"` in that fresh config file, started astroid et voila (see screenshot above). current version here is HEAD master. is that what you tried @Ashymad ?

**Comment by Ashymad** [comment]
Indeed. Just to be sure I've rebuilt astroid and followed your steps exactly and after changing the option
the background is still dark and selected message has yellow background.
![image](https://user-images.githubusercontent.com/15618637/34906671-2fcd26ec-f872-11e7-84a4-b73b8b0e3802.png)

**Comment by emdete** [comment]
what a mess! my fault. i use `examples/astroid` to start it but build with scons which builds in `./astroid`, not `./build/astroid` as required by the script. so i started the old version of my tries with ninja all the time.

yes you are right, i have the same appearance now as on your screenshot. thank you for your help!
