### ISSUE TITLE
GPG question

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#445]
This is a question I couldn't find in the wiki or issues list; it is not a bug report.

What's necessary for Astroid to recognize an encrypted email and process it for decryption?  

I am exchanging emails with a party who's encrypted emails are inline.  They are not multipart-mime.  They are content-type text/plain.  The bodies are ASCII armored.  Astroid is displaying the messages as if they were regular, clear-text messages; it is not decrypting them, and I'm curious as to what Astroid uses to detect encryption.

**Comment by gauteh** [comment]
Hi,

Currently only pgp/mime, and not inline pgp is supported. Gmime3 does have
better inline support , but we are probably not making use of that.

Regards, Gaute

lør. 16. des. 2017 kl. 02:55 skrev Sean Russell <notifications@github.com>:
