### ISSUE TITLE
body text is not used from editor

### ISSUE THREAD

**Issue by peterus** [astroidmail/astroid#447]
I wanted to use the markdown feature, so i used the last version from github.
compiling and running was not a problem. I updated the config (creating a new one and setting up everything again) again without some problems.

If i want to create a new mail (gvim extern and intern, commands suggested from wiki) the body text is not used.

I could trace it back to this line:

https://github.com/astroidmail/astroid/blob/80253d28e6b27744993e2f406b0e1da9ed10bb83/src/message_thread.cc#L332

c->preferred, html and fallback_html are all false -> no text will be applied to body.
As I don't know more about this code, I have to ask here for help.

Maybe another help for you: i am getting this error msg in the log (somewhere else) (no idea if this is helping):

> (astroid:28058): GLib-GObject-WARNING **: invalid cast from 'GMimeMultipart' to 'GMimePart'

Arch Linux (everything up to date)

**Comment by gauteh** [comment]
You have to open the HTML part, it is not shown by default. I think it is select the element and then C-Space.

**Comment by gauteh** [comment]
There's another issue concerning which part are shown by default. Closing this as duplicate.
