### ISSUE TITLE
Cannot send mail when running astroid from desktop

### ISSUE THREAD

**Issue by dnebauer** [astroidmail/astroid#450]
I have compiled and installed `astroid` on debian linux (prefix=/usr). When launched from a terminal it runs successfully, including writing to its log file and sending mail. When run from the desktop, i.e., a desktop menu entry based on the `astroid.desktop` file, it fails to write to its default log file and fails to send mail.

Mail is configured to be sent by `msmtpq`. The `msmtp` log shows that `msmtp` is not receiving the failed send jobs from `astroid`.

Here is a log extract showing a successful mail send attempt after launching `astroid` from the terminal:

```log
[info] cm: sending (threaded)..
[debug] em: set info (ready: true): sending message... Press C-c to cancel!
[warning] cm: sending message from account: David Nebauer <davidnebauer@hotkey.net.au>
[debug] tv: set info: sending message... Press C-c to cancel!
[debug] cm: sending message using command: msmtpq --account=bigpond -t --read-envelope-from
[debug] em: set warning (ready: true): 
[debug] em: got tv ready.
[debug] em: set info (ready: true): sending message... Press C-c to cancel!
[debug] tv: set info: sending message... Press C-c to cancel!
[debug] em: set warning (ready: true): 
[debug] sendmail:   mail for [ --account=bigpond -t --read-envelope-from ] : send was successful
[warning] cm: message sent successfully!
```

Here is a log extract showing an unsuccessful mail send attempt after launching `astroid` from the desktop:

```log
[info] cm: sending (threaded)..
[warning] cm: sending message from account: David Nebauer <davidnebauer@hotkey.net.au>
[debug] cm: sending message using command: msmtpq --account=bigpond -t --read-envelope-from
[debug] em: set info (ready: true): sending message... Press C-c to cancel!
[error] cm: could not send message!
[debug] tv: set info: sending message... Press C-c to cancel!
[debug] em: set warning (ready: true): 
[debug] em: got tv ready.
[debug] em: set info (ready: true): sending message... Press C-c to cancel!
[debug] tv: set info: sending message... Press C-c to cancel!
[debug] em: set warning (ready: true): 
[debug] em: set info (ready: true): 
[debug] em: set warning (ready: true): message could not be sent!
[debug] tv: set warning: message could not be sent!
[debug] em: got tv ready.
[debug] em: set info (ready: true): 
[debug] em: set warning (ready: true): message could not be sent!
[debug] tv: set warning: message could not be sent!
[info] em: message sending done.
```

If I manually specify the log file path in the `Exec` key within the desktop file, `astroid` *will* write to the log file. Nothing I have been able to do, however, results in successfully sending mail when `astroid` is launched from the desktop.

I have experimented with various versions of the `Exec` command:

|Desktop file `Exec` commands|
|--------------------------|
|`astroid %u`|
|`unbuffer astroid %u`|
|`/usr/bin/astroid %u`|
|`unbuffer /usr/bin/astroid %u`|
|`astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`unbuffer astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`/usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`unbuffer /usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`unbuffer astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`/usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`unbuffer /usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u`|
|`sh -c "astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|
|`unbuffer sh -c "astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|
|`sh -c "/usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|
|`unbuffer sh -c "/usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|
|`sh -c "astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|
|`unbuffer sh -c "astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|
|`sh -c "/usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|
|`unbuffer sh -c "/usr/bin/astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"`|

Each `Exec` command beginning with `sh -c` has been tried with the `Terminal` key set to both `true` and `false`.

I've also tried running a local wrapper script that, in turn, runs `astroid`. Again, this works fine if run from a terminal but fails if launched from the desktop.

I searched open and closed issues containing `terminal` or `desktop` and this problem does not appear to have been reported previously.

Does anyone know what is causing this problem when running `astroid` from the desktop? Does anyone know a fix or workaround?

System:

* Debian 4.14.7-1 (2017-12-22) x86_64 GNU/Linux
* Gnome 3.26.2
* Astroid 0.10.2-63-gcd899d3f

**Comment by gauteh** [comment]
Could you check if you environment is different between the desktop and the terminal, and whether this may be the cause?

**Comment by dnebauer** [comment]
It appears the problem is that running astroid from the desktop (using an `astroid.desktop` file like the one provided as part of astroid) causes it to run in a non-interactive shell. You may have noted one of the options I tried above was:

```sh
sh -c "astroid --log-level trace --log /home/david/.local/mail/log/astroid.log %u"
```

Well, using an interactive `bash` shell results in an instance of astroid that writes to the log file *and* successfully sends mail:

```bash
bash -ic "/usr/bin/astroid --log /home/david/.local/mail/log/astroid.log %u"
```

Hooray! Note that this command results in a terminal window opening and remaining open as long as astroid runs. Running astroid as a background process allows the terminal to close instantly:

```bash
bash -ic "/usr/bin/astroid --log /home/david/.local/mail/log/astroid.log %u &"
```

Here's where it gets confusing. If I run the same command without the custom `--log` option:

```bash
bash -ic "/usr/bin/astroid %u &"
```

it results in an instance of astroid that still sends mail but *doesn't* write to the default log file `~/.config/astroid/log`. Weird.

Also, note that I used `bash` rather than `sh`. I could not find a successful solution using `sh`. The equivalent command:

```sh
sh -i -c "/usr/bin/astroid --log /home/david/.local/mail/log/astroid.log %u"
```

results in an instance of astroid that does write to the custom log file but *doesn't* send mail successfully.

Note that for all these cases `Terminal` is set to `true`.

So, make of all that what you will, but I've at least found a desktop `Exec` command that works for me. I've put an altered version of `astroid.desktop` in `~/.local/share/applications/` to override the one that installed system wide with astroid.

I hope this helps someone figure out what is going on and maybe even tweak `astroid` so the default `Exec` command works.

**Comment by gauteh** [comment]
Usually the environment is set up differently based on whether the shell 
session is interactive or not. Perhaps this could be the cause?

I have this file in my ~/.local/share/applications/astroid.desktop:

```
[Desktop Entry]
Name=Astroid Mail
Comment=Graphical notmuch email client
Exec=astroid %u
Icon=astroid
Terminal=false
Type=Application
Keywords=Email;E-mail;
Categories=Network;Email;
MimeType=x-scheme-handler/mailto;
```
