### ISSUE TITLE
Cannot bind = key

### ISSUE THREAD

**Issue by dnebauer** [astroidmail/astroid#451]
I wan't to bind both `thread_index.tag` and `thread_view.tag_message` to the `=` key. I've tried the various formats used in the default keybindings (generated by `devel/get_keys.py`):

Keybinding attempts | Result
-----|-----
`thread_index.tag==` | unbinds `+` key
`thread_index.tag=\=` | binds to `\` key
`thread_index.tag=Key ("=")` | error: invalid number of parts
`thread_index.tag=Key ("\=")` | error: invalid number of parts
`thread_index.tag=Key (GDK_KEY_equal)` | error: invalid key name
`thread_index.tag=Key (GDK_KEY_KP_Equal)` | error: invalid key name
`thread_index.tag=Key((guint) GDK_KEY_equal)` | error: invalid key name
`thread_index.tag=Key((guint) GDK_KEY_KP_Equal)` | error: invalid key name
`thread_index.tag=Key (false, false, (guint) GDK_KEY_equal)` | error: invalid key name
`thread_index.tag=Key (false, false, (guint) GDK_KEY_KP_Equal)` | error: invalid key name
`thread_index.tag=Key (false, true, (guint) GDK_KEY_equal)` | error: invalid key name
`thread_index.tag=Key (false, true, (guint) GDK_KEY_KP_Equal)` | error: invalid key name
`thread_index.tag=Key (true, false, (guint) GDK_KEY_equal)` | error: invalid key name
`thread_index.tag=Key (true, false, (guint) GDK_KEY_KP_Equal)` | error: invalid key name
`thread_index.tag=Key (true, true, (guint) GDK_KEY_equal)` | error: invalid key name
`thread_index.tag=Key (true, true, (guint) GDK_KEY_KP_Equal)` | error: invalid key name

In each case attempting to being the key to `thread_view.tag_message` gave the same result.

Is it possible to make these bindings to the `=` key?

**Comment by gauteh** [comment]
Yeah - that's a bug! Probably needs to be fixed before it works..

**Comment by gauteh** [comment]
Actually; it should be:

`thread_index.tag=equal`

**Comment by dnebauer** [comment]
Thanks, that works great. It was the only %^^$#$^% variation I didn't try! In my defense, none of the default keybindings use the raw key name...

**Comment by gauteh** [comment]
dnebauer writes on januar 8, 2018 8:56:
> Thanks, that works great. It was the only %^^$#$^% variation I didn't try! In my defense, none of the default keybindings use the raw key name... 

You are right: the Key(..) doesn't work as a spec in the keybindings 
file, they should've ideally be converted to valid specs by the 
devel/get_keys.py script. Maybe the wiki at least needs some accessible 
information on this!
