### ISSUE TITLE
thread_view.search.search_or_next crashes astroid

### ISSUE THREAD

**Issue by hgvhgv** [astroidmail/astroid#459]
since switching to macos and using `astroid` from homebrew, `thread_view.search.search_or_next` (still bound to C-f) consistently crashes.  Pertaining to the crash:

```
[09:30:52.604486] [0x00007fffc24d33c0] [debug] cb: got key: 65508
[09:30:52.611663] [0x00007fffc24d33c0] [debug] cb: got key: 65514
[09:30:52.614498] [0x00007fffc24d33c0] [debug] cb: got key: 65512
[09:30:55.938290] [0x00007fffc24d33c0] [debug] mw: focus-in: 1 active: false, in_quit: false
[09:30:57.885104] [0x00007fffc24d33c0] [debug] cb: cmd (in mode: 1): test
[09:30:57.885662] [0x00007fffc24d33c0] [debug] tv: searching for: test
dyld: lazy symbol binding failed: Symbol not found: _usearch_open_60
  Referenced from: /usr/local/opt/webkitgtk@2.4.11/lib/libwebkitgtk-3.0.0.dylib
  Expected in: flat namespace

dyld: Symbol not found: _usearch_open_60
  Referenced from: /usr/local/opt/webkitgtk@2.4.11/lib/libwebkitgtk-3.0.0.dylib
  Expected in: flat namespace

[1]    4284 abort      astroid
```

I'm on macos 10.12.6 with astroid (via homebrew) from commit 3ce199d2e51d09469a5d142fd53ffcfd4784227d. 

I know webkit2 is an ongoing issue and might be tough to troubleshoot (plus long build time---maybe I can set up Docker?).

**Comment by gauteh** [comment]
Looks like you have to re-build webkitgtk

**Comment by hgvhgv** [comment]
OK when I have a chance I'll give Docker a go!

**Comment by gauteh** [comment]
Ok, closing. Let me know if this is not resolved by recompiled webkit.

**Comment by c-alpha** [comment]
Hello @hgvhgv , it seems I have run into a very similar issue. I'm on a Mac. Did you have any luck resolving this?

**Comment by hgvhgv** [comment]
The last time I built webkit it took nearly 24 hours, and I usually have to move my laptop around much more often than that (and this is my only machine currently). So that's the main limiting factor.  But will post when I do have a chance.

**Comment by c-alpha** [comment]
Same thing here. Hence I was asking... 😉

**Comment by c-alpha** [comment]
Currently recompiling webkitgtk. Keep fingers crossed that it will have been worth the wait and solve the issue! :shipit:

**Comment by gauteh** [comment]
c-alpha writes on februar 6, 2018 17:44:
> Currently recompiling webkitgtk. Keep fingers crossed that it will have been worth the wait and solve the issue! :shipit:
> 

Is it possible to make binary packages with homebrew?

**Comment by c-alpha** [comment]
> Is it possible to make binary packages with homebrew?

Yes, it's called a [bottle](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md). When installing it, you are pouring a bottle. Language joke extravaganza... ;-)

**Comment by gauteh** [comment]
c-alpha writes on februar 6, 2018 18:59:
>> Is it possible to make binary packages with homebrew?
> 
> Yes, it's called a [bottle](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md). When installing it, you are pouring a bottle. Language joke extravaganza... ;-)

Heh, I think webkitgtk should be a candidate for that at least! I could 
host it if regular http is sufficient.

**Comment by c-alpha** [comment]
```
==> Installing astroidmail/astroid/webkitgtk@2.4.11
==> Downloading https://webkitgtk.org/releases/webkitgtk-2.4.11.tar.xz
######################################################################## 100.0%
==> Patching
patching file Source/JavaScriptCore/API/JSStringRef.cpp
patching file Source/JavaScriptCore/runtime/DateConversion.cpp
patching file Source/WebKit2/Shared/API/c/WKString.cpp
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/webkitgtk@2.4.11/2.4.11 --disable-introspection --disable-x11-target --enable-quartz-target --
==> make
==> make install
🍺  /usr/local/Cellar/webkitgtk@2.4.11/2.4.11: 305 files, 31.5MB, built in 280 minutes 12 seconds
```
Hooray! And it fixes the dynamic linker error for me!

Now looking into making a bottle.

**Comment by gauteh** [comment]
Yey!

**Comment by c-alpha** [comment]
> Now looking into making a bottle.

Done. PR is here: astroidmail/homebrew-astroid#21
