### ISSUE TITLE
Recommended way to remove astroid in documentation

### ISSUE THREAD

**Issue by kirschner** [astroidmail/astroid#465]
I am wondering what the recommended way is to remove astroid if you installed it with the instructions here: https://github.com/astroidmail/astroid/wiki/Compiling-and-Installing . I think that will be useful in case distribution packages are available and you want to switch to them. 

Any recommended way to make sure there is a clean remove of the manual installed files?

Thank you!

**Comment by gauteh** [comment]
Matthias Kirschner writes on februar 6, 2018 10:25:
> I am wondering what the recommended way is to remove astroid if you installed it with the instructions here: https://github.com/astroidmail/astroid/wiki/Compiling-and-Installing . I think that will be useful in case distribution packages are available and you want to switch to them. 
> 
> Any recommended way to make sure there is a clean remove of the manual installed files?

Hi, this is a general problem with manually compiled/installed software 
on nix and there is no easy fix! I find that the best is to:

* Use package manager of your distro
* Run software from source directory without installing
* Install to /usr/local along with everything else manually installed

Your only alternative now is to find all the files and delete them 
yourself.

**Comment by gauteh** [comment]
It seems that CMake / ninja / make creates a install_manifest.txt in the 
build directory when you do the install:

  https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall

it should contain a list of installed files, you can use this to `rm` 
the installed files.

**Comment by francesquini** [comment]
Actually there is a nice tool for that: GNU Stow: https://www.gnu.org/software/stow/

I've been using it for ages to install and uninstall source compiled/installed software.

**Comment by gauteh** [comment]
Emilio Francesquini writes on februar 6, 2018 13:26:
> Actually there is a nice tool for that: GNU Stow: https://www.gnu.org/software/stow/
> 
> I've been using it for ages to install and uninstall source compiled/installed software.

Good idea, I use stow for my dotfiles - but this is a pretty neat 
use-case! Would be great with an example of how to do that in the wiki.

**Comment by francesquini** [comment]
Actually there is not much to be said beyond what is already in README.md

Install:
```
$ git clone https://github.com/astroidmail/astroid.git
$ cd astroid
$ cmake -H. -Bbuild -GNinja -DCMAKE_INSTALL_PREFIX=/usr/local/stow/astroid
$ sudo cmake --build build --target install 
$ cd /usr/local/stow
$ sudo stow astroid
```
Uninstall:

```
$ cd /usr/local/stow
$ sudo stow -D astroid
$ sudo rm -fr astroid
```

**Comment by gauteh** [comment]
Emilio Francesquini writes on februar 6, 2018 14:00:
> Actually there is not much to be said beyond what is already in README.md
> 
> Install:
> ```
> $ sudo cmake --build build --target install 
> ```
> 

Nice, probably not necessary to build with root privs; so that step 
should be split into build and install.

**Comment by francesquini** [comment]
Yeah, you are right. I've updated my previous post to correct that...

**Comment by gauteh** [comment]
Added examples to wiki, thanks. https://github.com/astroidmail/astroid/wiki/Compiling-and-Installing
