### ISSUE TITLE
Colors for icons?

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#466]
Now that I've looked at the astroid icon for a while I am thinking whether it would perhaps be better with something lower-key? Maybe gray/black - or dark/gray-blue / gray. I think this might not stand so much out and fit better with a greater range of themes. Any thoughts?

(@hugoroy: ping)

**Comment by hugoroy** [comment]
It doesn't hurt to try :-)

I personnally like the resulet we have and I have no problems with the colours.

**Comment by mxmehl** [comment]
I also like the current colour set. However, it doesn't harm if we also had a white/grey version of the icon somewhere if someone prefers

**Comment by gauteh** [comment]
Alright :) Closing. If I get the time I'll play around with this..
