### ISSUE TITLE
Still segfaults with gmime3

### ISSUE THREAD

**Issue by norbusan** [astroidmail/astroid#469]
Dear all,
I am trying to compile astroid on a Debian/sid system with libgmime3-dev, but it still fails to start:
```
(gdb) bt
#0  0x00007f5b72a7fb17 in g_mime_parser_options_get_address_compliance_mode () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
#1  0x00007f5b72a9018f in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
#2  0x00007f5b72a91a4b in internet_address_list_parse () from /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0
#3  0x00007f5b7d3aad98 in ?? () from /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
#4  0x00007f5b7d3a7ab9 in notmuch_threads_get () from /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
#5  0x000055c4a8299328 in Astroid::QueryLoader::loader (this=0x55c4a9403560)
    at /home/norbert/Development/astroid/astroid/src/modes/thread_index/query_loader.cc:156
#6  0x000055c4a829c031 in std::__invoke_impl<void, void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>(std::__invoke_memfun_deref, void (Astroid::QueryLoader::*&&)(), Astroid::QueryLoader*&&) (
    __f=<unknown type in /usr/local/pkgs/astroid/bin/astroid, CU 0x9731ff, DIE 0x9b49ef>, 
    __t=<unknown type in /usr/local/pkgs/astroid/bin/astroid, CU 0x9731ff, DIE 0x9b49fd>) at /usr/include/c++/7/bits/invoke.h:73
#7  0x000055c4a829b747 in std::__invoke<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*>(void (Astroid::QueryLoader::*&&)(), Astroid::QueryLoader*&&) (__fn=<unknown type in /usr/local/pkgs/astroid/bin/astroid, CU 0x9731ff, DIE 0x9b7239>, 
    __args#0=<unknown type in /usr/local/pkgs/astroid/bin/astroid, CU 0x9731ff, DIE 0x9b7255>) at /usr/include/c++/7/bits/invoke.h:95
#8  0x000055c4a829e0b1 in std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> >::_M_invoke<0ul, 1ul> (this=0x55c4a96db688) at /usr/include/c++/7/thread:234
#9  0x000055c4a829e067 in std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> >::operator() (
    this=0x55c4a96db688) at /usr/include/c++/7/thread:243
#10 0x000055c4a829e046 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Astroid::QueryLoader::*)(), Astroid::QueryLoader*> > >::_M_run (this=0x55c4a96db680) at /usr/include/c++/7/thread:186
#11 0x00007f5b7369580f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f5b73faf51a in start_thread (arg=0x7f5b5a40f700) at pthread_create.c:465
#13 0x00007f5b72db83ef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

This is despite the fact that also notmuch is compiled against libgmime3:
```
[~] ldd /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
	linux-vdso.so.1 (0x00007ffc5b2e9000)
	libgmime-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0 (0x00007fa66ad52000)
...
```

Notmuch is properly initialized and I can run queries against it.

Best

Norbert

**Comment by norbusan** [comment]
Just to add one thing I forgot, I compiled from current git, in particular from commit ec9851436734ee34209b74da66c309cb6835a2f7

**Comment by gauteh** [comment]
Norbert Preining writes on februar 7, 2018 16:37:
> Just to add one thing I forgot, I compiled from current git, in particular from commit ec9851436734ee34209b74da66c309cb6835a2f7

Seems like notmuch is using an older version of gmime. See #464:

$ cmake -H. -Bbuild -GNinja -DUSE_GMIME_26=ON
$ cd build && ninja

**Comment by gauteh** [comment]
Can you check if you get a more sensible error with #470 ?

**Comment by gauteh** [comment]
Closing as duplicate.

**Comment by norbusan** [comment]
This is strange, as I mentioned above: asteroid is compiled against gmime3, and libnotmuch *also*:
```
[~] ldd /usr/lib/x86_64-linux-gnu/libnotmuch.so.5
	linux-vdso.so.1 (0x00007ffc5b2e9000)
	libgmime-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0 (0x00007fa66ad52000)
...
```
So I am bit surprised about that.

I will check the patch mentioned in #470, too.

**Comment by gauteh** [comment]
Oh Ok, see if patch works. What does ldd astroid say?

tor. 8. feb. 2018 kl. 01:23 skrev Norbert Preining <notifications@github.com

**Comment by norbusan** [comment]
Ahh, good hint.
```
[~] ldd astroid  | grep gmime
	libgmime-2.6.so.0 => /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0 (0x00007fa79efc7000)
	libgmime-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0 (0x00007fa79b206000)
```
So I checked with readeld
```
[~] readelf -d astroid  | grep gmime
 0x0000000000000001 (NEEDED)             Shared library: [libgmime-2.6.so.0]
```
Hmmmm, why on earth did that happen despite the fact that the cmake call detected gmime3.0?

I need to investigate.

**Comment by gauteh** [comment]
Norbert Preining writes on februar 8, 2018 9:51:
> Ahh, good hint.
> ```
> [~] ldd astroid  | grep gmime
> 	libgmime-2.6.so.0 => /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0 (0x00007fa79efc7000)
> 	libgmime-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmime-3.0.so.0 (0x00007fa79b206000)
> ```
> So I checked with readeld
> ```
> [~] readelf -d astroid  | grep gmime
>  0x0000000000000001 (NEEDED)             Shared library: [libgmime-2.6.so.0]
> ```
> Hmmmm, why on earth did that happen despite the fact that the cmake call detected gmime3.0?

That could have happened after you tried the USE_GMIME_26 flag, I 
suggested that when I thought notmuch was using 2.6.

**Comment by norbusan** [comment]
No I never tried that one... but I will recompile from clean state and check again for the cmake output. I'll come back to you later tonight (here in JST).

**Comment by norbusan** [comment]
Sorry, there must have been a left over during compilation, because after cleaning the git repo of all ignored files and recompiling it now works and is only linked against gmime3.

Sorry for the noise, closing this bug.

Thanks

**Comment by gauteh** [comment]
Norbert Preining writes on februar 8, 2018 10:21:
> Sorry, there must have been a left over during compilation, because after cleaning the git repo of all ignored files and recompiling it now works and is only linked against gmime3.
> 

Good stuff!
