### ISSUE TITLE
customize VTE fonts

### ISSUE THREAD

**Issue by mturquette** [astroidmail/astroid#477]
Maybe there is a way to do this already, but I have not found it after much searching. I'd love for the embedded VTE terminal emulator to use the same Ubuntu Mono derivative Powerline Regular font that iTerm uses. Any thoughts on how to customize it? Ideally this configuration could be surface up to `~/.config/astroid/config`

**Comment by gauteh** [comment]
Just fixed in master. Use [`terminal.font_description`](https://github.com/astroidmail/astroid/wiki/Configuration-Reference#terminalfont_description).

**Comment by gauteh** [comment]
Also just added `terminal.height` which might be of interest.

**Comment by mturquette** [comment]
Tested and works great for me. Thanks!
