### ISSUE TITLE
QUESTION: 'R' and 'r' same behavior?

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#486]
Hi,

`R: Reply to sender of current message` and `r: Reply to the current message` operate the same way in my environment; namely, they both compose a response with only the Sender in the recipient list.  Is this an issue with my configuration?

If the message to which I'm replying has the following headers set:

```
From: sender@senderdomain
To: me@mydomain
CC: other@otherdomain
```

then pressing either 'R' or 'r" will compose with these headers set:

```
From: me@maydomain
To: sender@senderdomain
CC:
```

I'd expect 'r' to produce:

```
From: me@mydomain
To: sender@senderdomain
CC: other@otherdomain
```

My compose configuration is:

```
    "editor": {
        "cmd": "gvim -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' '+set fo+=w' %1",
        "external_editor": "true",
        "charset": "utf-8",
        "save_draft_on_force_quit": "true",
        "attachment_words": "attach",
        "attachment_directory": "~",
        "markdown_processor": "marked"
    },
    "mail": {
        "reply": {
            "quote_line": "Excerpts from %1's message of %2:",
            "mailinglist_reply_to_sender": "true"
        },
        "forward": {
            "quote_line": "Forwarding %1's message of %2:",
            "disposition": "inline"
        },
        "sent_tags": "sent",
        "message_id_fqdn": "",
        "message_id_user": "",
        "user_agent": "default",
        "send_delay": "2"
    },
```

'M' is close, but puts all of the recipients into the To: header.

**Comment by gauteh** [comment]
Does `G` work for you? You might have to remove some extra. `R` always replies to sender, while `r` might reply to Reply-To specified address.

**Comment by serussell** [comment]
@gauteh, yes, both 'G' and 'R' do work, although both put all of the recipients into the "To:" field.

Is there a command that I can bind myself?  I want a command that moves From: to To: and leaves CC: populated as in the original email.

**Comment by gauteh** [comment]
`G` shouldn't put all recipients in To:, but put all previous Cc into the Cc field.
