### ISSUE TITLE
astroid crashes when it sees duplicate messages

### ISSUE THREAD

**Issue by rnav** [astroidmail/astroid#490]
Not quite sure if this is related to #425, but astroid crashes with the below messages:
```[11:18:12.849162] [0x00007f370eff9680] [debug] db: ro: waiting for lock to close..
[11:18:12.849173] [0x00007f370eff9680] [debug] db: ro: closing..

(astroid:27941): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: db: got more than one thread for thread id.

Trace/breakpoint trap (core dumped)
```

This happens when I try to open a thread that has multiple/duplicate messages (which happens since I am subscribed to a mailing list, while also pulling the messages from a nntp server). `notmuch search thread:<>` seems to show a single thread, but `--output=summary` confirms that all messages have a duplicate.

**Comment by gauteh** [comment]
Naveen N. Rao writes on april 6, 2018 8:24:
> Not quite sure if this is related to #425, but astroid crashes with the below messages:
> `[11:18:12.849162] [0x00007f370eff9680] [debug] db: ro: waiting for lock to close..
> [11:18:12.849173] [0x00007f370eff9680] [debug] db: ro: closing..
> 
> (astroid:27941): glibmm-ERROR **: 
> unhandled exception (type std::exception) in signal handler:
> what: db: got more than one thread for thread id.
> 
> Trace/breakpoint trap (core dumped)
> `
> 
> This happens when I try to open a thread that has multiple/duplicate messages (which happens since I am subscribed to a mailing list, while also pulling the messages from a nntp server). `notmuch search thread:<>` seems to show a single thread, but `--output=summary` confirms that all messages have a duplicate.
> 

That is weird. Is it consistent? I do not think this should be possible, 
but we should check with notmuch folks.

**Comment by rnav** [comment]
It consistently crashes if I try to access a specific thread. The latest notmuch has some changes for handling duplicate files. I wonder if something could be going wrong there.

From https://notmuchmail.org/news/:

> Indexing files with duplicate message-id
> 
> Files with duplicate message-id's are now indexed, and searchable via terms and phrases. There are known issues related to presentation of results and regular-expression search, but in principle no mail file should be completely unsearchable now.

**Comment by gauteh** [comment]
That could be - let me see if I can make a small test case.

Naveen N. Rao writes on april 6, 2018 9:30:

**Comment by rnav** [comment]
Hohum:

> $ notmuch search thread:00000000000c4d20
> thread:00000000000c4d1e  Yest. 17:54 [1/1(2)] <snip> (imap inbox)
> thread:00000000000c4d20  Yest. 16:56 [5/6(12)] <snip> (imap inbox ppcdev unread)

**Comment by gauteh** [comment]
Naveen N. Rao writes on april 6, 2018 10:04:
> Hohum:
> 
>> $ notmuch search thread:00000000000c4d20
>> thread:00000000000c4d1e  Yest. 17:54 [1/1(2)] <snip> (imap inbox)
>> thread:00000000000c4d20  Yest. 16:56 [5/6(12)] <snip> (imap inbox ppcdev unread)

Well, I guess that covers it! Would you mind submitting to notmuch@ ?

**Comment by gauteh** [comment]
[duplicate_thread_id.zip](https://github.com/astroidmail/astroid/files/1883184/duplicate_thread_id.zip)

Here's a test case:

Build with `./build.sh`
Run with: `./test_duplicate_thread_id path/to/db thread_id`

**Comment by rnav** [comment]
Posted to notmuch mailing list:
https://notmuchmail.org/pipermail/notmuch/2018/026381.html

**Comment by gauteh** [comment]
I think this is fixed in notmuch master.

**Comment by rnav** [comment]
Gaute Hope wrote:
> I think this is fixed in notmuch master.

I thought this hasn't yet been fixed. I don't see any commits in the 
main notmuch git tree that seem to be for this issue. Also, I only see 
the tests being commited on this git tree:
http://pivot.cs.unb.ca/git?p=notmuch.git;a=shortlog;h=refs/heads/fix/thread-search

**Comment by gauteh** [comment]
Alright, leaving open untill fixed in notmuch.

**Comment by gauteh** [comment]
Is this still an issue?

**Comment by rnav** [comment]
Gaute Hope wrote:
> Is this still an issue?

It is. I just bumped the notmuch thread hoping for a response.

**Comment by gauteh** [comment]
Any news on this one?

**Comment by rnav** [comment]
Gaute Hope wrote:
> Any news on this one?

I'm afraid not. Please go ahead and close this, as this is clearly an 
issue with notmuch. I will chase this issue there. Thanks.

**Comment by gauteh** [comment]
Alright, closing.

**Comment by igoralmeida** [comment]
I think I hit upon this by replying to a mailing list. Trying to reproduce, I noticed that when hitting `G` to reply-all, there was no In-Reply-To header in the editor. Should I have added that myself? Is this related to #173?

PS: sorry for bumping old/closed issues, I'm slowly migrating to astroid and searching for the errors I get.

**Comment by rnav** [comment]
In-Reply-To doesn't show up in your editor, but gets added by astroid. After closing your editor, if you hit 'V', you should see all the headers astroid adds.
