### ISSUE TITLE
astroid crashes if we invoke `thread_view.next_unread_thread` on a query that has no emails left

### ISSUE THREAD

**Issue by rnav** [astroidmail/astroid#491]
I have a startup query for some of my unread emails. When navigating through the emails using `thread_view.next_unread_thread`, if I try to navigate past the last unread email in that query (i.e., when there are no more emails left in the original query), astroid crashes with:

> [15:27:30.036564] [0x00007fbcb454fa00] [debug] db: ro: waiting for lock to close..
> [15:27:30.036585] [0x00007fbcb454fa00] [debug] db: ro: closing..
> [15:27:35.429479] [0x00007fbcb454fa00] [debug] tv: index action: 2
> 
> (astroid:23610): Gtk-CRITICAL **: gtk_tree_path_next: assertion 'path->depth > 0' failed
> 
> (astroid:23610): Gtk-CRITICAL **: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed

**Comment by gauteh** [comment]
Does #496 fix the issue?

**Comment by rnav** [comment]
Gaute Hope wrote:
> Does #496 fix the issue?

Thanks for looking into this. Just got around to testing this.

This change now stops moving to the next unread thread when there is one 
more thread left. So yes, it prevents the crash, but misses displaying 
the last unread email.

**Comment by gauteh** [comment]
Naveen N. Rao writes on May 12, 2018 12:41:
> Gaute Hope wrote:
>> Does #496 fix the issue?
> 
> Thanks for looking into this. Just got around to testing this.
> 
> This change now stops moving to the next unread thread when there is one 
> more thread left. So yes, it prevents the crash, but misses displaying 
> the last unread email.

Right, there's an off-by-one there. Could you test #498?

Regards,

**Comment by rnav** [comment]
Gaute Hope wrote:
> Naveen N. Rao writes on May 12, 2018 12:41:
>> Gaute Hope wrote:
>>> Does #496 fix the issue?
>> 
>> Thanks for looking into this. Just got around to testing this.
>> 
>> This change now stops moving to the next unread thread when there is one 
>> more thread left. So yes, it prevents the crash, but misses displaying 
>> the last unread email.
> 
> Right, there's an off-by-one there. Could you test #498?

That fixes it. Thanks.
