### ISSUE TITLE
Wiki issue

### ISSUE THREAD

**Issue by robguinness** [astroidmail/astroid#493]
On the wiki page https://github.com/astroidmail/astroid/wiki/Arch-Linux, I think here is an incorrect link. It says:

"Details how to add the Arch Linux CN repo to your pacman config can be found [here](https://aur.archlinux.org/packages/webkitgtk)." But that link has nothing to do with Arch Linux CN (it seems to me at least).

**Comment by gauteh** [comment]
Thanks - removed the link for now. If anyone has the correct one, feel free to add it.

**Comment by mxmehl** [comment]
When I added this link the pinned comment contained instructions on how to add the repo to the pacman config. But it doesn't seem to be on top anymore.
