### ISSUE TITLE
Sent mail not displayed : The message file is missing…

### ISSUE THREAD

**Issue by matclab** [astroidmail/astroid#505]
Every time I send a message from astroid (configured with `"save_sent_to" : "\/home\/matclab\/mail\/Sent\/cur"`), the message is sent, saved in the aforementioned directory. Notmuch find the message (when doing a search with subject or message id), but astroid shows `The message file is missing, only fields cached in the notmuch database are shown. Most likely your database is out of sync`. in the log and in the UI.

Have you any insight of what could be wrong ? Or on how to debug the problem further ?

Mail response of @gaute:
>If the folder is in your notmuch dB, astroid will add it to the database so that it will be immediately available before you run notmuch new. Have you tried to open the sent message before running notmuch new?
>
>This makes me believe that it is renamed by notmuch new (e.g. due to maildir flag synchronization?) - could this be the case. Still, if notmuch new has been run through the poll script (from astroid) the change should have been detected by astroid. There are more complex ways to tell astroid if there has been any changes described in the wiki if that is relevant to you.

**Comment by matclab** [comment]
Sending the mail, and doing a `notmuch new` before reading the mail leads to the same behavior.

However Trying to view the source of the message it displays:
```
Filename: /homecrypt/matclab/mail//home/matclab/mail/Sent/cur/1527532983.alnynmyzsj.astroid@loriot.none:2,
```
Where the existing file is : `/home/matclab/mail/Sent/cur/1527532983.alnynmyzsj.astroid@loriot.none:2,S`

**Comment by matclab** [comment]
The problem was due to `/home/matclab/mail` being a symbolic link to `/homecrypt/matclab/mail/`.

Modifying astroid configuration to use the path without symlink did the trick.

**Comment by matclab** [comment]
@gauteh I close this issue as I've a very simple workaround.
I can investigate a little bit more, but it would be nice if you can give me some tip about where to start looking on the codebase…

**Comment by gauteh** [comment]
Are you using the same dir (symlink or absolute) in both notmuch config and
astroid?



man. 28. mai 2018 kl. 21:32 skrev matclab <notifications@github.com>:

**Comment by gauteh** [comment]
The code for storing the sent message is in compose_message.cc, while the
code for adding the message to the dB should be in db.cc and possibly in
one of the actions/ files (to make the dB r/w action async). Possibly
there’s an issue with finding the file and adding tags, and getting the
updated file name because of the mismatch in the leading path.

man. 28. mai 2018 kl. 21:53 skrev Gaute Hope <eg@gaute.vetsj.com>:

**Comment by matclab** [comment]
There was indeed a mismatch between the notmuch and astroid configuration. notmuch was configured with the real path and astroid with the symlink.

**Comment by gauteh** [comment]
Perhaps if we had written an error/warning when you sent the message that
it is stored outside the notmuch database it would have been easier to
discover the cause of the problem. I think it shouldn’t be Astroids job to
resolve the path into the notmuch dB, but would be good with some
validation.

man. 28. mai 2018 kl. 22:40 skrev matclab <notifications@github.com>:
