### ISSUE TITLE
icon symlinks do not respect DESTDIR

### ISSUE THREAD

**Issue by Hello71** [astroidmail/astroid#514]
re #467, on Gentoo this results in the following error:

```
 * ACCESS DENIED:  symlink:      /usr/share/icons/hicolor/512x512/apps/astroid.png
failed to create symbolic link '/usr/share/icons/hicolor/512x512/apps/astroid.png': Permission denied
-- Symlinking: /usr/share/icons/hicolor/512x512/apps/astroid.png -> ../../../../astroid/ui/icons/icon_color.png
```

**Comment by gauteh** [comment]
Hi, I've noticed the same error on the archlinux PKGBUILD. Just replacing the relative path with a full path does not work. It seems that the install_symlink macro does not support DESTDIR. 

@c-alpha do you have any suggestions? this one is a bit critical.

**Comment by gauteh** [comment]
Does #515 fix the issue?

**Comment by c-alpha** [comment]
> Does #515 fix the issue?

Maybe. maybe not. Whether we install a symlink (as the stock `CMakeLists.txt`), or whether we install a copy (as #515 does), if permissions aren't so, it will fail either way.

**Comment by c-alpha** [comment]
@Hello71, could you please do an install with an **additional** `cmake` flag of `--trace-expand`, and post your command line and the output here?

_(Please be sure to not post a `--trace-expand` of the compile, but **of the install only**.)_

**Comment by gauteh** [comment]
Fixed in master.
