### ISSUE TITLE
thumbnails are not visible

### ISSUE THREAD

**Issue by apm256** [astroidmail/astroid#521]
Perhaps it is "normal" due to the port to Webkit2, but, just in case, there are no more thumbnails shown in case of image attachments.

**Comment by gauteh** [comment]
apm256 writes on July 9, 2018 14:27:
> Perhaps it is "normal" due to the port to Webkit2, but, just in case, there are no more thumbnails shown in case of image attachments.

No, they should be visible - they are here. Can you confirm this with 
with all e-mails with simple image attachments? Does it change if you 
hit C-i to allow remote images?

Do you have a screenshot? And if still not visible, please test latest 
master and inspect the source of the image using the web inspector.

**Comment by apm256** [comment]
Indeed, I can make them visible (but only with emails with html contents) with the following procedure:

1. C-i (thumbnails are not visible)
2. "Alternative part (type: text/html) - potentially sketchy" (thumbnails are now visible)
3. "Alternative part (type: text/plain)" (thumbnails are still visible)

Note that the problem is not restricted to images, but to all attachment formats, which exhibit no icons if I don't hit C-i before viewing the html part:

![astroif-attachments](https://user-images.githubusercontent.com/5927058/42455350-4ed6553a-8392-11e8-9082-c4aa3e95c39f.png)

**Comment by gauteh** [comment]
Hm, weird... is it the same without C-i as well? Could you send a minimal
log of what you need to do to get the images visible? Remember to capture
stdout, the webextension does not output to file.

man. 9. jul. 2018 kl. 16:12 skrev apm256 <notifications@github.com>:

**Comment by apm256** [comment]
In the meantime, I've tried on another machine (same distribution: Arch Linux) with the same results.
I'm unable to see attachments icons or image thumbnails without the above trick, by using C-i.

I've followed the above procedure and joined the relevant log to this post. When first viewing the message, the thumbnail is invisible, after C-i and hitting "Alternative part (type: text/html)", it is.

[astroid.log.gz](https://github.com/astroidmail/astroid/files/2179327/astroid.log.gz)

**Comment by gauteh** [comment]
apm256 writes on July 10, 2018 10:03:
> In the meantime, I've tried on another machine (same distribution: Arch Linux) with the same results.
> I'm unable to see attachments icons or image thumbnails without the above trick, by using C-i.
> 
> I've followed the above procedure and joined the relevant log to this post. When first viewing the message, the thumbnail is invisible, after C-i and hitting "Alternative part (type: text/html)", it is.
> 
> [astroid.log.gz](https://github.com/astroidmail/astroid/files/2179327/astroid.log.gz)
> 

Thanks,

I noticed that there is an error in the setup of webkit: is-ephemeral. 
What version of WebKit2 do you have?

Regards, Gaute

**Comment by apm256** [comment]
This one:
$ yaourt -Ss webkit2gtk
extra/webkit2gtk 2.20.3-1 [installed]
    GTK+ Web content engine library

**Comment by gauteh** [comment]
apm256 writes on July 10, 2018 14:17:
> This one:
> $ yaourt -Ss webkit2gtk
> extra/webkit2gtk 2.20.3-1 [installed]
>     GTK+ Web content engine library

Hm, weird - same as I have. Either way, I made some changes that might 
have an effect on this to master. Could you see if the issue persists?

**Comment by gauteh** [comment]
Gaute Hope writes on July 10, 2018 16:31:
> apm256 writes on July 10, 2018 14:17:
>> This one:
>> $ yaourt -Ss webkit2gtk
>> extra/webkit2gtk 2.20.3-1 [installed]
>>     GTK+ Web content engine library
> 
> Hm, weird - same as I have. Either way, I made some changes that might 
> have an effect on this to master. Could you see if the issue persists?

Do you have any custom theme files or plugins?

**Comment by apm256** [comment]
>  Could you see if the issue persists?

the issue persists :-(

> Do you have any custom theme files or plugins?

No custom theme and no plugin.

**Comment by gauteh** [comment]
apm256 writes on July 11, 2018 14:21:
>>  Could you see if the issue persists?
> 
> the issue persists :-(

Ok. Could you send me a full log? Does the same happen with a Debug 
build?

**Comment by gauteh** [comment]
Gaute Hope writes on July 11, 2018 15:15:
> apm256 writes on July 11, 2018 14:21:
>>>  Could you see if the issue persists?
>> 
>> the issue persists :-(
> 
> Ok. Could you send me a full log? Does the same happen with a Debug 
> build?

Think I figured it out. Was releated to Release build. Please try latest 
master.

**Comment by gauteh** [comment]
Great!
