### ISSUE TITLE
Message content is blank

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#527]
Hi everyone. I just tried out astroid 0.13 - the content of messages is blank :-) 
Here's what the shell gives:

```
** (WebKitWebProcess:7304): CRITICAL **: 16:56:55.317: void webkit_dom_element_set_inner_html(WebKitDOMElement*, const gchar*, GError**): assertion 'WEBKIT_DOM_IS_ELEMENT(self)' failed
```

**Comment by gauteh** [comment]
Hugo Roy writes on July 23, 2018 17:01:
> Hi everyone. I just tried out astroid 0.13 - the content of messages is blank :-) 
> Here's what the shell gives:
> 
> ```
> ** (WebKitWebProcess:7304): CRITICAL **: 16:56:55.317: void webkit_dom_element_set_inner_html(WebKitDOMElement*, const gchar*, GError**): assertion 'WEBKIT_DOM_IS_ELEMENT(self)' failed
> ```

Could you send a more detailed log leading to the warning? Also, try to 
see if there is more of a backtrace if you run through gdb?

I assume this happens with all messages?

What version of webkit do you have and do you have your own HTML/CSS theme 
files?

**Comment by hugoroy** [comment]
Yes, with all messages as far as I can tell.

Problem solved when not using my own HTML/CSS files! :-)

**Comment by gauteh** [comment]
Hugo Roy writes on July 24, 2018 12:36:
> Problem solved when not using my own HTML/CSS files! :-)
> 

Great :)

**Comment by mxmehl** [comment]
@hugoroy I think I had the same because of a custom CSS. IIRC, this is how I fixed it: https://src.mehl.mx/mxmehl/mail-config/commit/99d2bf712f0fd7776a1b932306082ba141670b6e
