### ISSUE TITLE
Multiple instances on different displays?

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#533]
Does Astroid *intentionally* ignore `DISPLAY`? 

I'm running an instance of Astroid on a computer; when I `ssh -X` in from another and run Astroid, I'd expect to get another instance of Astroid on the new X display (e.g., `localhost:10.0`, the X forwarding display).  Instead, Astroid opens a new window on the display of the existing instance.

Is there a way to force the `astroid` command to run a completely separate, new process rather than communicating commands to the existing instance?

**Comment by gauteh** [comment]
Closing, not a priority currently.
