### ISSUE TITLE
close_on _success closes active tab instead of sent mail tab

### ISSUE THREAD

**Issue by matclab** [astroidmail/astroid#535]
When `mail.close_on_success` is set, the current active tab is closed once the mail is sent. When `mail.send_delay` is also set, the user has the time to change the active tab to say `inbox` which is then unexpectedly closed.

I would have expect that the closed tab would be the one related to the mail being sent.

**Comment by gauteh** [comment]
matclab writes on August 20, 2018 12:24:
> When `mail.close_on_success` is set, the current active tab is closed once the mail is sent. When `mail.send_delay` is also set, the user has the time to change the active tab to say `inbox` which is then unexpectedly closed.
> 
> I would have expect that the closed tab would be the one related to the mail being sent.

Definitely!

**Comment by matclab** [comment]
Yes, just compiled and tested.
It works perfectly.

Thanks a lot for such a rapid response :clap: !

**Comment by gauteh** [comment]
matclab writes on August 20, 2018 14:35:
> Yes, just compiled and tested.
> It works perfectly.
> 
> Thanks a lot for such a rapid response :clap: !

Great, thanks :)
