### ISSUE TITLE
license file COPYING-CMAKE-SCRIPTS referenced in license grants is missing

### ISSUE THREAD

**Issue by jonassmedegaard** [astroidmail/astroid#539]
The files cmake/FindGObjectIntrospection.cmake and GObjectIntrospectionMacros.cmake contain the following license grant:

> Redistribution and use is allowed according to the terms of the BSD license.
> For details see the accompanying COPYING-CMAKE-SCRIPTS file.

That referenced file COPYING-CMAKE-SCRIPTS is missing, however.

**Comment by gauteh** [comment]
Jonas Smedegaard writes on August 24, 2018 14:48:
> The files cmake/FindGObjectIntrospection.cmake and GObjectIntrospectionMacros.cmake contain the following license grant:
> 
>> Redistribution and use is allowed according to the terms of the BSD license.
>> For details see the accompanying COPYING-CMAKE-SCRIPTS file.
> 
> That referenced file COPYING-CMAKE-SCRIPTS is missing, however.
> 

I moved the COPYING-CMAKE-SCRIPTS part to LICENSE.md in c1e212f3. We 
should point to that file instead.
