### ISSUE TITLE
testsuite fails building 0.13 officially for Debian

### ISSUE THREAD

**Issue by jonassmedegaard** [astroidmail/astroid#540]
Hi,

Not really sure how to isolate the individual issues of this, so I simply give up for now and report it as a whole:

Building release 0.13 for Debian fails its testsuite:

```
*** 5 failures are detected in the test module "TestCrypto"


71% tests passed, 5 tests failed out of 17

Total Test time (real) =   2.66 sec

The following tests FAILED:
	  1 - generic (Failed)
	  2 - compose (Failed)
	  3 - markdown (Failed)
	  9 - theme (Failed)
	 16 - crypto (Failed)
Errors while running CTest
```
Full buildlog e.g. for i386 is here: https://buildd.debian.org/status/fetch.php?pkg=astroidmail&arch=i386&ver=0.13-1&stamp=1535147012&raw=0

Builds for all architectures fail similarly (buildlogs are linked from the "installed" cells): https://buildd.debian.org/status/package.php?p=astroidmail&suite=experimental

**Comment by gauteh** [comment]
Hi,

seems like several issues here:

  * test plugins were using old GIR version, fixed in ec3cab68.

  * GNUPG fails to set up keys for test, this is probably the reason for 
    several of the failures. this is done in tests/run_test.sh:42, maybe 
    put in some debug echo output there to see if the paths are correct.

  * markdown fails because the `marked` binary / package is not 
    installed.

**Comment by gauteh** [comment]
Todo: use fixtures for boost to ensure proper setup / teardown: 

* https://www.boost.org/doc/libs/1_36_0/libs/test/doc/html/utf/user-guide/fixture/test-suite-shared.html
* https://stackoverflow.com/questions/8510256/boost-test-initialization-for-each-suite-not-case

**Comment by jonassmedegaard** [comment]
Thanks. GIR patch cherry-picked and marked installed during build, and indeed those specific errors are no more but oddly the summary of the testsuite still state that 5 areas failed: https://buildd.debian.org/status/package.php?p=astroidmail&suite=experimental

I would appreciate more details on how I might handle gnupg issues.  Or perhaps those tests could be made more verbose?

**Comment by gauteh** [comment]
Jonas Smedegaard writes on August 25, 2018 12:53:
> Thanks. GIR patch cherry-picked and marked installed during build, and indeed those specific errors are no more but oddly the summary of the testsuite still state that 5 areas failed: https://buildd.debian.org/status/package.php?p=astroidmail&suite=experimental
>
> I would appreciate more details on how I might handle gnupg issues.  Or perhaps those tests could be made more verbose?
>

The test suite is not properly set up, so the tests will always fail.
The issue is caused by the generation of the GPG keys in
`tests/run_test.sh`. From the log you sent me:

> /<<PKGBUILDDIR>>/obj-i686-linux-gnu/tests/test_home/gnupg /<<PKGBUILDDIR>>/obj-i686-linux-gnu/tests
> gpg: keybox '/<<PKGBUILDDIR>>/obj-i686-linux-gnu/tests/test_home/gnupg/pubring.kbx' created
> gpg: Generating a basic OpenPGP key
> gpg: agent_genkey failed: End of file
> gpg: key generation failed: End of file
> gpg: done

Maybe it helps to put in a `killall gpg-agent` or something at the
beginning of run_test.sh. Otherwise the gpg-agent might be stuck on the
gpg profile used by the build system (presumably to validate the
packages).

From the gpg error message it seems that the issue might be at reading
the `foo1.key` or `foo2.key`.

Regards, Gaute

**Comment by gauteh** [comment]
It seems that the tests are maybe run in parallel? This is not 
supported. Each test need exclusive access to the test mail db.

> /usr/bin/ctest --force-new-ctest-process -j4

**Comment by jonassmedegaard** [comment]
Bingo! Avoiding parallel mode for testsuite made it succeed.  Thanks a lot!

**Comment by gauteh** [comment]
Jonas Smedegaard writes on August 25, 2018 13:15:
> Bingo! Avoiding parallel mode for testsuite made it succeed.  Thanks a lot!
> 

Yey!
