### ISSUE TITLE
Please use cmark (not marked) by default

### ISSUE THREAD

**Issue by jonassmedegaard** [astroidmail/astroid#541]
The arkdown processor "marked" depend on Node.js which is a pretty heavy dependency for such a tiny little tool.

I recommend to instead by default use cmark - which is both very lightweight and uses the arguably most reliable of the Markdown flavors - CommonMark.

If cmark is disliked (for political reasons, perhaps?) then I recommend discount.

If neither of those, then the original Markdown parser in Perl.

(yes, I am aware that I can simply change the default for my own use, and for use with Debian where I maintain packaging of Astroid - and I will: This is to track the issue of doing similar in general)

 - Jonas

**Comment by gauteh** [comment]
Jonas Smedegaard writes on August 25, 2018 13:59:
> The arkdown processor "marked" depend on Node.js which is a pretty heavy dependency for such a tiny little tool.
> 
> I recommend to instead by default use cmark - which is both very lightweight and uses the arguably most reliable of the Markdown flavors - CommonMark.

Sounds good to me, always felt a bit weird about the 'marked' dep. Feel free to submit a PR.

**Comment by jonassmedegaard** [comment]
Sorry, I won't contribute code to Github, due to their arguably licensing-affecting terms of service.

**Comment by jonassmedegaard** [comment]
In a quick test, these all work with STDIN and STDOUT:
 * cmark
 * markdown
 * discount (executable markdown on Debian - conflicting with original markdown)
 * python-markdown (executable markdown_py on Debian)
 * pandoc
 * marked
 *

**Comment by gauteh** [comment]
Jonas Smedegaard writes on August 25, 2018 14:26:
> In a quick test, these all work with STDIN and STDOUT:
>  * cmark

Done.
