### ISSUE TITLE
Startup query although set blank

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#542]
I've upgraded to latest master but noticed that there's now a startup query with `tag:inbox` which I cannot close.

This is strange since I've neither set such in searches, and `config` has

```
    "startup": {
        "queries": ""
    }
```

What went wrong? Can someone reproduce?

**Comment by gauteh** [comment]
Max writes on August 27, 2018 17:47:
> I've upgraded to latest master but noticed that there's now a startup query with `tag:inbox` which I cannot close.
> 
> This is strange since I've neither set such in searches, and `config` has
> 
> ```
>     "startup": {
>         "queries": ""
>     }
> ```
> 
> What went wrong? Can someone reproduce?

Probably introduced in 68c66bb61004cc462e1e20cd09a4765a2c25772c.

**Comment by mxmehl** [comment]
I don't quite understand the code as I fail to see how the error emerged. My config didn't change by that, but for some reason the blank startup setting isn't respected. Even if I change startup.queries to another tag for example, I only see tag:inbox.

**Comment by gauteh** [comment]
Max writes on August 29, 2018 10:06:
> I don't quite understand the code as I fail to see how the error emerged. My config didn't change by that, but for some reason the blank startup setting isn't respected. Even if I change startup.queries to another tag for example, I only see tag:inbox.
> 

In that change the missing config is not written back. This means that 
you only need to define the config values that you change from the 
default. It also means that we can change the defaults and these will be 
updated on the user end (unless the specifically configured them).

Accounts and startup.queries are handled specially though. I didn't 
anticpiate that users don't want any queries at all (just the saved 
searches panel I guess?). And that this means that this section is not 
configured, and is replaced by the default which is `tag:inbox`.

**Comment by gauteh** [comment]
Please test #544.

**Comment by mxmehl** [comment]
#544 works for me, thanks!

**Comment by gauteh** [comment]
Max writes on August 30, 2018 8:39:
> #544 works for me, thanks!

Merged.
