### ISSUE TITLE
Include text/html using markdown and pandoc

### ISSUE THREAD

**Issue by dnebauer** [astroidmail/astroid#549]
Found a fascinating conversation on Hacker News about scripting mutt to include a html message in outgoing email, as well as plaintext, by writing emails in markdown and having pandoc convert it to standlone html prior to sending (see [here](https://news.ycombinator.com/item?id=12325767), and [here](https://news.ycombinator.com/item?id=12324506) for the full thread).

Is there any way for astroid users to do something similar using its current capabilities, i.e., without having to patch astroid itself?

**Comment by gauteh** [comment]
Check out markdown switch in composer 😉 requires cmark or similar. See
config if using custom processor.

søn. 9. sep. 2018 kl. 11:41 skrev dnebauer <notifications@github.com>:

**Comment by dnebauer** [comment]
Not sure what you mean by "markdown switch in composer" -- can you point me to anywhere with more information (wiki? github pages?). Does this switch, whatever it is, control whether an html part is included in outgoing messages?

By "See config if using custom processor" do you mean the `editor.markdown_processor` config option? I see from #541 that jonassmedegaard found that the markdown processors cmark, markdown, discount, python-markdown, pandoc, and marked all worked on quick testing. I'm not sure I get the relevance, however, as choice of markdown processor has no influence on whether an html part is included in outgoing messages (at least as far as I can see).

**Comment by gauteh** [comment]
See this issue: https://github.com/astroidmail/astroid/pull/430, is that what you mean?

You can write your e-mail as normal, but with markdown formatting. If you flip the Markdown switch on the e-mail will be written as two parts: the raw message as text/plain and a processed text/html part which has been piped through cmark (or the processor of your choice). Make sure you have it installed.

Note that there are some preview issues: https://github.com/astroidmail/astroid/issues/532

**Comment by dnebauer** [comment]
This feels like one of those conversations where everybody else knows something I don't. My new message window does not have a markdown switch:

![astroid_new_message](https://user-images.githubusercontent.com/1834722/45304183-b0a1aa80-b556-11e8-877e-682235435f20.png)

Here is the editor section of my config file:

```conf
    "editor": {
        "cmd": "gvim -geom 10x10 --servername %2 --socketid %3 -f '+set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' '+set fo+=w' '+/^To:/' '+startinsert!' %1",
        "external_editor": "false",
        "charset": "utf-8",
        "save_draft_on_force_quit": "true",
        "attachment_words": "attach",
        "attachment_directory": "~",
        "markdown_processor": "cmark"
    },
```

I've also tried marked and pandoc as markdown processors, with not effect. The processors cmark, marked and pandoc are all installed.

Is there some step I have to take to enable the markdown switch? Maybe this feature is available with editors other than gvim?

**Comment by gauteh** [comment]
It is only visible in the preview view, so either with external editor or
if you :wq vim. Note that you can always open grim again with enter.

man. 10. sep. 2018 kl. 16:45 skrev dnebauer <notifications@github.com>:

**Comment by dnebauer** [comment]
First, \*doh\*, I've sent hundreds of emails using astroid and can't believe I never noticed the Markdown and Signature switches on the preview window. Talk about inattentional blindness...

Second, \*sigh\*, that just leads to another problem. When I toggle the Markdown switch the html display is suppressed, with an "Alternative part (type: text/html) - potentially sketchy" widget appearing in its place:

![astroid_md-switch](https://user-images.githubusercontent.com/1834722/45334771-67377680-b5bb-11e8-8de9-6209307f263e.png)

This is the usual behaviour when displaying emails, and in those cases I can open the html part by moving focus to the "sketchy" widget with Ctrl-j and opening it by pressing Enter on my keyboard. When previewing an outbound email, I can jump to the "sketchy" widget with Ctrl-j as usual but the Enter key press is intercepted and used to open the email once again for editing. According to #19 it should be possible to open the "sketchy" widget with the 'o' key when it has focus, but in preview mode this has no effect (nor does pressing capital 'O').

I experimented with the `thread_view.preferred_type` and `thread_view.preferred_html_only` settings but they made no difference in preview mode. It also made no difference whether I used internal gvim or external gvim to edit emails.

Is there any way to open the html part in preview mode? (I'm sure it's ridiculously easy when you know the trick.)

Is there any way to ensure that html displays by default in preview mode?

I should add that I've checked the raw email using 'V' and the html part is present and correct.

**Comment by gauteh** [comment]
dnebauer writes on September 11, 2018 4:58:
> This is the usual behaviour when displaying emails, and in those cases I can open the html part by moving focus to the "sketchy" widget with Ctrl-j and opening it by pressing Enter on my keyboard. When previewing an outbound email, I can jump to the "sketchy" widget with Ctrl-j as usual but the Enter key press is intercepted and used to open the email once again for editing. According to #19 it should be possible to open the "sketchy" widget with the 'o' key when it has focus, but in preview mode this has no effect (nor does pressing capital 'O').

It should work with C+Space, but it does not seem to do so! This is a
bug. The normal ThreadView bindings work (though they don't show in the
help view - a bug), though they are shadowed by EditMode keybindings if
they conflict.

> I experimented with the `thread_view.preferred_type` and `thread_view.preferred_html_only` settings but they made no difference in preview mode.

You should be able to get HTML to always show, I think this is possible,
but there are some other issues with that: #532.

> It also made no difference whether I used internal gvim or external gvim to edit emails.

This should not make any difference. I mentioned it just because you
cannot see the Markdown-switch with internal gvim untill you close the
editor.

> Is there any way to open the html part in preview mode? (I'm sure it's ridiculously easy when you know the trick.)

This might be a bug --- for now you can probably save the message as
draft, and open the draft like a normal email and preview it.

> Is there any way to ensure that html displays by default in preview mode?

(covered above)

> I should add that I've checked the raw email using 'V' and the html part is present and correct.

Nice!

So there are a few things that need to be ironed out, the default HTML 
preview thing is actually a bit more complicated than it seems (#545), 
@yrashk had some ideas about how to fix it, but I am not sure if he's 
had the chance to look into it anymore yet.

**Comment by dnebauer** [comment]
Ctrl-Space opens the "sketchy" widget and opens the html part in EditMode on my current astroid! (Note that this is version 0.11.1):

![astroid_html-part](https://user-images.githubusercontent.com/1834722/45342120-1b48f980-b5dc-11e8-99c9-f969542487cf.png)

**Comment by dnebauer** [comment]
I should point out that the original issue reported here -- writing plain text emails in markdown and including an html part in the resulting email -- has been resolved.

The remaining problem is getting the html part to always display in the preview. It currently takes 5 key presses to show: M (Markdown switch), Ctrl-j (to move focus to "sketchy" widget) and Ctrl-Space (to open html part). That is annoying if you want to routinely preview html output, which I do. If I'm reading it correctly, though, #532 is addressing this problem so I'll subscribe to it and close this issue.

Thanks for your prompt replies throughout this issue and, as always, thanks for astroid.

**Comment by gauteh** [comment]
No worries 😊 should definitely fix #532. This should avoid having to push
any keys. If there is interest for it markdown switch default could also be
made configurable.


you could also experiment with simpler key bindings to get key count down.

tir. 11. sep. 2018 kl. 08:52 skrev dnebauer <notifications@github.com>:

**Comment by dnebauer** [comment]
Please add my vote to making it possible to configure the Markdown switch to be on by default.

**Comment by gauteh** [comment]
dnebauer writes on September 11, 2018 11:31:
> Please add my vote to making it possible to configure the Markdown switch to be on by default.

`editor.markdown_on` option added in master.
