### ISSUE TITLE
provide a list of default keybindings

### ISSUE THREAD

**Issue by teto** [astroidmail/astroid#553]
aka run get_keys.py on each release to install the keybindings names in the package or provide it in contrib/extra folder.
A copy could be uploaded on the wiki too !
https://github.com/astroidmail/astroid/wiki/Customizing-key-bindings

**Comment by gauteh** [comment]
Good suggestion, could probably be made part of the build.

**Comment by teto** [comment]
closing as duplicate of https://github.com/astroidmail/astroid/issues/323
