### ISSUE TITLE
message in bottom bar popup flashes then disappears

### ISSUE THREAD

**Issue by teto** [astroidmail/astroid#554]
When the bottom popup appears (very cool btw), the text appears during a subsecond then disappears (pretty reliably, I would advance 100% of the time here).

Using astroid 0.13.0 on www.nixos.org / i3wm. Dark gtk theme.

(edit I erased the main content for privacy)
![astroid_bug](https://user-images.githubusercontent.com/886074/46016887-035f9280-c111-11e8-8797-4a7136d5e288.png)

If I resize the window, it gets printed properly and stays as it should.

**Comment by gauteh** [comment]
Matthieu Coudron writes on September 26, 2018 9:20:
> I just noticed that the "From" also disappears. If blinks randomly if I move my mouse.

Inside the message view? That is generated by the webkit-component.. 
weird that you should have two fairly unrelated rendering issues. Do you 
notice similar things in other applications? Maybe especially ones that 
use animations of sort.

**Comment by teto** [comment]
> Inside the message view? 

On the screenshot, it would be left next to "Luke skywalker": "From" should be written there but it isn't.
I don't have any problem with other gtk based applications (just in libreoffice, some pictures don't render) but I think this is the only webkit app I use.

**Comment by teto** [comment]
Could this be a hint ?
```

** (WebKitWebProcess:24184): CRITICAL **: 16:17:20.042: gdouble webkit_dom_element_get_offset_top(WebKitDOMElement*): assertion 'WEBKIT_DOM_IS_ELEMENT(self)' failed

** (WebKitWebProcess:24184): CRITICAL **: 16:17:20.042: gdouble webkit_dom_element_get_client_height(WebKitDOMElement*): assertion 'WEBKIT_DOM_IS_ELEMENT(self)' failed

(WebKitWebProcess:24184): GLib-GObject-CRITICAL **: 16:17:20.042: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

** (WebKitWebProcess:24184): CRITICAL **: 16:17:20.207: gdouble webkit_dom_element_get_offset_top(WebKitDOMElement*): assertion 'WEBKIT_DOM_IS_ELEMENT(self)' failed

** (WebKitWebProcess:24184): CRITICAL **: 16:17:20.207: gdouble webkit_dom_element_get_client_height(WebKitDOMElement*): assertion 'WEBKIT_DOM_IS_ELEMENT(self)' failed

```

**Comment by gauteh** [comment]
So those two components are GTK and not webkit. Maybe a driver / rendering thing happening with GTK?

**Comment by teto** [comment]
As I get a similar problem in libreoffice, I will close this, as it doesn't seem astroid specific. 
If I ever find the root cause, I will post it here.
