### ISSUE TITLE
testsuite failures on some archs when building 0.13 (+ 7 patches) on Debian

### ISSUE THREAD

**Issue by jonassmedegaard** [astroidmail/astroid#556]
Hi,

I recently cherry-picked a few patches and rebuild Astroid for Debian, and it succeeds on arm64 and some other archs, but fails on others: https://buildd.debian.org/status/package.php?p=astroidmail&suite=sid

The patches applied are these: https://salsa.debian.org/debian/astroidmail/tree/master/debian/patches

If you don't want to be bothered with issues in a codebase deviating from your work, then I perfectly understand that.  Sharing in case you (like me) consider the deviation minor and find the revealed testsuite failures helpful.

**Comment by gauteh** [comment]
The tests are partly failing because of missing gpg-agent, did we 
discuss this issue already? Check the issue tracker. Seem to remember 
something about it with relation to packaging.

Does the same happen if you apply all patches (just to make sure that 
any fixes to the test-suite also were applied).

Regards, Gaute

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2018-09-26 15:08:28)
> The tests are partly failing because of missing gpg-agent, did we 
> discuss this issue already? Check the issue tracker. Seem to remember 
> something about it with relation to packaging.

You suggested missing gpg-agent being the cause in the past, yes.

I might in our conversation have acknowledged that, but then looked 
closer and confirmed that was not the case.

Also (as I recall different from my earlier testsuite failures) it fails 
only for _some_ architectures, not all: I am not convinced that your 
testsuite skips the need for properly setup gpg-agent on amd64 and 
armel, but not on armhf ;-)


> Does the same happen if you apply all patches (just to make sure that 
> any fixes to the test-suite also were applied).

I have not packaged HEAD of development, no.  That is not easy to do, so 
I would prefer not needing to do that.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on September 26, 2018 17:09:
> Quoting Gaute Hope (2018-09-26 15:08:28)
>> The tests are partly failing because of missing gpg-agent, did we 
>> discuss this issue already? Check the issue tracker. Seem to remember 
>> something about it with relation to packaging.
> 
> You suggested missing gpg-agent being the cause in the past, yes.
> 
> I might in our conversation have acknowledged that, but then looked 
> closer and confirmed that was not the case.
> 
> Also (as I recall different from my earlier testsuite failures) it fails 
> only for _some_ architectures, not all: I am not convinced that your 
> testsuite skips the need for properly setup gpg-agent on amd64 and 
> armel, but not on armhf ;-)

That seems unlikely I agree :) But not much debug output to go with 
there without access to a test system which can replicate the issue.

>> Does the same happen if you apply all patches (just to make sure that 
>> any fixes to the test-suite also were applied).
> 
> I have not packaged HEAD of development, no.  That is not easy to do, so 
> I would prefer not needing to do that.
> 

Ok, I think  I promised a release a while ago. Super-swamped for the 
next two weeks, but after that things will ease up. If not sooner, I 
will try to make a release then. It would be good to fix #550 before 
next release.

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2018-09-26 17:18:33)
> Jonas Smedegaard writes on September 26, 2018 17:09:
>> I am not convinced that your testsuite skips the need for properly 
>> setup gpg-agent on amd64 and armel, but not on armhf ;-)
>
> That seems unlikely I agree :) But not much debug output to go with 
> there without access to a test system which can replicate the issue.

Debian has a policy of verbose compilation output by default, so I would 
be happy to tweak that.

Can you help suggest some environment variables or configure options to 
set to make testsuite more verbose?


>>> Does the same happen if you apply all patches (just to make sure 
>>> that any fixes to the test-suite also were applied).
>>
>> I have not packaged HEAD of development, no.  That is not easy to do, 
>> so I would prefer not needing to do that.
>> 
>
> Ok, I think I promised a release a while ago. Super-swamped for the 
> next two weeks, but after that things will ease up. If not sooner, I 
> will try to make a release then. It would be good to fix #550 before 
> next release.

Ohh, I realize now that the Debian build seems affected by #550 too, so 
solving that would indeed be highly appreciated.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on September 26, 2018 17:45:
> Quoting Gaute Hope (2018-09-26 17:18:33)
>> Jonas Smedegaard writes on September 26, 2018 17:09:
>>> I am not convinced that your testsuite skips the need for properly 
>>> setup gpg-agent on amd64 and armel, but not on armhf ;-)
>>
>> That seems unlikely I agree :) But not much debug output to go with 
>> there without access to a test system which can replicate the issue.
> 
> Debian has a policy of verbose compilation output by default, so I would 
> be happy to tweak that.
> 
> Can you help suggest some environment variables or configure options to 
> set to make testsuite more verbose?

There was a patch related to run_test.sh, you could try appling that 
one. I don't see how test_theme fails. Weird that the files are not 
copied. Maybe ls the build/ui/* dir?

You can add the -v flag to the gpg AND gpgconf calls in run_test.sh. 
This might show some more info about why the files are not generated. 
Maybe the key files were also not copied.

>> Ok, I think I promised a release a while ago. Super-swamped for the 
>> next two weeks, but after that things will ease up. If not sooner, I 
>> will try to make a release then. It would be good to fix #550 before 
>> next release.
> 
> Ohh, I realize now that the Debian build seems affected by #550 too, so 
> solving that would indeed be highly appreciated.
> 

Should be fixed in #560.

**Comment by gauteh** [comment]
Gaute Hope writes on September 30, 2018 9:00:
> You can add the -v flag to the gpg AND gpgconf calls in run_test.sh. 
> This might show some more info about why the files are not generated. 
> Maybe the key files were also not copied.

I pushed a commit on master which makes GPG setup more verbose, you can 
add that one. I am getting more suspicious about whether all test files 
have been copied to the test dir successfully. Seems that that could 
explain the theme thing as well.

**Comment by gauteh** [comment]
Gaute Hope writes on September 30, 2018 9:00:
> There was a patch related to run_test.sh, you could try appling that 
> one. I don't see how test_theme fails. Weird that the files are not 
> copied. Maybe ls the build/ui/* dir?

See 33fc885209198cb0a8ccaa89fd706883e08288fa

**Comment by gauteh** [comment]
Just made a new release as well.

**Comment by gauteh** [comment]
Jonas Smedegaard writes on October 2, 2018 8:24:
> Unfortuinately it seems that [builds for 0.14](https://buildd.debian.org/status/package.php?p=astroidmail&ver=0.14-1) fail in same way as [builds for 0.13-3](https://buildd.debian.org/status/package.php?p=astroidmail&ver=0.13-3) did - but now with slightly more detail that perhaps you can help decipher, @gauteh.
> 
> 

Maybe the gpg-agent takes too long to start, try adding these lines:


```
diff --git a/tests/run_test.sh b/tests/run_test.sh
index 7370c5ea..a5becd1f 100755
--- a/tests/run_test.sh
+++ b/tests/run_test.sh
@@ -16,6 +16,7 @@ export GNUPGHOME="${BINDIR}/tests/test_home/gnupg"
 export ASTROID_BUILD_DIR="${BINDIR}"
 
 gpgconf -v --kill all # stop all components
+gpg-agent -v --daemon # re-start gpg-agent - fails if it has already been started. But ensures that the gpg-agent has already been started.
 
 if [ ! -e "${NOTMUCH_CONFIG}" ]; then
   echo "Setting up test suite.."
```

**Comment by gauteh** [comment]
Gaute Hope writes on October 2, 2018 9:39:
> Jonas Smedegaard writes on October 2, 2018 8:24:
>> Unfortuinately it seems that [builds for 0.14](https://buildd.debian.org/status/package.php?p=astroidmail&ver=0.14-1) fail in same way as [builds for 0.13-3](https://buildd.debian.org/status/package.php?p=astroidmail&ver=0.13-3) did - but now with slightly more detail that perhaps you can help decipher, @gauteh.
>> 
>> 
> 
> Maybe the gpg-agent takes too long to start, try adding these lines:

Also maybe you have mismatching versions of gpg-agent and gpg installed?

https://askubuntu.com/questions/860370/gpg-agent-cant-be-reached

**Comment by gauteh** [comment]
Closing, let me know if you have wish to investigate further.
