### ISSUE TITLE
fetaure request : allow to zoom on message list view

### ISSUE THREAD

**Issue by matclab** [astroidmail/astroid#559]
It would be usefull to allow user to dynamically change font size in the message list view like it is already possible in the thread view (with CTRL++ and CTRL+-).

Use case : I have a laptop with high density display (not huge, but still higher than my external screen) and when I have to work without the external screen, I'd like to be able to make the font size bigger in the message list view too.

**Comment by gauteh** [comment]
matclab writes on September 28, 2018 15:13:
> It would be usefull to allow user to dynamically change font size in the message list view like it is already possible in the thread view (with CTRL++ and CTRL+-).
> 
> Use case : I have a laptop with high density display (not huge, but still higher than my external screen) and when I have to work without the external screen, I'd like to be able to make the font size bigger in the message list view too.

You can do this statically by specifying the font. I do this by changing 
the system monospace font when I swap between Hi-dpi retina screen and 
external screen. Not possible with the font size yet, but shouldn't be 
too hard!

**Comment by gauteh** [comment]
Gaute Hope writes on September 28, 2018 16:39:
> matclab writes on September 28, 2018 15:13:
>> It would be usefull to allow user to dynamically change font size in the message list view like it is already possible in the thread view (with CTRL++ and CTRL+-).
>> 
>> Use case : I have a laptop with high density display (not huge, but still higher than my external screen) and when I have to work without the external screen, I'd like to be able to make the font size bigger in the message list view too.
> 
> You can do this statically by specifying the font. I do this by changing 
> the system monospace font when I swap between Hi-dpi retina screen and 
> external screen. Not possible with the font size yet, but shouldn't be 
> too hard!

(not possible dynamically yet, I meant)

We can also in theory hook into the system-monospace font config option 
and change our font whenever the setting is changed. Then an astroid 
restart would not be necessary.

**Comment by matclab** [comment]
Changing the font scale ratio (for example with gnome tweak tools, or with text scaler gnome extension on gnome desktop) also works well.

**Comment by gauteh** [comment]
Ok. Is this solved by changing desktop fonts?

fre. 12. okt. 2018 kl. 07:57 skrev matclab <notifications@github.com>:

**Comment by matclab** [comment]
Yep, I consider the original need of having bigger font in the message list solved.
I close the issue.

**Comment by gauteh** [comment]
Ok!
