### ISSUE TITLE
Allow dot in account name

### ISSUE THREAD

**Issue by varac** [astroidmail/astroid#563]
First of all, thx alot for astroid!

I started naming my first email account like the email addr associated with it but then found out that astroid doesn't like dots in the account name. It won't recognize this account when composing a mail (`To:`) is empty in the editor.

Allowing dots in the account name would allow using an email adr as account name, which is pretty natural to me.

**Comment by gauteh** [comment]
Varac writes on October 2, 2018 22:42:
> First of all, thx alot for astroid!
> 
> I started naming my first email account like the email addr associated with it but then found out that astroid doesn't like dots in the account name. It won't recognize this account when composing a mail (`To:`) is empty in the editor.
> 
> Allowing dots in the account name would allow using an email adr as account name, which is pretty natural to me.

Thanks, I think this is a limitation in the JSON format used for the 
config file. So unfortunately I don't think it is worth changing the 
format for fixing this.
