### ISSUE TITLE
more packages required to compile on Fedora

### ISSUE THREAD

**Issue by bingoUV** [astroidmail/astroid#568]
On Fedora (28), I needed to install these extra packages in addition to the ones recommended on the Fedora install guide in 
- ninja-build
- vte291-devel
- scdoc

Please add them to the recommended list of packages if it makes sense

**Comment by gauteh** [comment]
Klozuht writes on October 5, 2018 6:58:
> On Fedora (28), I needed to install these extra packages in addition to the ones recommended on the Fedora install guide in 
> - ninja-build
> - vte291-devel
> - scdoc

Hi, please add them to the wiki. These pages are maintained by users of 
the various distributions. As a side note, these dependencies are 
optional (you can use Makefiles in stead of ninja).

**Comment by bingoUV** [comment]
Added to wiki. Thanks
