### ISSUE TITLE
Ctrl-Space not activating Alternative Part widget in preview view (v0.14)

### ISSUE THREAD

**Issue by dnebauer** [astroidmail/astroid#584]
In version 0.14 `Ctrl-Space` no longer activates the `Alternative part` widget when previewing in Edit Mode. The `Enter` key, which in other modes activates the widget, in Edit Mode opens the message for (re-)editing.

`Ctrl-Space` worked fine for activating the widget in Edit Mode back in 0.11.1 -- see, for example, [this comment](https://github.com/astroidmail/astroid/issues/549#issuecomment-420130049) and following comments.

**Comment by gauteh** [comment]
dnebauer writes on October 23, 2018 13:59:
> In version 0.14 `Ctrl-Space` no longer activates the `Alternative part` widget when previewing in Edit Mode. The `Enter` key, which in other modes activates the widget, in Edit Mode opens the message for (re-)editing.

For some reason some Ctrl-keybindings do not work in hte ThreadView when 
in EditMode. If you change it to a simpler key, like just 'o' it starts 
working again.

**Comment by dnebauer** [comment]
I can't locate the default keybinding for `Ctrl-Space` in the output of `devel/get_keys.py`. What is the target for activating the `Alternative part` when it has focus?

**Comment by gauteh** [comment]
https://github.com/astroidmail/astroid/blob/master/src/modes/thread_view/thread_view.cc#L658

**Comment by gauteh** [comment]
```
thread_view.activate=Enter
thread_view.activate=o
```

note that `o` is already used to open search, so its not a good default choice.
