### ISSUE TITLE
Markdown part with incomplete text at the end

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#585]
Hi,

I have the following bug, to reproduce:

1. Write an email in plain text
2. In preview, activate Markdown
3. Send / Preview the html part of the email
4. Notice the end of the email: it stops somewhere before the end of the plain text email, leaving out part of the end

Am I the only one able to produce this bug?

**Comment by gauteh** [comment]
Hugo Roy writes on October 24, 2018 16:15:
> Hi,
> 
> I have the following bug, to reproduce:
> 
> 1. Write an email in plain text
> 2. In preview, activate Markdown
> 3. Send / Preview the html part of the email
> 4. Notice the end of the email: it stops somewhere before the end of the plain text email, leaving out part of the end
> 
> Am I the only one able to produce this bug?

What markdown processor are you using and what version are you on? Do 
you get a different result from the sent and previewed version?

**Comment by gauteh** [comment]
Hi Hugo, I need some more info on this one. Are you using any plugins?

**Comment by hugoroy** [comment]
Hi Gaute,

Yes, sure no problem :)

I'm not using any plugin that I know of. The plugin directory is empty.

Best,
Hugo

**Comment by gauteh** [comment]
What markdown processor are you using and what version are you on? Do you get a different result from the sent and previewed version?

**Comment by hugoroy** [comment]
↪ Gaute Hope / 2018-10-29, 19:46 (CET):
> What markdown processor are you using and what version are you on?

My config tells me it's marked (v 0.5.1). But I don't think that's particularly intentional. Could that be an old thing?

> Do you get a different result from the sent and previewed version?

No, the previewed version has the same problem.

**Comment by gauteh** [comment]
Hugo Roy writes on October 29, 2018 20:05:
> ↪ Gaute Hope / 2018-10-29, 19:46 (CET):
>> What markdown processor are you using and what version are you on?
> 
> My config tells me it's marked (v 0.5.1). But I don't think that's particularly intentional. Could that be an old thing?

Yes, should be cmark now (by default). You can just remove the config 
option and it will use the default.

**Comment by hugoroy** [comment]
↪ Gaute Hope / 2018-10-29, 20:08 (CET):
> Yes, should be cmark now (by default). You can just remove the config 
> option and it will use the default.

Perfect! I guess that should probably solve it :^)

let me try with this email!

**Comment by hugoroy** [comment]
It seems that the problem still happens. I will investigate further.

**Comment by gauteh** [comment]
Do you have some example input where this issue happens?

**Comment by Radvendii** [comment]
This was happening to me sometimes too, and of course now that I'm trying to reproduce it I can't. Next time it happens I'll post it here.

**Comment by jorsn** [comment]
I can reproduce it with pandoc and rather long mails. There is also a warning:

> invalid cast from 'GMimeMultipart' to 'GMimePart'

**Comment by gauteh** [comment]
Please supply some example input and exact steps to reproduce. Would be great to figure out what is going on here.

**Comment by jorsn** [comment]
> Would be great to figure out what is going on here.

Wide UTF-8 characters were treated as one byte.
