### ISSUE TITLE
Attachments can't be viewed when composing message

### ISSUE THREAD

**Issue by larskotthoff** [astroidmail/astroid#586]
When attaching things while composing a message, the attachments show up and can be selected as usual. However, when pressing <Enter> to open them, the editor launches as the key binding for that is the same.

**Comment by gauteh** [comment]
Lars Kotthoff writes on October 26, 2018 21:07:
> When attaching things while composing a message, the attachments show up and can be selected as usual. However, when pressing <Enter> to open them, the editor launches as the key binding for that is the same.

I think this is actually a duplicate of #584. Ctrl-space used to be an 
alternative keybinding. But somehow it stopped working during the 
migration to webkit2 (maybe webkit swallows it?). If you add an 
simple keybinding to that target (`thread_view.activate`), e.g.: `o`, 
you should be able to use that to open attachments and also open 
alternative parts.

**Comment by larskotthoff** [comment]
Ok, thanks. Another alternative would be to check whether an attachment is focused when enter is pressed; or allow to open it by mouse click.

**Comment by gauteh** [comment]
True, but I think it would be better to maybe change the keybinding for editing. Lets move the rest of the discussion to #584.
