### ISSUE TITLE
Sent messages saved in "Sent Items" even if different path configured

### ISSUE THREAD

**Issue by larskotthoff** [astroidmail/astroid#590]
I noticed that I'm getting copies of all the messages I've sent in my offlineimap's "Sent Items" folder in addition to the folder that I've configured sent messages to be saved to, i.e. there's 2 copies of each sent message.

I'm not 100% sure that astroid is causing this, but it didn't happen before I switched to offlineimap + notmuch + astroid + mstmp and none of the others seems to do this.

**Comment by gauteh** [comment]
Often the email provider will save a copy on send. In that case it will pop
up on the next offlineimap run. You can test by sending a message with
offlineimap/polling turned off temporarily. Then check in webmail or see if
it pops up after the next offlineimap run.

**Comment by larskotthoff** [comment]
Thanks, I'll try that. I don't think that it's that though as this didn't happen with another email client.

**Comment by larskotthoff** [comment]
Ok, turns out that this is the server putting the messages there (even though it didn't before). Nothing to do with astroid -- sorry for the noise!
