### ISSUE TITLE
Switch forwarding disposition inside astroid

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#594]
Currently, if you want to configure how astroid handles forwarded emails – inline or as attachment – you have to configure `mail.forward.disposition` [link](https://github.com/astroidmail/astroid/wiki/Configuration-Reference#mailforwarddisposition) in astroid's config.

Can we make that configurable inside astroid, e.g. like we do it with the target clipboard using `"`, but use the configured setting as default? Alternatively, a second keybinding could work, e.g. `F` instead of `f`.

For example, I mostly use attachment, but sometimes an inline would make more sense.

**Comment by gauteh** [comment]
You can use the unbound targets to bind directly to each different behavior:

# thread view
thread_view.forward_inline=f
thread_view.forward_attached=M-f

# thread index
thread_index.forward_inline=f
thread_index.forward_attached=M-f

**Comment by gauteh** [comment]
Also, you always attach by Mid after starting to edit.

**Comment by mxmehl** [comment]
Ah thanks, didn't know there were keybindings for that!
