### ISSUE TITLE
Possibility of providing a cygwin package

### ISSUE THREAD

**Issue by krishnakumarg1984** [astroidmail/astroid#602]
I absolutely love Astroid. Unfortunately in my current corporate setting, I am not given admin access and is forced to use a windows 10 laptop.

I am currently using all my favourite `*nix` tools provided by the portable version of [`mobaxterm`](https://mobaxterm.mobatek.net/) . It consists of its own package manager `MobApt` which essentially is a wrapper around the `apt-cyg` script. 

Is there a way you could support a `cygwin` build of `astroid`? This will be a huge quality improvement to my (work) life.

**Comment by gauteh** [comment]
Hi, nice to hear. I haven't tried building on Cygwin, but in principle
there shouldn't be anything stopping you. In practice though, probably! I
noticed for instance that the notmuch dependency is not available at
cygwin.com yet.

**Comment by gauteh** [comment]
I personally do not have the time to support a cygwin package. I will therefore have to close this.
