### ISSUE TITLE
astroid.desktop doesn't work with mailto: links

### ISSUE THREAD

**Issue by larskotthoff** [astroidmail/astroid#608]
When setting astroid.desktop as the default handler for mailto: links, astroid opens, but without composing a new message. This is because astroid expects the email address to be passed to the --mailto flag, but this argument isn't present in the .desktop file. Adding it there breaks the "normal" way of opening astroid.

Possible fix: if only a single positional argument is given to astroid, treat it as a mailto: link and handle accordingly.

Related to #11.

**Comment by larskotthoff** [comment]
I had a go at that, but couldn't figure out how to process positional arguments in boost and with the arguments being parsed twice. Might have another look when I get a chance.

**Comment by gauteh** [comment]
Yeah, it is a bit sub-optimal. I think in newer Gtk4 the argument parsing
will be different anyway. The weird setup stems from supporting arguments
when you run the astroid command when there already is an instance running.
