### ISSUE TITLE
Search for key binding

### ISSUE THREAD

**Issue by matclab** [astroidmail/astroid#611]
The help pane is very useful, but it sometime difficult to find the wanted key binding.

It would be very useful to be able to search the pane for any text.

**Comment by mxmehl** [comment]
Duplicate of #208?

**Comment by gauteh** [comment]
Yes.

lør. 8. des. 2018 kl. 16:52 skrev Max <notifications@github.com>:

**Comment by matclab** [comment]
Closed as duplicate. Thanks @mxmehl, I have overlooked it.
