### ISSUE TITLE
Feature request: Programatically create list of startup queries

### ISSUE THREAD

**Issue by glacambre** [astroidmail/astroid#614]
Hi! First, I want to thank you for working on astroid, it's the email client I've been dreaming of for the last three years but never actually tried to implement, I'm really happy I found it :)

I'd like to be able to programmatically create a list of startup queries. I do this in neomutt by using back-quotes in order to generate one query per tag and also a query containing all messages that do not have a tag. I couldn't find a way to do that by reading the manual so I assume it's not possible.

Would you be open to such a feature? If yes, how would you implement it and how hard would it be?

**Comment by gauteh** [comment]
Absolutely, I think the best way to do that would be through plugins.

**Comment by glacambre** [comment]
Ok, these are the conclusions I came to after taking a brief look at the code:
- The plugin can be a simple AstroidActivatable
- It needs access to the MainWindow, a good place to put a reference to it could be `struct _AstroidActivatableInterface` in astroid_activatable.h
- In its do_activate function, it should add a ThreadIndex per startup query to the main window using the add_mode function

Is this correct? If yes, how can I expose the ThreadIndex constructor to the python plugin? I never wrote C++ or python code and I have no idea how the C++/python interop works aside from translating datastructures to the right format and putting arguments in the right registers before performing a call.

**Comment by gauteh** [comment]
Maybe the easiset is to hook into startup-queries in mainwindow.cc
(astroid.cc). And just replace the config file list with the plugin method.
If there is no plugin, then use the configured startup queries. Then all
you have to do is return a list of tuples (title, query). You could then
write a plugin to load all the notmuch tags for example and build the list
from that.
