### ISSUE TITLE
Message content is missing when saved draft reopened

### ISSUE THREAD

**Issue by dnebauer** [astroidmail/astroid#616]
When I save a draft and reopen it, the reopened draft has no message content, as indicated by the "Message content is missing" message:

![html-email-forwarded-draft](https://user-images.githubusercontent.com/1834722/50393578-b6866900-079e-11e9-8f36-6ef75d0453f4.jpg)

Steps to reproduce:

1. Create message using inline gvim
2. In Edit Mode tab press `s` to save as draft (and message tab closes)
3. Search for saved draft using term `tag:draft`
4. Open draft message for editing by selecting it and pressing `Enter` key

Astroid reports it is version 0.14.

Issue #527 does not appear to be about the same problem.

**Comment by gauteh** [comment]
Do you save the draft to a maildir which is managed by eg offlineimap? If
the imap syncing tool renames the message, and the dB is not updated
(notmuch new), astroid won’t find the message content.

man. 24. des. 2018 kl. 08:45 skrev dnebauer <notifications@github.com>:

**Comment by dnebauer** [comment]
I do use offlineimap. In these cases, however, the message is saved to draft and reopened in between polls, which is when offlineimap is called. The only notmuch hooks defined are for pre- and post-new, so they can't be having any effect. I just don't see how other mail tools could be involved here. Happy to keep troubleshooting if there are other possibilities.

**Comment by gauteh** [comment]
Is the save draft folder outside your notmuch dB directory?

tir. 25. des. 2018 kl. 10:03 skrev dnebauer <notifications@github.com>:

**Comment by gauteh** [comment]
If you do a refresh or restart if astroid does that fix the missing
content? What if you do a notmuch new inbetween? Make sure your poll script
does not run. Offlineimap may change the maildirflags, which is part of the
file name. That is the most frequent cause of this issue.

tir. 25. des. 2018 kl. 10:28 skrev dnebauer <notifications@github.com>:

**Comment by gauteh** [comment]
Did you have the chance to investigate further? Need more info or will close.

**Comment by igoralmeida** [comment]
Same problem. In my case, the drafts folder is indeed outside the notmuch database. Is that not allowed?

**Comment by gauteh** [comment]
Not if you want it to be shown in astroid, then it has to be in your
notmuch database.

fre. 17. mai 2019 kl. 03:04 skrev Igor Almeida <notifications@github.com>:
