### ISSUE TITLE
Cannot delete draft with D key

### ISSUE THREAD

**Issue by dnebauer** [astroidmail/astroid#617]
If I open a draft message the display states it can be edited with `E` and deleted with `D`:

![html-email-forwarded-draft](https://user-images.githubusercontent.com/1834722/50393800-47117900-07a0-11e9-835b-ff55e97a1e02.jpg)

\[_The fact that the draft contains no content is a separate problem reported as #616._\]

Pressing `E` does, in fact, open it for editing. Pressing `D`, however, has no visible effect. The help displayed by pressing `?` shows, in part:

![thread-view-help](https://user-images.githubusercontent.com/1834722/50393933-0fef9780-07a1-11e9-8773-16a0da16e59b.jpg)

\[_The odd lines in the title bar are an artefact of the screen grabber. The fading of the astroid window is an new effect my desktop has started doing when a window loses focus, and I haven't yet figured out how to turn it off._\]

According to this help, `D` will "Delete currently focused draft".

I am not aware of any configuration setting that could alter this behaviour, and can see nothing in my config or keybindings files that could affect it.

**Comment by gauteh** [comment]
Need some more information, will re-open if turns out to be separate issue.
