### ISSUE TITLE
QUESTION: How to expand HTML part of newly composed email?

### ISSUE THREAD

**Issue by serussell** [astroidmail/astroid#618]
I'm trying to preview the HTML version (from Markedown) of my composed emails, and can't figure out how to expand the focused (HTML) part when in Reply mode.  In Reply mode, Enter triggers Edit, C-Space isn't bound, Help doesn't list a binding for expand(), mouse-click doesn't expand it, and I can't find the magic configuration option to set up my own keybinding.

Other people's comments make it obvious that they're able to do this, so I'm sure I'm just being stupid.

**Comment by gauteh** [comment]
The problem is related to the default keybinding not working for some reason, see #584. A work around is to redefine it to some other working key for now.

So not your fault!
