### ISSUE TITLE
any plan to get into gsoc ?

### ISSUE THREAD

**Issue by teto** [astroidmail/astroid#620]
aka google summer of code : https://developers.google.com/open-source/gsoc/timeline

I feel like there is no great GUI MUA on linux apart from thunderbird (whose future I am very worried about) and astroid has a nice angle with the notmuch capability. I feel like it could be a good candidate for 1 or 2 students depending on mentor availibility

**Comment by gauteh** [comment]
Absolutely, my previous experience with GSOC (on sup) was that many tasks where rudimentary implemented, but there was no interest to clean them up or respond to review (and in the end few of them could be merged). But we might be able to specify that a bit more. I'd be able to mentor, would be great if someone else also had the chance.

I think that making the install of astroid and the rest of the notmuch infrastructure would be pretty critical to making astroid a more general mail client. As well as better mouse-support.

**Comment by teto** [comment]
> I think that making the install of astroid and the rest of the notmuch infrastructure would be pretty critical to making astroid a more general mail client

This kind of "infrastructure" task is actively discouraged by google.

> As well as better mouse-support.

This. I do appreciate keyboard+shell but have neomutt/alot configured for that while for longer sessions, similar to web browsing, it's sometimes nice to sit back and click on a fancy UI.

**Comment by gauteh** [comment]
Ok, that's fine, there's more than enough to pick from!

**Comment by mxmehl** [comment]
That would be great! I also think there are many issues that would qualify as interesting projects for students.

Can the non-coding part of the community help somehow to make this happen?

**Comment by gauteh** [comment]
It would be very useful to help compile a list of functionality, refactors,
or priority grievances (previewing html mail?) that is needed. Anyone want
to take charge? I’ll be able to help on the technical side on complexity,
dependencies and my view on priority of tasks.

What format or what is needed to get into gsoc? Either way I don’t think
the effort will be wasted. We’re overdue for a roadmap.



lør. 19. jan. 2019 kl. 13:46 skrev Max <notifications@github.com>:

**Comment by mxmehl** [comment]
> It would be very useful to help compile a list of functionality, refactors, or priority grievances (previewing html mail?) that is needed. Anyone want to take charge?

I think I'd be able to collect some hurdles for better (less-techy) user experience, like mouse support, handling of encrypted mails, attachment selection, html view/reply, in-app search for help... But as someone using astroid solely for large amounts of business mails in a tech-savvy environment, I might be biased, so a complementary view would be helpful.

Where would be a good place to collect these items? In the wiki perhaps?

**Comment by gauteh** [comment]
Yes, or maybe githubs project thing can be used?

lør. 19. jan. 2019 kl. 14:32 skrev Max <notifications@github.com>:

**Comment by teto** [comment]
Neovim was selected last year with this kind of page https://github.com/neovim/neovim/wiki/GSoC which I like: simple and straightforward.
Would be great to have 2 mentors to ask for at least 2 students (though with 315 stars only, I believe we can hope for one student at most). If there is any student contributing to astroid, that would be great to ask him if he is interested. 
The gsoc website needs some filling like why the application ?

**Comment by gauteh** [comment]
Ok! Then wiki is good. I can be mentor.

lør. 19. jan. 2019 kl. 16:37 skrev Matthieu Coudron <
notifications@github.com>:

**Comment by teto** [comment]
I guess deadline is past xD
