### ISSUE TITLE
Ambiguous parameters used for ronn 0.8.x in CMakeLists.txt

### ISSUE THREAD

**Issue by hosiet** [astroidmail/astroid#627]
When building this package under Debian 10, the following error will happen:

https://github.com/astroidmail/astroid/blob/master/CMakeLists.txt#L416

```
% ronn -rp ./doc/astroid.1.scd | gzip > ./astroid.1.gz      

ronn: ambiguous option: -p
     roff: ./doc/astroid.1.scd.1

% ronn --version
Ronn-NG v0.8.0
http://github.com/apjanke/ronn-ng/tree/0.8.0
```

The `-p` option is not compatible with ronn provided by ronn-ng project. Please consider using the long option (`--pipe --roff`) for better compatibility.

Thanks!

**Comment by gauteh** [comment]
Thanks, fixed.
