### ISSUE TITLE
Markdown ctest failure

### ISSUE THREAD

**Issue by arael** [astroidmail/astroid#628]
I have issues with the markdown.
This is what I get when I run ctest.
Please let me know how to provide more info.

I am using Ubuntu 18.10.

`
Test project /archive/software/utility/astroid/build
      Start  1: generic
 1/17 Test  #1: generic ..........................   Passed    0.20 sec
      Start  2: compose
 2/17 Test  #2: compose ..........................   Passed    1.23 sec
      Start  3: markdown
 3/17 Test  #3: markdown .........................***Failed    0.32 sec
      Start  4: non_existant
 4/17 Test  #4: non_existant .....................   Passed    0.59 sec
      Start  5: open_db
 5/17 Test  #5: open_db ..........................   Passed    0.20 sec
      Start  6: convert_error
 6/17 Test  #6: convert_error ....................   Passed    0.19 sec
      Start  7: no_newline
 7/17 Test  #7: no_newline .......................   Passed    0.19 sec
      Start  8: mime_message
 8/17 Test  #8: mime_message .....................   Passed    0.24 sec
      Start  9: theme
 9/17 Test  #9: theme ............................   Passed    0.20 sec
      Start 10: keybindings
10/17 Test #10: keybindings ......................   Passed    0.19 sec
      Start 11: bad_content_id
11/17 Test #11: bad_content_id ...................   Passed    0.30 sec
      Start 12: notmuch
12/17 Test #12: notmuch ..........................   Passed    0.06 sec
      Start 13: notmuch_standalone
13/17 Test #13: notmuch_standalone ...............   Passed    0.23 sec
      Start 14: address
14/17 Test #14: address ..........................   Passed    0.20 sec
      Start 15: dates
15/17 Test #15: dates ............................   Passed    0.19 sec
      Start 16: crypto
16/17 Test #16: crypto ...........................   Passed    3.00 sec
      Start 17: gmime_version
17/17 Test #17: gmime_version ....................   Passed    0.01 sec

94% tests passed, 1 tests failed out of 17

Total Test time (real) =   7.56 sec

The following tests FAILED:
	  3 - markdown (Failed)
Errors while running CTest
`

**Comment by gauteh** [comment]
Do you have cmark installed?

tir. 16. apr. 2019 kl. 11:04 skrev arael <notifications@github.com>:

**Comment by arael** [comment]
Indeed that was the issue. Thank you very much for support and for this awesome client.

**Comment by gauteh** [comment]
Thanks 😁

tir. 16. apr. 2019 kl. 14:09 skrev arael <notifications@github.com>:

**Comment by hugoroy** [comment]
That still happens to me.

There is no line in the config. Should I use cmark or marked?

**Comment by gauteh** [comment]
Both should be possible to use.
