### ISSUE TITLE
astroid does not save the sent messages

### ISSUE THREAD

**Issue by arael** [astroidmail/astroid#631]
For some reason Astroid does not save the sent messages anymore after I have updated to Ubuntu 19.04. 

The messages are sent but are not saved inside 'Sent Items'.

I have tried from mutt and the messages are saved and labeled correctly.

Just in case I have compiled the last version.

astroid version: v0.14-53-gaae4c520

this is my config:

{
    "astroid": {
        "config": {
            "version": "11"
        },
        "notmuch_config": "\/home\/arael\/.notmuch-config",
        "debug": {
            "dryrun_sending": "false"
        },
        "hints": {
            "level": "0"
        },
        "log": {
            "syslog": "false",
            "stdout": "true",
            "level": "debug"
        }
    },
    "accounts": {
        "josicg": {
            "name": "My Name",
            "email": "my@email.address",
            "gpgkey": "",
            "always_gpg_sign": "false",
            "sendmail": "/usr/bin/msmtp -i --account=work -t --read-envelope-from",
            "default": "true",
            "save_sent": "true",
            "save_sent_to": "\/home\/arael\/mail\/Sent\/Items\/",
            "additional_sent_tags": "sent",
            "save_drafts_to": "\/home\/arael\/mail\/Drafts\/",
            "signature_separate": "false",
            "signature_file": "",
            "signature_file_markdown": "",
            "signature_default_on": "true",
            "signature_attach": "false",
            "select_query": ""
        }
    },
    "startup": {
        "queries": {
            "inbox": "tag:inbox",
            "support": "tag:support"
        }
    },
    "terminal": {
        "height": "10",
        "font_description": "default"
    },
    "thread_index": {
        "page_jump_rows": "6",
        "sort_order": "newest",
        "cell": {
            "font_description": "default",
            "line_spacing": "2",
            "date_length": "10",
            "message_count_length": "4",
            "authors_length": "20",
            "subject_color": "#807d74",
            "subject_color_selected": "#000000",
            "background_color_selected": "",
            "background_color_marked": "#fff584",
            "background_color_marked_selected": "#bcb559",
            "tags_length": "80",
            "tags_upper_color": "#e5e5e5",
            "tags_lower_color": "#333333",
            "tags_alpha": "0.5",
            "hidden_tags": "attachment,flagged,unread"
        }
    },
    "general": {
        "time": {
            "clock_format": "local",
            "same_year": "%b %-e",
            "diff_year": "%x"
        },
        "tagbar_move": "tag"
    },
    "editor": {
        "cmd": "gvim -geom 10x10 --servername %2 --socketid %3 -f -c 'set ft=mail' '+set fileencoding=utf-8' '+set ff=unix' '+set enc=utf-8' '+set fo+=w' %1",
        "external_editor": "false",
        "charset": "utf-8",
        "save_draft_on_force_quit": "true",
        "attachment_words": "attach",
        "attachment_directory": "~",
        "markdown_processor": "cmark",
        "markdown_on": "false"
    },
    "mail": {
        "reply": {
            "quote_line": "Excerpts from %1's message of %2:",
            "mailinglist_reply_to_sender": "true"
        },
        "forward": {
            "quote_line": "Forwarding %1's message of %2:",
            "disposition": "inline"
        },
        "sent_tags": "sent",
        "message_id_fqdn": "",
        "message_id_user": "",
        "user_agent": "default",
        "send_delay": "2",
        "close_on_success": "false",
        "format_flowed": "false"
    },
    "poll": {
        "interval": "30",
        "always_full_refresh": "true"
    },
    "attachment": {
        "external_open_cmd": "xdg-open"
    },
    "thread_view": {
        "open_html_part_external": "false",
        "preferred_type": "plain",
        "preferred_html_only": "false",
        "allow_remote_when_encrypted": "false",
        "open_external_link": "xdg-open",
        "default_save_directory": "~",
        "indent_messages": "false",
        "gravatar": {
            "enable": "true"
        },
        "mark_unread_delay": "0.5",
        "expand_flagged": "true"
    },
    "crypto": {
        "gpg": {
            "path": "gpg2",
            "always_trust": "true",
            "enabled": "true"
        }
    },
    "saved_searches": {
        "show_on_startup": "false",
        "save_history": "true",
        "history_lines_to_show": "15",
        "history_lines": "1000"
    }
}

**Comment by arael** [comment]
more details. This is from the log when trying to send the message:

[11:09:29] [0x00007f7dfbdc9700] [M] [info] db: adding sent message: /home/arael/mail/Sent/Items/1557479330.b018sqgztm.astroid@mywork.domain.none:2,
[11:09:29] [0x00007f7dfbdc9700] [M] [error] db: error adding message: 4
[11:09:29] [0x00007f7dfbdc9700] [M] [error] db: file seems to have been moved, ignoring - probably a race condition with some syncing program.
[11:09:29] [0x00007f7dfbdc9700] [M] [info] db: closing db.

**Comment by gauteh** [comment]
Yes, could you try without offlineimap? Also try doing notmuch new and refresh the view in astroid.

**Comment by arael** [comment]
Sorry, it is not a bug. It is a configuration issue.

I have this: "save_sent_to": "\/home\/arael\/mail\/Sent\ Items\/" and I don't know how to quote that space properly.

I have tried:
"\/home\/arael\/mail\/Sent\ Items\/"
"\/home\/arael\/mail\/'Sent Items'\/"
But none works. Any hint? Maybe I should use a soft link?

**Comment by gauteh** [comment]
I dont think you need to escape or quote  it additionally inside the quotes.

fre. 10. mai 2019 kl. 13:38 skrev arael <notifications@github.com>:

**Comment by arael** [comment]
You are indeed right. I didn't need the additional quotes for the directory name with space.

Thank you very much.

**Comment by arael** [comment]
I am sorry to bothering you again but now I have solved the issue half way.

Now the mail is saved in the Sent Items but not in the correct place:

This is my Sent Items directory:

~/m/Sent Items ❯❯❯ ls -l
total 268
-rw-rw-r-- 1 arael arael    395 May 10 14:27 1557491249.yur9wbhmjk.astroid@mydomain.none:2,
drwx------ 2 arael arael 258048 May 10 14:27 cur
drwx------ 2 arael arael   4096 May 10 12:40 new
drwx------ 2 arael arael   4096 May 10 14:26 tmp
~/m/Sent Items ❯❯❯ 


As you can see the message is not placed correctly.

Also, most of my other messages have this kind of name format:

'1557487116_4.5499.mydomain,U=9882,FMD5=bc66aead267922ff6f696dda008c6475:2,S'

But the one sent by astroid is different. Is this still a configuration problem?

Thank you very much.

**Comment by gauteh** [comment]
You can put it in the cur or new sub-dir, offlineimap will probably rename it to the U= scheme once it also exists on the IMAP server.

**Comment by arael** [comment]
I have opted for cur and now everything works.
Thank you very much!
