### ISSUE TITLE
two macOS build patches

### ISSUE THREAD

**Issue by c-alpha** [astroidmail/astroid#633]
While working on c-alpha/astroid#25, I discovered two isuues with the `CMakeLists.txt`:

1. gtkmm-3 now requires gobject-2, which in turn requires libffi. Hence, libffi is no longer exclusive to builds with plugins, but is needed for all builds. This is fixed by this patch: [libiffi.patch.txt](https://github.com/astroidmail/astroid/files/3188192/libiffi.patch.txt)

2. The linker flags for libsoup were missing from the cmake file. Not sure why and how it used to build on other platforms, but broke the build on macOS. This is fixed by this patch: [libsoup.patch.txt](https://github.com/astroidmail/astroid/files/3188193/libsoup.patch.txt)

**Comment by gauteh** [comment]
Thanks, merged.
