### ISSUE TITLE
Run separate instances with separate configuration?

### ISSUE THREAD

**Issue by rasmuse** [astroidmail/astroid#634]
Thanks for making Astroid! It's really cool software.

I would like to run two instances of Astroid with separate configurations, separate notmuch databases, everything separate. It seems Astroid is really not designed to do this, but I tried anyway. My attempts so far are documented here: https://rasmuse.github.io/multiple-instances-astroid-mail.html

The short version is that I can start the different configs one at a time, but not both simultaneously.

Any ideas about how I could get it to work? I really don't understand the internals of Astroid (as you can gather from the post).

Many thanks in advance.

**Comment by gauteh** [comment]
This has come up before and I dont think we found a solution at the time. You can use the `-c` flag to specify a different directory. It is also possible to use `ASTROID_DIR` for resources (and thus different theme files, at least in the debug build). The problem with different intances is that we use `Gtk::Application` which just opens a new window if you try to re-launch an astroid instance. In this case you might want to run the second astroid under a different dbus (but that is probably likely to break a few other things). Maybe a few modifications is needed to make this work.

**Comment by rasmuse** [comment]
Thanks for the prompt reply!

Follow-up question: if I use the `-c` flag, where will Astroid put the saved searches file? Is `-c path/to/config` generally a sufficient solution to run separate accounts (if only one at a time)?

I guess we can close this issue since it is a known issue and apparently not high on the priorities list?

**Comment by gauteh** [comment]
Thats a good point, no, the other paths will not be updated. Then you currently have to use your method. Not sure if we have another open issue for it, but unfortunately no, it is not at the top of the list.

**Comment by rasmuse** [comment]
OK. Thank you again for the quick feedback!

I guess a simple solution would be to create a `--config-dir` flag, if it is not necessary to also separate `.cache`, `.data`, and `.runtime`. Anyway, to me that's not much use unless the application can be run in simultaneous separate instances anyway.

Closing the issue for now, if you agree, so you can focus on more pressing tasks :)

**Comment by gauteh** [comment]
Sounds good :)

**Comment by igoralmeida** [comment]
For future endeavors, what would be a sane-but-not-terribly-difficult way to run different instances?
IOW, how unsuccessful would I be if I tried to replace `Gtk::Application::*` calls with actual object method calls?

**Comment by Lattitude75** [comment]
I have come across this [question](https://github.com/astroidmail/astroid/search?q=gtk%3A%3Aapplication&type=Code) on StackOverflow where it seems the APPLICATION_NON_UNIQUE flag can be used to open multiple instances. Would this be of some help here? @rasmuse @igoralmeida might also check this out.

The ability to launch multiple instances is very important for me too. There are many instances when I need to refer to two mails simultaneously. This feature I think, is necessary.
