### ISSUE TITLE
gpg.always_trust doesnt work with gmime 3..

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#638]
always trust isnt set in code anymore

**Comment by gauteh** [comment]
you have to set it in the gpg config with new gmime

**Comment by emdete** [comment]
The context doesnt take that flag anymore but the encrypt call itself (src/crypto.cc:246), so the line 251 should read:

```
always_trust?GMIME_ENCRYPT_ALWAYS_TRUST:GMIME_ENCRYPT_NONE,
```

do you agree?

**Comment by gauteh** [comment]
That seems right

**Comment by emdete** [comment]
do you want me to create a PR or is that line enough?

**Comment by gauteh** [comment]
Pr would be great👍

tir. 28. mai 2019 kl. 18:51 skrev M. Dietrich <notifications@github.com>:

**Comment by igoralmeida** [comment]
Tested and it works. Maybe close #637 as dupe?

**Comment by gauteh** [comment]
Fixed.
