### ISSUE TITLE
White text on white background in text emails with dark theme

### ISSUE THREAD

**Issue by donbex** [astroidmail/astroid#662]
As shown in the screenshots below, Astroid uses the text colour specified in the current GTK theme to render plain text emails, making them unreadable when using a dark theme. Note that HTML emails are rendered as expected.

This is puzzling, since the default `thread-view.scss` file (which I did not override) contains the following line:

```
.email {
    ...
    color: black;
    ...
}
```

![astroid_dark_theme](https://user-images.githubusercontent.com/894255/66146876-90cba180-e605-11e9-9363-fe7d2286354c.png)
![astroid_light_theme](https://user-images.githubusercontent.com/894255/66146879-91643800-e605-11e9-8658-1405a46e4b67.png)

**Comment by gauteh** [comment]
part.scss styles the part in the iframe.

**Comment by donbex** [comment]
> part.scss styles the part in the iframe.

Thanks, adding
```
body {
  color: black;
}
```
to a custom `part.scss` fixed the issue. It might be worthwhile putting this in the default file, since it already forces the background to be white.

**Comment by gauteh** [comment]
True, happy to review a PR 🙂

fre. 4. okt. 2019, 02:46 skrev Alessandro Pezzoni <notifications@github.com
