### ISSUE TITLE
HTML composing?

### ISSUE THREAD

**Issue by bjesus** [astroidmail/astroid#666]
Hi, thanks for Astroid!

I was wondering if it's currently possible or if there are any plans to support HTML message composing in the future? I know it's not a popular feature and that we all like to hate HTML messages, but for some of us it can be crucial. Big chunk of the messages I send are in Hebrew, which is a Right-to-left language. For them to be properly shown, I really need to wrap them in a `<div style="direction: rtl;">`. I guess that in an ideal world that wouldn't be necessary because the recipient's client would somehow recognize the direction by itself, but currently it's just not the case. 

I was thinking, if it was possible to compose & reply with an HTML message that could be edited in an external editor, we could either write the HTML ourselves or even direct it to some graphical HTML editor. Sounds like a nightmare for us CLI lovers, yes, but I thought maybe Astroid will be more open to implement it because it's already a graphical tool.

**Comment by gauteh** [comment]
Hi, is this somehow achievable through the markdown option currently? Otherwise, not opposed at all :)

**Comment by bjesus** [comment]
Awesome! I see now that Astroid is using Marked to parse its markdown markup, and it seems like Marked does support inline HTML. I'll try it and report back shortly. Thank you!

**Comment by bjesus** [comment]
Glad to confirm that this is indeed possible using the Marked (and possibly others) markdown parser. I have encountered some other issues but will open separate tickets if I can't figure them out. Thank you!

**Comment by gauteh** [comment]
Great!
