### ISSUE TITLE
Too high minimum width for the window

### ISSUE THREAD

**Issue by bjesus** [astroidmail/astroid#667]
Hi again,
I've noticed I can't resize Astroid to take just one half of my screen (or less). It seemed like some hard-coded minimum width that's specified somewhere. I tracked it down to this line:
https://github.com/astroidmail/astroid/blob/35660d486bed3c856603dcff8e8b52153e8e8da9/src/command_bar.cc#L30

After changing it to 300, it seems to work just fine. But I'm wondering, why is there a a minimum width setting in first place? What's the use of it?

Thank you!

**Comment by gauteh** [comment]
I think it was just to make it look good by default. But there's probably
another setting which doesn't prevent it from being lower. PR welcome :)

**Comment by bjesus** [comment]
Done!
