### ISSUE TITLE
Co-maintainer?

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid#669]
If anyone is interested in being a co-maintainer, please let me know.

**Comment by glacambre** [comment]
Hi @gauteh. Is the reason you're looking for a co-maintainer that you don't use Astroid anymore?

**Comment by gauteh** [comment]
Hi @glacambre, I am unfortunately not using it currently due to a couple of job changes, so stuck in GMail right now.

**Comment by teto** [comment]
probably not a solution in a shortterm but https://github.com/rycee/home-manager can generate configurations for astroid/alot/mutt/getmail/offlineimap/etc based on a your account description.
Looking forward to the next improvements on astroid, the best notmuch GUI out there.

**Comment by duckdalbe** [comment]
I'm not stepping up, but I'd like to thank you @gauteh for building and maintaining this great MUA! It is a joy to use already, and I would love to see future improvements!  💕

(Sorry if this is not the right place for this comment.)

**Comment by gauteh** [comment]
Fup Duck writes on April 16, 2020 19:10:
> I'm not stepping up, but I'd like to thank you @gauteh for building
> and maintaining this great MUA! It is a joy to use already, and I
> would love to see future improvements!  💕
>

Thanks :)

-- gaute

**Comment by paulgoetze** [comment]
@gauteh In case you’re still looking for (co-)maintainers you could consider submitting astroid to [adoptoposs.org](https://adoptoposs.org). There’s a bunch of people interested in C/C++ and they will also get notified about newly added projects.

**Comment by hugoroy** [comment]
I’m a bit late to the party, but I really hope that we are able to continue maintenance and development of Astroid. This really is the best email user agent I have ever used. This has helped me a lot in busy times :-)

So, huge thanks to @gauteh!! And best wishes for your job chances!

I hope I will have some time in the near future to continue with bug reporting, wiki maintenance, and globally just helping new users :-)

**Comment by matthiasbeyer** [comment]
I am currently playing a bit with astroid (as a long time mutt user) and I really like it.

I'd love to see continued development on this. I also opened some issues and am currently building from source to debug something. Would love to see some progress here, maybe we can get ourselves together to work on this?

**Comment by gauteh** [comment]
Absolutely, I am using astroid everyday so I would love to see the
continuation of astroid.

tir. 21. jul. 2020, 17:00 skrev Matthias Beyer <notifications@github.com>:

**Comment by gauteh** [comment]
By the way, take a look at #689 (especially since you are into rust). If I were to re-do astroid I would do as much as possible in rust.

**Comment by gauteh** [comment]
@jorsn im closing this.
