### ISSUE TITLE
run-hook does not inherit notmuch_config?

### ISSUE THREAD

**Issue by igoralmeida** [astroidmail/astroid#670]
For context: I'm trying to use astroid with different notmuch databases, but something has come up that might make it... difficult.

I wanted `a` to remove both `inbox` and `unread`, so that's what I came up with based on the [wiki page](https://github.com/astroidmail/astroid/wiki/User-defined-keyboard-hooks):
```
thread_index.run(notmuch tag -inbox -unread thread:%1, notmuch tag +inbox +unread thread:%1)=a
```

The problem is that, while this works when I'm using the "default" astroid config (which points to my "default" notmuch database), it does not seem to know that it must use a different `NOTMUCH_CONFIG` (or pass `--config` to notmuch) with my "alternate" astroid config, even though the different `notmuch_config` setting is there.

How could I solve this?

**Comment by gauteh** [comment]
Run hooks are simple shell commands so they do not know anything about astroid. In this case, and in many of the examples, the `notmuch` command is used. You could try using `NOTMUCH_CONFIG=.. notmuch tag ...` in your hook.

**Comment by igoralmeida** [comment]
The hook cannot know which astroid config (and therefore which notmuch database) I'm using currently, so that won't work.

Maybe astroid itself needs to be called with different NOTMUCH_CONFIG envvars, so child processes like hooks could inherit them? In that case it wouldn't matter which `notmuch_config` is in the config file, I assume.

**Comment by igoralmeida** [comment]
Indeed, calling astroid with NOTMUCH_CONFIG set does work. A bit redundant, but that's something I can live with.

**Comment by gauteh** [comment]
Ok, great!
