### ISSUE TITLE
3 testsuite errors: message reading produces the same output as compose message input

### ISSUE THREAD

**Issue by jonassmedegaard** [astroidmail/astroid#676]
recent builds on Debian fails testsuite at 3 places, with identical error message:
> message reading produces the same output as compose message input

More detail in Debian bugreport at https://bugs.debian.org/952167
Full build log is at http://qa-logs.debian.net/2020/02/22/astroidmail_0.15-3_unstable.log and should also appear soon at https://buildd.debian.org/status/package.php?p=astroidmail&suite=experimental

**Comment by jonassmedegaard** [comment]
bump

**Comment by stefanor** [comment]
Took a look into this. In Debian regression started with gmime 3.2.4, the tests passed with gmime 3.2.1.

The offending change appears to be jstedfast/gmime@2dd1be81555d787ff1ff03b11e5cb4b9e81630d6.

Putting a trailing newline on the test bodies avoids this test failure.

I think it's reasonable to append a trailing newline to a `text/plain` body. I notice that Python's MIME implementation will do this, too.

**Comment by jonassmedegaard** [comment]
Quoting Stefano Rivera (2020-05-09 03:49:22)
> Took a look into this. In Debian regression started with gmime 3.2.4, the tests passed with gmime 3.2.1.
> 
> The offending change appears to be jstedfast/gmime@2dd1be81555d787ff1ff03b11e5cb4b9e81630d6.
> 
> Putting a trailing newline on the test bodies avoids this test failure.
> 
> I think it's reasonable to append a trailing newline to a `text/plain` body. I notice that Python's MIME implementation will do this, too.

Great. Thanks!

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
