### ISSUE TITLE
Segfault when trying to compose email (GtkSocket: only works under X11)

### ISSUE THREAD

**Issue by axelsimon** [astroidmail/astroid#680]
Hi,
Trying to use astroid (v0.15-14-g964c1c70) under Fedora 30, compiled from source.

Anytime i try an action related to composing email (compose, reply, reply all) astroid segfaults and the following error is shown in a terminal:
> (astroid:9210): Gtk-WARNING **: 12:19:26.329: GtkSocket: only works under X11
> (astroid:9210): Gdk-WARNING **: 12:19:26.329: gdkwindow-x11.c:5633 drawable is not a native X11 window

I see that there was already an issue reported about this, over 3 years ago, #198. I'm opening a new one because so much time has passed.

Wayland is the default in Fedora and likely in other distros too, and in any case the future of graphical servers so astroid should probably not depend on something that "only works under X11".

Thanks!

**Comment by gauteh** [comment]
Hi, you can now use an external editor. This should have been the default when compiling without X11. But the config might have come from somewhere else. Don't think embedded windows work through gtksocket on wayland yet.

**Comment by axelsimon** [comment]
Thanks. I'm using the Flatpak, which i suppose has no idea whether it will run with or without X11, and so does this.

I found how to force use of the external editor in the [configuration](https://github.com/astroidmail/astroid/wiki/Configuration-Reference#editor), but it doesn't work, even after installing the `vim-X11` package. It opens a window that looks like it's going to let me edit, but actually doesn't. Pressing <enter> just flashes the window and nothing happens.
This is turning into a lot of effort just to answer some emails…
