### ISSUE TITLE
Apply hook on all marked messages

### ISSUE THREAD

**Issue by tenllado** [astroidmail/astroid#684]
This is not an issue, is a feature-request.

I would like to be able to apply the hooks I have binded to some keys to all the marked threads in the thread view, so that when I press ; astroid would give me the option to apply my hooks with the same key binding.

**Comment by gauteh** [comment]
Is this the same as #683?

**Comment by tenllado** [comment]
Yes, indeed it is. I am sorry.

**Comment by tenllado** [comment]
I will close the issue then.
