### ISSUE TITLE
[Help] How to actually send mail

### ISSUE THREAD

**Issue by skyler544** [astroidmail/astroid#699]
I guess I'm too dense for such a simple task. I have mstmp set up and can send mail directly from the command line, with, e.g. `echo test | msmtp recipient@example.com` but how am I supposed to send a message I've composed in the embedded gvim in astroid? if I try to use `:! msmtp --read-envelope-from -i -t` (the command from the wiki in the section about sending, which I also have in my `~/.config/astroid/config`), nothing seems to happen. The command seemingly runs forever and no email is sent.

**Comment by gauteh** [comment]
You close vim and use y to send the email from astroid

tir. 1. sep. 2020, 14:07 skrev skyler544 <notifications@github.com>:

**Comment by skyler544** [comment]
thank you!
