### ISSUE TITLE
query and open message from the command line

### ISSUE THREAD

**Issue by jorsn** [astroidmail/astroid#701]
It would be really handy if astroid allowed to give a query on the command line. If the query is a message id (`id:*`/`mid:*`) or a `file:*` it should then open thread view focused on the message directly.

This would glue astroid together with notes, so that one could reference mails and open them in astroid anywhere.

**Comment by aecepoglu** [comment]
I'm surprised this isn't vocalised more often. I also want the same feature.

:+1:

**Comment by jorsn** [comment]
Duplicate of #37.
