### ISSUE TITLE
Astroid trims the output of the markdown processor

### ISSUE THREAD

**Issue by bjesus** [astroidmail/astroid#704]
It seems that Astroid is removing some of the output of the markdown processor.

When setting the processor to `cat`, you'd expect to get the exact same content back. However, sending it text in Hebrew, returns with much the text left out.

```
בדיקה בדיקה
מה קורה
בדיקה בדיקה
מה קורה
בדיקה בדיקה
מה קורה
בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה.

מה קורה


* שלום שלום
* שלום שלום
* שלום שלום
* שלום שלום
```

Comes back as:
```
בדיקה בדיקה מה קורה בדיקה בדיקה מה קורה בדיקה בדיקה מה קורה בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיקה, בדיקה בדיק
```

Of course in real life I don't use `cat` as my markdown processor, but the same happens with `marked` or anything else. When I check their actual output it seems full, but in Astroid the mail looks trimmed, and is also sent trimmed.

The problem doesn't occur when sending English-only emails.

**Comment by gauteh** [comment]
Hi, i know this issue has come up before. Think maybe @hugoroy reported. Could be related to waiting for filter-program or closing/flushing of streams.

**Comment by bjesus** [comment]
Sorry, I've just checked against the latest git version and I actually don't see the same behviour. I wasn't using it because the AUR PKGBUILD file includes some patch file (`test-compose.patch`) that made the package fail building. Removing the patch made the build work, and the new Astroid doesn't seem to suffer from the issue. My bad!

**Comment by gauteh** [comment]
That's good.
