### ISSUE TITLE
search for folder

### ISSUE THREAD

**Issue by kahironimashte** [astroidmail/astroid#705]
Hi, I read, that with notmuch one can search for mails by folders [doku](https://notmuchmail.org/manpages/notmuch-search-terms-7/). 

How would I search for folders in Astroid?

I tried folder:accountname.subfolder

My mails are stored in ~/mails/accountname1, ~/mails/accountname2, etc.

**Comment by gauteh** [comment]
maybe path:accountname1/**

**Comment by kahironimashte** [comment]
Yes, path:accountname1/** works, thank you for the hint!

 But I cannot make it work for subfolders like path:accountname1/Junk. 

Does it work for you? Did you try the "folder:"-synthax on your machine?

**Comment by gauteh** [comment]
I'm not sure

**Comment by kahironimashte** [comment]
When in terminal: `notmuch search folder:accountname/JUNK` gets me a list of junk mail from that folder. 

When in Astroid: I search for `folder:accountname/JUNK` then search is empty. The same applies for `folder:accountname.JUNK`

**Comment by kahironimashte** [comment]
When in terminal: `notmuch search folder:accountname/Junk` gets me a list of junk mail from that folder. 

Also in Astroid it works with `folder:accountname/Junk`

To get the right path terminal auto completion for notmuch is helpful.
