### ISSUE TITLE
go to next thread from last tread index view

### ISSUE THREAD

**Issue by kahironimashte** [astroidmail/astroid#706]
Hi, 
I saw a Video on [Superhuman Mail](https://youtu.be/zaxAdRlyZQ8?t=742) on how they keep you in focus. The trick is that you can work through your mail with a "next" function related to your last selection or search. 

Would it be possible to add a "next tread" function which selects the next thread based on the specific thread index view (TIV) that I visited last?

**Example usage** "plow through your github mail": 
- search: _from:*github.com AND tag:unread_
- open first mail in thread index for those results. 
- read / tag the message. 
- hit "next thread from last TIV" function key
- read next mail _from:*github.com AND tag:unread_ and possibly tag it.
- repeat last 2 steps n times untill there are now more unread mails from github.
- exit thread view

**Comment by gauteh** [comment]
Yes, should already be keybindings for this. One of the multi-key ones.

**Comment by gauteh** [comment]
https://github.com/astroidmail/astroid/blob/0723bf78587eb9c36fa304e33e53b0dfae112589/src/modes/thread_view/thread_view.cc#L1564

**Comment by kahironimashte** [comment]
Thank you, for the info and your effort for Astroid!

**Comment by gauteh** [comment]
Thanks 😊
