### ISSUE TITLE
sending mail hangs astroid with adwaita-icon-theme 42 installed

### ISSUE THREAD

**Issue by Hello71** [astroidmail/astroid#715]
Attempting to send mail causes the following error to be printed:

```
** (astroid:66541): CRITICAL **: 00:29:09.255:
unhandled exception (type Glib::Error) in signal handler:
domain: gtk-icon-theme-error-quark
code  : 0
what  : Icon 'mail-send' not present in theme Adwaita
```

The mail is not sent, and astroid hangs displaying "sending message..". Pressing "q" or other key bindings has no effect; the program must be killed. Downgrading to adwaita-icon-theme 41 resolves the issue.

**Comment by Hello71** [comment]
According to https://github.com/GNOME/adwaita-icon-theme/blob/1095485b06702dd0d2b232c5896e3e0d7340ad51/NEWS#L9-L10:

> - fullcolor: prune legacy fullcolor lowres, apps like Evolution ship
>   their assets from now on

which... I feel like they have missed the point of an icon theme? but it is what it is, and I doubt they can be convinced to change it back, so I guess astroid needs to either ship its own icons or just not show one here.

**Comment by gauteh** [comment]
Yeah, that was kind of meaningless... I'd be happy to accept a PR for a different icon.
