### ISSUE TITLE
How to delete messages not documented

### ISSUE THREAD

**Issue by mcp292** [astroidmail/astroid#722]
How do you delete messages in Astroid?

I assume you add a tag like `trash`. If so, this is not documented. 

Further, is there a way to bind this so that say in thread index view hitting `d` automatically replaces all tags with `trash` on the focused message?

**Comment by mcp292** [comment]
In addition, it would be very helpful to document a way to delete a message from thread view and automatically bring up the next chronological message in thread view.

The idea is you would start from the oldest unread message and start reading, deleting, and sorting from there.

**Comment by dnebauer** [comment]
Is #452 of any help?

**Comment by mcp292** [comment]
Yes, thank you. Not what I was expecting.
