### ISSUE TITLE
segfault when attaching a file to an email

### ISSUE THREAD

**Issue by mklinik** [astroidmail/astroid#726]
I'm getting a segfault when trying to attach a file to an email.

Steps to reproduce:

- start astroid
- `m` to compose new message (I'm using vim, so vim pops up)
- fill `To:`, `Subject:` and body with something
- save and close vim
- In the New Message tab, press `a` to attach a file
- In the file selector, select a random file from my home directory, click "Attach" button

Result: astroid crashes with `Segmentation fault (core dumped)`

I'm using astroid compiled from source, current master 7c2022f06a4146ad62e858bcaacdb4ee817851b9, Arch linux.

Here is a complete log of the procedure described above in gdb, with backtrace after the segfault happened https://gist.github.com/mklinik/f15cab0a048cbc95e84d6161b6c5975b

The last message I sent with attachment was on Feb 22 2023, back then it still worked. I updated Arch and recompiled astroid, same result.

**Comment by stephancb** [comment]
Not reproduced on Fedora 37: I recompiled two days ago (new laptop), and then sent emails with attachment (also using vim as external editor).

**Comment by stephancb** [comment]
Found it!

src/compose_message.cc:784

\- refptr<Gio::File> fle = Glib::wrap (file, false);
+refptr<Gio::File> fle = Glib::wrap (file, true);

`wrap` needs to copy all fields of `file`. Only in the latest update of GLib the `wrap(.., false)` seems to segfault, before it probably by chance went unnoticed.

Should I attempt to create a pull request?

**Comment by gauteh** [comment]
For sure!

**Comment by mklinik** [comment]
Awesome! Thank you so much @stephancb for figuring it out and fixing it.

**Comment by noideawhatwhat** [comment]
Arch linux has this as the latest build

extra/astroid 0.16-11 [installed]
    A graphical threads-with-tags style, lightweight and fast, e-mail client for Notmuch

The Arch version segmentation faults when attaching a file to an email in the same way as above.

Webkit version in Arch is webkit2gtk-4.1 2.42.4-2 so it seems to fit.

Is there any chance of a release with this fix? That would likely lead to Arch updating its package.

**Comment by jorsn** [comment]
@noideawhatwhat Is it still the case with v17? Can you provide more info (e.g. logs)?
