### ISSUE TITLE
Can't open attachments

### ISSUE THREAD

**Issue by danielkrajnik** [astroidmail/astroid#729]
Does astroid allow for opening attachments? Seems like clicking on the attachment doesn't have any effect. This system does have a default pdf reader that should handle this. When clicking no output is shown in the console from where astroid was started.

![image](https://github.com/astroidmail/astroid/assets/15096799/feadabd7-f276-43e6-89f7-f482a6de5b1f)

**Comment by gauteh** [comment]
Yes, there is a keyboard binding and config option for opening.

søn. 4. jun. 2023, 00:37 skrev danielkrajnik ***@***.***>:

**Comment by danielkrajnik** [comment]
Thank you. Thanks to your tip I've managed to open the attachment by focusing on it and pressing Enter, but I couldn't find specific keybindings to open attachments?

Generating keybindings templates and grepping for "attach":
`src/astroid/devel/get_keys.py > ~/.config/astroid/keybindings.orig`

````
# edit_message.attach=a # Attach file, default: a
# edit_messsage.attach_mids=A # Attach messages by mids, default: A
# thread_index.forward_attached=UnboundKey () # Forward last message in thread attached, no defaults.
# thread_view.save=s # Save attachment or message, default: s
# thread_view.delete_attachment=d # Delete attachment (if editing), default: d
# thread_view.save_all_attachments=S # Save all attachments, default: S
# thread_view.forward_attached=UnboundKey () # Forward current message as attachment, no defaults.
````

none of them seem to `open` attachments?

**Comment by gauteh** [comment]
You can choose the external open command:
https://github.com/astroidmail/astroid/blob/master/src/chunk.cc#L585 with a
config option.

I'm pretty sure the wiki has some more stuff here on how to do antivirus
and making this more robust.

You can also save the attachment with another key.

søn. 4. jun. 2023, 16:31 skrev danielkrajnik ***@***.***>:

**Comment by danielkrajnik** [comment]
Sorry, I may be doing something wrong, but are you saying that adding this line:
` attachment.external_open_cmd`=C-O

to `.config/astroid/keybindings`
should assign it a keybinding? I've tried it just now (with a few combinations), but none of them seem to do anything. Opening a mail with an attachment and pressing this keybinding didn't seem to work?

**Comment by gauteh** [comment]
No, that's just for choosing which program opens it. The key is enter, or
the activate element key.

tir. 6. jun. 2023, 02:19 skrev danielkrajnik ***@***.***>:

**Comment by danielkrajnik** [comment]
sorry, I've removed my last reply shortly after posting it (incorrectly asking if `attachment.external_open_cmd`) was part of the `keybindings` file before realizing that it sits in the config). No worries, I agree that just highlighting it and pressing enter should be fine.
