### ISSUE TITLE
emails shown truncated with webkit 2.40.3

### ISSUE THREAD

**Issue by mklinik** [astroidmail/astroid#735]
A recent Arch system update gave me some new libraries, including webkit2gtk 2.40.3-1. With this version of webkit, emails are truncated in the thread view.

![astroid-email-cut-off-1](https://github.com/astroidmail/astroid/assets/520106/870da99c-d2ac-4889-b866-73569bb2cbbb)

![astroid-email-cut-off-2](https://github.com/astroidmail/astroid/assets/520106/fad836c0-b0c8-40d5-913e-66044c01d12c)

Downgrading to webkit2gtk-2.38.5-1 used to fix the issue.

```
# pacman -U https://archive.archlinux.org/packages/w/webkit2gtk/webkit2gtk-2.38.5-1-x86_64.pkg.tar.zst
```

However, some conflicts with other packages don't allow me to run the downgraded version of webkit anymore. I have to install 2.40.3-1.

**Comment by kirschner** [comment]
Hello @mklinik There are several people struggling with that issue at the moment. See also https://github.com/astroidmail/astroid/issues/720  or also a Debian Bug report by me https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036154 . Unfortunately at the moment it seems nobody is able to work on a fix. If anyone does I would be available to do testing.

**Comment by mklinik** [comment]
Okay, thanks for the reply. I'll close this as duplicate then.
