### ISSUE TITLE
please add function to advance to next unread email from thread-view

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#91]
it would be nice to have a function (bound to Tab for example) to jump to the next unread email when watching one alread (thread view). either by just advance or by pressing "S" and marking it as spam.

**Comment by gauteh** [comment]
maybe we can make a leader key like `,` and then the regular actions, which mean: do action, then open next unread in previous search.

in case the original search has been closed: do nothing
what if the cursor has been moved in the original search?

**Comment by emdete** [comment]
i would use Tab and S for "leaving" the thread-view of that thread and show the next unread thread wherever the cursor is in that search (the thread-view has to know from what search it was startet). i really like mutts behaviour to be able to read mails with a single key (Tab) without going back&forth.

i think as well that (even in thread-index) the Tab should wrap and seach from the top when no new mails are below. if the search was closed i would just either do nothing (or personally i prefere) to close the win (especially on S).

**Comment by gauteh** [comment]
M. Dietrich writes on February 23, 2016 10:24:
> i would use Tab and S for "leaving" the thread-view of that thread and show the next unread thread wherever the cursor is in that search (the thread-view has to know from what search it was startet). i really like mutts behaviour to be able to read mails with a single key (Tab) without going back&forth.

Technically two keys right? Tab and S or maybe just Tab-Tab to close and
jump to next? Anyway, the key would be configurable. I think we used ','
in sup, but Tab makes sense since it means jumping to the next unread in
thread-index already.

I think the best way to implement this is to create a
`open_next_unread_request` signal in ThreadView, then the ThreadIndex
that opened it can connect to it and do whatever it wants when the
signal is emitted. That way we don't have to take care of the
thread-index form the thread-view, and things will still work with lots
of thread-views opened from the same thread-index. And we don't need to
care about cleaning things up if the thread-index is closed before the
threadview.
 
> i think as well that (even in thread-index) the Tab should wrap and seach from the top when no new mails are below. if the search was closed i would just either do nothing (or personally i prefere) to close the win (especially on S).

Agreed, but only if all messages have been loaded. Also Shift-Tab should
jump backwards.

**Comment by gauteh** [comment]
Gaute Hope writes on February 23, 2016 12:52:
> M. Dietrich writes on February 23, 2016 10:24:
>> i think as well that (even in thread-index) the Tab should wrap and seach from the top when no new mails are below. if the search was closed i would just either do nothing (or personally i prefere) to close the win (especially on S).
> 
> Agreed, but only if all messages have been loaded. Also Shift-Tab should
> jump backwards.
> 

Tab wraps, M-Tab searches backwards (and wraps).

**Comment by gauteh** [comment]
Moved to Shift-Tab.

**Comment by gauteh** [comment]
For reference: some attempts at implementing Shift support:
https://github.com/gauteh/astroid/tree/ky-shift

doesn't work on Shift+? since questionmark needs shift to be made.
Unresolved.

**Comment by hugoroy** [comment]
Isn't that resolved now?

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 0:34:
> Isn't that resolved now?

It is for the next mail in the same thread. But I think the intention of
the original issue was to close the current thread and move to the next
(unread) thread in the thread-index that the thread-view was opened
from. With actions for 'archiving' as well, think working through
'tag:inbox'. Just press ',' then 'a' which archives the current thread,
then closes it and moves to the next. '.' could perhaps be used for the
same, but only closes the thread without opening a new.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 2, 2017 8:24:
> Hugo Roy writes on mars 2, 2017 0:34:
>> Isn't that resolved now?
> 
> It is for the next mail in the same thread. But I think the intention of
> the original issue was to close the current thread and move to the next
> (unread) thread in the thread-index that the thread-view was opened
> from. With actions for 'archiving' as well, think working through
> 'tag:inbox'. Just press ',' then 'a' which archives the current thread,
> then closes it and moves to the next. '.' could perhaps be used for the
> same, but only closes the thread without opening a new.

OK. I think this keybinding would make sense in the pane for 
thred-view (#290), but not in a standalone tab.

Honestly, I'd be disoriented if pressing Tab at the end of a thread
opens a completely new thread *in the same tab*. I assume I would not be
the only one. I like the current behaviour of Tab.

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 9:22:
> ↪ Gaute Hope / mars 2, 2017 8:24:
>> Hugo Roy writes on mars 2, 2017 0:34:
>>> Isn't that resolved now?
>> 
>> It is for the next mail in the same thread. But I think the intention of
>> the original issue was to close the current thread and move to the next
>> (unread) thread in the thread-index that the thread-view was opened
>> from. With actions for 'archiving' as well, think working through
>> 'tag:inbox'. Just press ',' then 'a' which archives the current thread,
>> then closes it and moves to the next. '.' could perhaps be used for the
>> same, but only closes the thread without opening a new.
> 
> OK. I think this keybinding would make sense in the pane for 
> thred-view (#290), but not in a standalone tab.
> 
> Honestly, I'd be disoriented if pressing Tab at the end of a thread
> opens a completely new thread *in the same tab*. I assume I would not be
> the only one. I like the current behaviour of Tab.

Yeah, it would require a second key-press. When I think about it would
still require the same amount of keys to just close, archive, open or
close, next, open. So I agree, we can close this.

**Comment by gauteh** [comment]
#327
