### ISSUE TITLE
cache and check for changed attachments

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#99]
The file open dialog should allow keyboard input of the directory and file names.

It should as well remember the last location where the user navigated to (to make it easier to attach several files from a directoy which is a quite common case i assume).

btw: i did not check but will astroid check if the file changed before sending (as mutt does) and ask if it should recode the attachment?

**Comment by gauteh** [comment]
M. Dietrich writes on February 26, 2016 10:44:
> The file open dialog should allow keyboard input of the directory and file names.

I don't know if this can be done with the Gtk FileChooser dialog, could
you check?

> It should as well remember the last location where the user navigated to (to make it easier to attach several files from a directoy which is a quite common case i assume).

Agreed, same for saving dialogs.

> btw: i did not check but will astroid check if the file changed before sending (as mutt does) and ask if it should recode the attachment?

If I remember correctly I don't load the attachment before sending,
which probably isn't the best way. In case you save a draft with an
attachment that you delete by the time you actually want to send the
message.

**Comment by emdete** [comment]
the first point is wrong: if you just blindly start typing a textedit apears and works just fine (too sad it's not already there to show it's possible).

the last point: i like mutts behaviour. encode when attaching, warn when changed.

**Comment by gauteh** [comment]
M. Dietrich writes on February 29, 2016 23:29:
> the first point is wrong: if you just blindly start typing a textedit apears and works just fine (too sad it's not already there to show it's possible).

You could check if we could show it by default Gtk::FileChooserDialog,
otherwise isn't it a GTK+ issue?
 
> the last point: i like mutts behaviour. encode when attaching, warn when changed.

Yes, that makes sense.

**Comment by mardukbp** [comment]
Maybe [vimiv](https://github.com/karlch/vimiv/blob/master/vimiv) can provide some inspiration. Take a look at the functions `cmd_path` and `cmd_complete`. It is not like ido-mode in emacs but it could be a start.

**Comment by gauteh** [comment]
#239 always caches attachments. this means that if you change an attachment you need to re-attach it. this is the most consistent way to work across drafts (where they have always been cached)

**Comment by gauteh** [comment]
I think I'll close this. We are now caching attachments, and there isn't an easy way to store the attachment path when saving as drafts, which would be needed to check consistently for changes for drafts as well.
